danbooru/danbooru

app/assets/javascripts/notes.js
app/assets/stylesheets/specific/notes.css.scss
app/logical/sources/strategies/twitter.rb
app/models/post.rb
app/views/posts/partials/show/_edit.html.erb
app/views/posts/show.html.erb
config/deploy.rb
db/migrate/20150128005954_add_bit_flags_to_posts.rb
db/structure.sql

This is a new feature to embed text in the note boxes to remove the need to hover to read the text. It is conditionally activated on a per-post basis with a new boolean flag.

Embedded notes

---

app/views/post_flags/_new.html.erb
app/views/static/terms_of_service.html.erb

see http://danbooru.donmai.us/forum_topics/11877 for discussion

Update ToS and common flag reasons

---

app/logical/anonymous_user.rb
db/migrate/20150728170433_add_default_blacklist_to_users.rb

see http://danbooru.donmai.us/forum_topics/11877 for discussion
Only affects newly created accounts and anonymous. For now I made the default blacklist be:
```
spoilers
guro
scat
furry -rating:s
```

Add default blacklist

---

app/models/post.rb
test/unit/post_test.rb

Self explanatory, see commits and issue #2730.

Resolve aliases when removing negated tags (fix #2730)

---

app/views/static/_footer.html.erb
app/views/static/bookmarklet.html.erb
app/views/static/site_map.html.erb
config/application.rb
config/danbooru_default_config.rb

* Also replace references to Danbooru github with a configurable repo.
* Link commit hash in footer to github.
* Use the HEAD commit hash if running inside a git repo (for development, when running `rails server` inside the repo).

Replace references to "Danbooru" with <%= Danbooru.config.app_name %>

---

app/views/posts/partials/show/_notices.html.erb
app/views/uploads/new.html.erb

* Add self-uploading disclaimer to uploads page.
* Link to howto:flag in flag notice.

Link self-upload disclaimer on /uploads; link howto:flag in flag notices.

---

app/models/forum_post.rb
test/functional/forum_posts_controller_test.rb

Fixes bug in https://github.com/r888888888/danbooru/issues/2658#issuecomment-257428807.

Fix AmbiguousColumn exception in /forum_posts?search[creator_id]=1

---

app/models/comment_vote.rb
test/unit/comment_test.rb

Discussed in http://danbooru.donmai.us/forum_topics/9127?page=139#forum_post_122209.

Prevent users from upvoting their own comments.

---

app/controllers/user_feedbacks_controller.rb
app/models/user_feedback.rb
app/views/user_feedbacks/index.html.erb
app/views/user_feedbacks/show.html.erb
test/functional/user_feedbacks_controller_test.rb

As per discussion in http://danbooru.donmai.us/forum_topics/13460. This disallows mods from editing or deleting any feedback given to themselves, positive or negative.

Prevent mods from editing/deleting feedbacks given to themselves.

---

Gemfile.lock

Follow-up to 1314239326bf1126f32a6f3325463bbf78600c29.

Remove coinbase from Gemfile.lock.

---

app/controllers/concerns/saved_searches/check_availability.rb
app/controllers/saved_search_category_changes_controller.rb
app/controllers/saved_searches_controller.rb

Fixes #2795 by refactoring `check_availability` into a concern to avoid duplicating this code.

Fix #2795: "check_availability" bug with saved searches.

---

app/assets/javascripts/artist_commentaries.js
app/controllers/artist_commentaries_controller.rb
app/logical/sources/site.rb
app/views/artist_commentaries/_form.html.erb
app/views/artist_commentaries/_quick_search.html.erb
app/views/artist_commentaries/_secondary_links.html.erb
app/views/artist_commentaries/search.html.erb
config/routes.rb

Addresses issues #2561 and #2238.

Copy artist commentary (#2561, #2238)

---

app/logical/tag_name_validator.rb
app/models/post.rb
app/models/tag.rb
test/unit/post_test.rb
test/unit/tag_test.rb

This would enforce stricter rules for tag names. These things would be forbidden in tags:
* Blank names (e.g. ___).
* Non-ASCII characters (Japanese text).
* Non-printable characters (e.g. control characters < 0x20).
* Leading or trailing underscores, or consecutive underscores. Reason: `_foo__bar_` and `foo_bar` both render as `foo bar` in the tag list.
* Leading `-` or `~`, or `*` (-foo, ~foo, foo*bar). Currently these things are silently stripped, but that means tagging a post with e.g. `*-foo` tags the post with the invalid tag `-foo`.
* Tag type prefixes (so that e.g. `character:character:hatsune_miku` doesn't create the literal tag `character:hatsune_miku`).
* Metatags (order:score, user:evazion, etc).
These rules are a codification of existing practices. Since currently there are …

Enforce stricter rules for tag names

---

app/views/post_disapprovals/_compact_counts.html.erb
app/views/post_disapprovals/_counts.html.erb

Fixes #2914. Bug introduced in 83915a5.

Fix 'Posts Report "Reviewed by 0 Moderators"' (#2914).

---

app/controllers/post_versions_controller.rb
app/models/post_archive.rb
app/views/post_versions/_listing.html.erb
app/views/post_versions/index.html.erb

Fixes a few issues causing extraneous sql queries on /post_versions.

Fix N+1 queries issues on /post_versions

---

app/logical/sqs_service.rb

Fixes this exception on `/posts` when `Danbooru.config.aws_sqs_enabled?` is true but `Danborou.config.aws_sqs_reltagcalc_url` is not configured:
ArgumentError exception raised
missing required parameter params[:queue_url]
app/logical/sqs_service.rb:11:in `send_message'
app/models/tag.rb:674:in `update_related_if_outdated'
app/models/tag.rb:698:in `related_tag_array'
app/presenters/post_set_presenters/post.rb:49:in `related_tags_for_single'
app/presenters/post_set_presenters/post.rb:19:in `related_tags'
app/presenters/post_set_presenters/post.rb:8:in `initialize'
app/logical/post_sets/post.rb:181:in `new'
app/logical/post_sets/post.rb:181:in `presenter'
app/views/posts/index.html.erb:14:in `_app_views_posts_index_html_erb___3235672853362939702_47243208308540' …

sqs_service.rb: fix exception when related tags sqs not configured.

---

app/views/users/edit.html.erb

* Go to My Account > Settings > Advanced Settings
* Paste this in the frequent tags field:
```
</textarea>
<script>alert('xss')</script>
```
* Go back to the settings page.
* Observe a self-XSS.

Fix self-xss in favorite tags.

---

app/assets/javascripts/posts.js
app/views/posts/index.html.erb
app/views/posts/partials/index/_posts.html.erb
app/views/posts/show.html.erb

Fixes a problem with the saved search dropdown not working on the posts show page. The problem was that the dropdown was only initialized on the index page.

Fix saved search dropdown on post show page.

---

app/assets/javascripts/posts.js
app/views/static/keyboard_shortcuts.html.erb

Adds a `shift+F` hotkey for unfavoriting a post.
Discussion: https://danbooru.donmai.us/forum_topics/13985

/posts: add shift+F to unfavorite hotkey.

---

app/models/post.rb
app/presenters/post_presenter.rb

Adds a `data-is-favorited` attribute to post thumbnails. This is to make it possible to use custom CSS to mark posts that you have already favorited.

Add `data-is-favorited` attribute to post thumbnails.

---

app/views/comments/index.atom.builder
app/views/forum_topics/show.html.erb
app/views/posts/show.html.erb

Fixes #3081:
* Adds a comment feed discovery link on post show pages.
* Fixes the feed discovery link on forum topic show pages.

Fix #3081: ATOM discovery link issues.

---

app/assets/javascripts/related_tag.js
app/views/posts/partials/show/_edit.html.erb
app/views/uploads/new.html.erb

Fix #3061: Add "General" button for related tags on new/edit posts.

---

app/views/explore/posts/intro.html.erb

Fixes #3109 (was broken by 4631262374f63476ca56bd3beb9d77bd95bd2912).

Fix #3109: Fix autocomplete on intro page

---

app/models/user.rb

Fix #3123: Error with user JSON query when the Archive service is not installed

---

app/assets/stylesheets/specific/pools.scss
app/models/post.rb
app/views/moderator/post/queues/_post.html.erb
app/views/moderator/post/queues/random.html.erb
app/views/moderator/post/queues/show.html.erb
app/views/pools/_inline_list.html.erb

Fix #3125: Show pools in mod queue

---

app/helpers/post_flags_helper.rb
app/logical/anonymous_user.rb
app/logical/post_query_builder.rb
app/models/post_event.rb
app/models/post_flag.rb
app/models/tag.rb
app/models/user.rb
app/views/post_events/index.html.erb
app/views/post_flags/index.html.erb

Went with "EXISTS" option. I'm pretty sure it would be faster for "none" cases; "any" cases should be tested on large datasets if possible, to see if `IN` would be better instead.

Add "flagger:" and "appealer:" metatags (fixes #3142)

---

app/models/artist_commentary.rb
test/unit/artist_commentary_test.rb

Fix #3149: Artist commentaries should merge versions

---

app/assets/javascripts/notes.js
app/assets/stylesheets/common/000_vars.scss
app/assets/stylesheets/specific/notes.scss
app/controllers/notes_controller.rb
app/views/note_versions/index.html.erb
app/views/notes/index.html.erb

Fix #3205: Add ability to link to individual notes

---

app/models/post.rb

This fixes issue #3340.
Seems like that issue was caused with commit [2c56a19](https://github.com/r888888888/danbooru/commit/2c56a19dec57f50c2a86458a45882cc379cf802c) when issue #3307 was being fixed.  Not wanting to change the order back around to mess with the resolution of that issue, I moved the source metatags and the other case sensitive metatag ``newpool`` to their own function before the tags get converted to downcase.

Move case sensitive metatags to before downcase

---

app/models/post.rb

[Danbooru forum](http://danbooru.donmai.us/forum_posts/138383):
> fossilnix said:
> 
> When I uploaded post #2906639 with the newpool metatag to create a pool, the pool was created but post ID wasn't inserted into it. Trying to visit the post gave an error message until I manually added it to the pool. I forgot to save the error though...
@evazion pointed out on Discord that this issue was being caused by the post not being created yet on uploads by the time it has reached the ``apply_casesensitive_metatags`` function.  Unfortunately, I didn't test uploads on #3341 so I didn't see this error.  
For a fix, I pulled out the code adding the post to the pool in the ``apply_casesensitive_metatags`` function and readded it back to the ``apply_post_metatags`` function where it is guaranteed to …

Fix bug with newpool metatag on uploads

---

app/models/post.rb
script/fixes/050_fix_post_tagcount.rb

This is for #3365.  After speaking it over with @evazion, we realized that fixing the tagcounts client-side would take forever, and that it would be much better to do it server-side.

Added fix script to update the correct tagcount for all posts

---

app/models/dmail.rb
config/application.rb
config/danbooru_default_config.rb
config/initializers/rakismet.rb

Anything that involved sending dmails failed when akismet wasn't configured.

Fix dmail failures when akismet isn't configured.

---

app/presenters/user_presenter.rb

Fix #3438: Thumbnails on user profiles don't respect safe mode.

---

app/assets/javascripts/wiki_pages.js

Add autocomplete to wiki page versions

---

app/models/post.rb
app/models/user.rb

Fix #3468: Approval queue should not show one's own uploads or previous approvals.

---

app/models/artist_commentary_version.rb
app/models/ban.rb
app/models/mod_action.rb
app/models/note_version.rb

There were a couple of controllers missed with #3431 that this covers.

Fix missing controllers for search[id] (Ref #3430)

---

app/controllers/uploads_controller.rb

This is a potential fix for #3527.

Fix #3527: Bookmarklet timeouts for Members.

---

app/assets/javascripts/application.js
vendor/assets/javascripts/jquery-2.2.4.js

Upgrading to 1.12.4 didn't seem to break anything, so it should be okay to go to 2.2.4.

#3548: Upgrade to jquery-2.2.4

---

app/logical/daily_maintenance.rb

Fix #3518: Don't prune mod actions.

---

app/logical/danbooru_image_resizer.rb

Fixup for #3584. Adds a fallback path to use the `vipsthumbnail` command on libvips 8.4. Shelling out to `vipsthumbnail` is about 50% slower for me, but even so, it's still twice as fast as generating thumbnails with ImageMagick.

Workaround for libvips-8.4 incompatibility

---

app/views/static/site_map.html.erb

Add about:userscripts to the site map, as per [topic #15135](https://danbooru.donmai.us/forum_topics/15135).

Add about:userscripts to site map.

---

app/logical/daily_maintenance.rb
app/models/user_password_reset_nonce.rb
test/unit/daily_maintenance_test.rb
test/unit/weekly_maintenance_test.rb

Fixes a couple incorrect uses of `delete_all` / `destroy_all`, plus adds some basic tests for the daily / weekly maintenance code.

Fix rails 5.1 bugs

---

app/controllers/reports_controller.rb
app/logical/danbooru_math.rb
app/logical/reports/post_flags.rb
app/models/post_flag.rb
test/unit/post_flag_test.rb

A report to list anyone who might be targeting a user for flagging, assuming that a 50% target rate or more (with 95% confidence) is abnormal.

Post Flagger Report

---

app/logical/storage_manager.rb
app/logical/storage_manager/match.rb
app/logical/upload_error_checker.rb
app/models/post.rb

Adds a declarative-syntax storage manager.

Add matching storage manager

---

app/assets/stylesheets/common/main_layout.scss
app/assets/stylesheets/common/paginator.scss
app/assets/stylesheets/specific/posts.scss
app/assets/stylesheets/specific/z_responsive.scss
app/helpers/pagination_helper.rb
app/presenters/post_presenter.rb
app/presenters/post_set_presenters/base.rb
app/presenters/post_set_presenters/post.rb
app/views/posts/partials/common/_search.html.erb
app/views/posts/partials/index/_posts.html.erb
db/populate.rb

This eliminates the usage of float to render the post previews. Switching to flexbox affords slightly more flexibility in terms of styling and layout.

Switch to flexbox

---

public/maintenance.html.bak

The widget displays the last three tweets

Add Twitter widget (maintenance page)

---

app/javascript/src/javascripts/blacklists.js
app/views/moderator/post/queues/random.html.erb
app/views/moderator/post/queues/show.html.erb

Fixes #3821. Adds blacklists to the modqueue.

Fix #3821: Blacklist and mod queue.

---

app/controllers/tags_controller.rb
app/javascript/src/javascripts/autocomplete.js.erb
app/logical/tag_autocomplete.rb
app/models/tag_implication.rb
test/models/tag_autocomplete_test.rb
test/unit/tag_implication_test.rb

This adds, among other things, fuzzy matching and prefix matching.

Intelligent autocomplete

---

app/logical/sources/strategies/base.rb
app/logical/sources/strategies/pixiv.rb
app/logical/sources/strategies/tumblr.rb
app/logical/sources/strategies/twitter.rb
app/views/uploads/batch.html.erb
test/unit/sources/pixiv_test.rb
test/unit/sources/tumblr_test.rb
test/unit/sources/twitter_test.rb

rely on preview urls if available for gallery

---

Gemfile
Gemfile.lock
Procfile
README.md
app/controllers/saved_searches_controller.rb
app/logical/post_query_builder.rb
app/models/saved_search.rb
app/presenters/post_set_presenters/post.rb
config/danbooru_default_config.rb
db/structure.sql
script/mock_services/README.md
script/mock_services/listbooru.rb
test/functional/saved_searches_controller_test.rb
test/test_helpers/saved_search_test_helper.rb
test/unit/post_test.rb
test/unit/saved_search_test.rb
test/unit/tag_alias_test.rb

This eliminates Listbooru as a dependency and simplifies the aggregation of saved searches, using Redis as a key store.

Refactor saved searches

---

app/controllers/bulk_update_requests_controller.rb
app/helpers/forum_topics_helper.rb
app/logical/forum_updater.rb
app/logical/tag_alias_request.rb
app/logical/tag_implication_request.rb
app/models/bulk_update_request.rb
app/models/tag_alias.rb
app/models/tag_implication.rb
app/models/tag_relationship.rb
app/views/bulk_update_requests/_form.html.erb
app/views/bulk_update_requests/_listing.html.erb
app/views/bulk_update_requests/show.html.erb
app/views/forum_posts/_forum_post.html.erb
app/views/forum_topics/_secondary_links.html.erb
app/views/tag_aliases/show.html.erb
app/views/tag_implications/show.html.erb
test/unit/tag_alias_test.rb
test/unit/tag_implication_test.rb

There will be a weird period transitioning to the new system.

fixes #3824: render tag requests dynamically in the forum post

---

app/logical/alias_and_implication_importer.rb
app/logical/moderator/tag_batch_change.rb
app/models/bulk_update_request.rb
app/models/tag_relationship.rb
app/views/bulk_update_requests/show.html.erb
test/test_helpers/saved_search_test_helper.rb
test/unit/alias_and_implication_importer_test.rb
test/unit/bulk_update_request_test.rb
test/unit/moderator/tag_batch_change_test.rb
test/unit/tag_alias_test.rb
test/unit/tag_implication_test.rb

This sets up groundwork for tiered approval of tag change requests.

add post count estimates for bulk update requests

---

app/javascript/src/javascripts/posts.js.erb

This should make videos automatically scale on the mobile view.

Add video support to resize_image_to_window

---

config/webpacker.yml

Set Webpack Compile Output to true during development.

---

app/logical/sources/strategies/twitter.rb

Fixes #4047. I went with the negative lookbehind assertion as there might be some tags that use the kanji portion of the regex as part of the other names, in which case it would end up as a translated tag miss.

Add normalization for Twitter hashtags

---

app/javascript/packs/application.js

Fix the error from missing jQuery-ui effects

---

app/javascript/src/styles/common/dtext.scss
app/logical/d_text.rb

Fixes #4205. It also checks for existing artist pages, similar to it does for wiki pages.

Have artist wiki links go to artist page

---

app/logical/sources/strategies/twitter.rb

It was mentioned on issue #4047 but was forgotten to be included

Add additional Twitter hashtag

---

app/presenters/post_set_presenters/base.rb

Remove posts not shown for blank message check

---

app/javascript/src/javascripts/autocomplete.js.erb
app/logical/danbooru/has_bit_flags.rb
app/logical/post_query_builder.rb
app/models/tag.rb

Also fixed a bug in the bit flags module.

Add search for embedded notes status

---

app/logical/pawoo_api_client.rb
app/logical/sources/strategies/pawoo.rb

Fix Pawoo source

---

app/views/artist_commentary_versions/_listing.html.erb

Fix searching artist commentaries by post ID

---

app/javascript/src/javascripts/blacklists.js

Only count unique post IDs for blacklist menu

---

app/models/bulk_update_request.rb
app/views/bulk_update_requests/_search.html.erb
db/migrate/20200318224633_drop_title_from_bulk_update_requests.rb
db/structure.sql

Fixes #4157. Numbers 3. and 4. were no longer an issue, so this only fixes 1. and 2. The title is longer used anywhere else except on the creation of a forum topic, so there was no reason to keep this column around, therefore it was removed and replaced with an attribute accessor.

Various BUR fixes

---

app/logical/sources/strategies/twitter.rb

Allow video thumbnails as direct Twitter images

---

app/views/artist_commentary_versions/_listing.html.erb

Fix artist commentary version view

---

app/logical/sources/strategies/twitter.rb
test/unit/sources/twitter_test.rb

Account for additional Twitter video image links

---

app/javascript/src/javascripts/notes.js
app/javascript/src/styles/base/040_colors.css

Fixes #4362 and fixes #4363.
Besides those, it also fixes an issue with the movable status on new notes. Now it just removes that status regardless upon a note being saved.

Various note fixes

---

app/javascript/src/javascripts/notes.js
app/logical/note_sanitizer.rb

Add additional settable attributes for embedded notes alignment

---

app/javascript/src/styles/specific/posts.scss

Fix relationship preview alt text overflowing

---

app/logical/sources/strategies/art_station.rb

Fixes issue #4328.
Also adds in support for preview URLs which was missing.

Fixes issues with Artstation source strategy

---

app/logical/sources/strategies/weibo.rb
test/unit/sources/weibo_test.rb

Tested against all 1793 weibo sources on live site, all succeeded.

Weibo: add source normalization

---

app/logical/sources/strategies/twitter.rb

Twitter: don't get api without a status id

---

app/policies/forum_post_policy.rb

Prevent creators from voting on their own BURs

---

app/controllers/static_controller.rb
app/javascript/src/styles/specific/privacy_policy.scss
app/views/static/privacy_policy.html.erb
app/views/static/site_map.html.erb
app/views/static/terms_of_service.html.erb
config/danbooru_default_config.rb
config/routes.rb
test/functional/static_controller_test.rb

Draft for a new privacy policy. Related to #4415.

Add new privacy policy

---

app/logical/sources/strategies/nijie.rb
test/unit/sources/nijie_test.rb

Nijie: Add doujin support

---

app/logical/post_query_builder.rb

Return empty search for ordfav of fake user

---

app/javascript/src/javascripts/notes.js

Fixes #4578. It was only the nudge event that had issues, the resize event still works fine. The commit message has more details on the issue.

Fix the note nudge on rotated notes

---

app/presenters/tag_set_presenter.rb

Fix page title in case of no copyright tag

---

app/views/users/_statistics.html.erb

It's kind of old and misleading

Change "Inviter" to "Promoter"

---

app/logical/artist_finder.rb

Forgot to add this when I added the strategy.

Artist finder: add skeb.jp root to blacklist

---

app/models/tag_implication.rb

Reported in https://danbooru.donmai.us/forum_topics/18299

Tag implications: fix typo in validate error

---

app/logical/sources/strategies/nico_seiga.rb
test/unit/sources/nico_seiga_test.rb

References: 
* https://discord.com/channels/310432830138089472/310846683376517121/828954750007246988
* https://danbooru.donmai.us/posts/4282355

Nicoseiga: auto-add spoiler tags to commentary

---

app/logical/sources/strategies/skeb.rb

They changed something in their private api and broke it. Now it's even worse to unfold!

Skeb: fix broken strategy

---

app/logical/sources/strategies.rb
app/logical/sources/strategies/lofter.rb
test/unit/sources/lofter_test.rb

Cuz replacing posts manually when users upload samples is a pain in the ass, since Lofter blocks the right click menu.

Add Lofter support

---

app/logical/sources/strategies/lofter.rb
test/unit/sources/lofter_test.rb

There was a second type of html theme that I didn't find when testing. This adds support for that too.

Lofter: fix strategy for additional type of html theme

---

app/views/bulk_update_requests/_secondary_links.html.erb

BUR: add link to wiki help page in navbar

---

app/components/post_preview_component/post_preview_component.scss

Resolves #4460
Pretty straightforward, @evazion literally solved it in the issue description.
I just messed up a lot of times, so ignore the excessive commit messages please.

Mobile uncropped thumbnails: Fix sizing and overflow

---

app/models/post.rb

Fixes #4607. 
Edit: just saw a discord discussion that raised concerns about performance. If that's a problem then this can be rejected but the issue should be closed as well.

Add post disapprovals to available includes

---

app/controllers/post_appeals_controller.rb
app/policies/post_appeal_policy.rb
app/views/post_appeals/_reasons.html.erb
app/views/post_appeals/edit.html.erb

make appeals editable

---

app/views/favorite_groups/_add_to_favgroup_dialog.html.erb

Favgroups: only add shortcuts for first 10 groups

---

app/models/forum_post.rb
test/functional/forum_posts_controller_test.rb

Forum link search: also include BURs

---

app/views/users/_statistics.html.erb

Quick utility links for mods, because the ol' copy-paste method got old pretty quickly.

Add utility links to user events from user page

---

app/views/post_disapprovals/index.html.erb

Currently broken because of a wrong parameter.
https://danbooru.donmai.us/post_disapprovals

Fix link to rest of user's post disapprovals

---

app/logical/bulk_update_request_processor.rb
test/unit/bulk_update_request_test.rb

Reference: https://danbooru.donmai.us/forum_topics/19097

Tag nuke: remove implications to a tag before nuking it

---

README.md

As discussed here: https://github.com/danbooru/danbooru/issues/4198

Reflect that SQS is not needed anymore for IQDB

---

app/logical/discord_slash_command/post_embed.rb

Hopefully. Also censor guro/bestiality because Discord ToS. Fixes #4836

Hide posts not visible to anonymous users from Discord slash commands

---

app/models/post.rb

Ref: [topic #19497](https://danbooru.donmai.us/forum_topics/19497)

Posts: stop autotagging long_image

---

app/logical/sources/strategies/lofter.rb

* Fix some tags not being parsed in a specific css style
* Fix some tags being parsed wrong in another specific css style

Lofter: fix tag extraction

---

app/logical/sources/strategies/lofter.rb

Ref: https://danbooru.donmai.us/forum_topics/17912?page=9#forum_post_198970

Lofter: Add support for additional theme

---

app/logical/sources/strategies/foundation.rb
test/unit/sources/foundation_test.rb

Didn't even know they supported mp4s.

Foundation: add support for videos

---

app/logical/sources/strategies/skeb.rb
test/unit/sources/skeb_test.rb

* Fix fetching of videos
* Fix fetching of original commentary
* Fix images being returned out of order in bookmarklet
Fixes #4955.

Skeb: fix several issues with the strategy

---

app/logical/upload_limit.rb
config/danbooru_default_config.rb

For issue #4963. Simple enough, but I've never worked in rails before, so please make sure I'm not making any beginner's mistakes here!
I opted to set the constants rather than replace them. A few places reference `UploadLimit::MAXIMUM_POINTS` and I didn't want to change that behind anyone's back.

Add configurable upload limits

---

app/logical/sources/strategies/lofter.rb
test/unit/sources/lofter_test.rb

Fix lofter not working with iqdb

---

app/javascript/src/javascripts/post_mode_menu.js
app/javascript/src/styles/specific/post_mode_menu.scss

Fixes the post-score link triggering the mode menu action as well as
all three score links getting the blue border on hover.

post_mode_menu: update preview link selector

---

INSTALL.debian

See https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

Convert GIT paths to https

---

test/unit/sources/nijie_test.rb

It will just always assert true at present.

fix broken assertion in nijie test

---

app/models/post.rb

Posts: don't try to ban/unban a post that is already banned/unbanned

---

app/logical/source/url/anifty.rb
app/logical/source/url/art_station.rb
app/logical/source/url/booth.rb
app/logical/source/url/deviant_art.rb
app/logical/source/url/fanbox.rb
app/logical/source/url/fantia.rb
app/logical/source/url/fc2.rb
app/logical/source/url/foundation.rb
app/logical/source/url/hentai_foundry.rb
app/logical/source/url/instagram.rb
app/logical/source/url/lofter.rb
app/logical/source/url/mastodon.rb
app/logical/source/url/moebooru.rb
app/logical/source/url/newgrounds.rb
app/logical/source/url/nico_seiga.rb
app/logical/source/url/nijie.rb
app/logical/source/url/null.rb
app/logical/source/url/pixiv.rb
app/logical/source/url/pixiv_sketch.rb
app/logical/source/url/plurk.rb
app/logical/source/url/reddit.rb
app/logical/source/url/skeb.rb
app/logical/source/url/tinami.rb
app/logical/source/url/tumblr.rb
app/logical/source/url/twit_pic.rb
app/logical/source/url/twitter.rb
app/logical/source/url/weibo.rb

I was starting to look into sorbet, and this syntax makes it segfault. It's also reported as a smell by Rubocop, so might as well fix it.

Sources: do not use an empty else in case blocks

---

app/logical/source/extractor/deviant_art.rb
test/test_helpers/source_test_helper.rb
test/unit/sources/deviant_art_test.rb

Unfortunately does not do anything for #4616, but that should in theory apply only to old posts so it's not too bad.

Fix deviantart strategy to get biggest available size

---

app/logical/source/extractor/deviant_art.rb
test/unit/sources/deviant_art_test.rb

Of course the case that broke was the one that wasn't in the tests...

Deviantart: fix regression in 3a0a32b98adcb6c110180d3ad5f530a9ad3743e4

---

app/logical/source/url/nico_seiga.rb

Nicoseiga: normalize oekaki links

---

app/views/layouts/default.html.erb

Revert 1720246cb9534bb67c06b700b8bf45843dcd1891 and f668cfdbac3344e5009888fab44ba8d8db008a83
If I understand correctly we're not using the payment processor that wanted these removed.

Add back social icons to site footer.

---

app/logical/session_loader.rb

Fix typo in session_loader.rb

---

app/logical/source/extractor/twitter.rb
app/logical/source/url/twitter.rb
test/test_helpers/source_test_helper.rb
test/unit/sources/twitter_test.rb

Also add partial support for profile banner images.
Leaving it for a few days as a pull to double check it when I'm fresh.

Twitter: rewrite tests

---

docker-compose.yaml

This should make local development a bit less of a pain in the ass.

Docker compose: add comments and use templating

---

app/logical/bulk_update_request_processor.rb
test/unit/bulk_update_request_test.rb

Tags: remove aliases when deprecating a tag

---

app/logical/mastodon_api_client.rb
app/logical/source/extractor/art_station.rb
app/logical/source/extractor/mastodon.rb
test/unit/sources/art_station_test.rb
test/unit/sources/fanbox_test.rb
test/unit/sources/hentai_foundry_test.rb
test/unit/sources/mastodon_test.rb
test/unit/sources/moebooru_test.rb
test/unit/sources/newgrounds_test.rb
test/unit/sources/pixiv_sketch_test.rb
test/unit/sources/plurk_test.rb
test/unit/sources/stash_test.rb

Gonna open this pull to motivate myself to finish rewriting all the source tests. I'll merge once I'm done with them all.

Source tests rewrite

---

test/functional/application_controller_test.rb

tests: fix typo in application_controller_test.rb

---

app/views/counts/posts.html.erb

Make it easier to compare counts for different searches.

post counts: add search field.

---

app/logical/source/extractor.rb
app/logical/source/extractor/reddit.rb
app/logical/source/url/reddit.rb
test/unit/sources/reddit_test.rb

Fixes #4786, I guess. People are gonna upload samples if we don't support it anyway, so might as well get the full size if we must. This also automatically resolves crossposts so we get the original link.

Add reddit support

---

app/logical/tag_mover.rb

Fix typo in tag_mover.rb

---

app/javascript/src/styles/specific/posts.scss

Leftover from 2df1db187af5eedfb8883a71aa52e5c9ef98f23e

css: remove styling for blob emotes

---

app/jobs/application_job.rb

jobs: fix typo in application_job.rb

---

app/logical/note_sanitizer.rb

previous PR was closed by accident

fix border-top-left-radius in note_sanitizer

---

app/logical/source/url/misskey.rb

post #7085860 was not auto-tagged with `bad_link`

misskey: recognize new misskey.io cdn host

---

app/logical/source/extractor/bilibili.rb
test/unit/sources/bilibili_test.rb

Hashtags, @-mentions, links other than `bilibili.com/video/`, emoji alt text

bilibili: better DText formatting

---

app/logical/source/extractor/lofter.rb
app/logical/source/url/lofter.rb
test/unit/sources/lofter_test.rb

https://danbooru.donmai.us/artist_commentary_versions?search[post_tags_match]=source%3A*lofter*&search[updater_id]=499533

lofter: extract artist display name and post title

---

app/logical/source/extractor/fantia.rb
test/unit/sources/fantia_test.rb

fantia: handle blog-album articles

---

app/logical/source/extractor/bluesky.rb
test/unit/sources/bluesky_test.rb

I sure do love unstable APIs that evolve every second with no documentation changes.
Also, add hashtags - for some reason they are here, but you can do nothing with them (can't click on web ui, can't search for them - a design as well-thoroughly thought as one may expect from 321958234th twitter clone)

bluesky: parse another kind of api response

---

app/views/media_assets/show.html.erb

Fixes https://github.com/danbooru/danbooru/issues/5609

Fix incorrect rendering of false exif values in /media_assets/id page

---

app/models/favorite_group.rb

Addresses <https://github.com/danbooru/danbooru/pull/5023#issuecomment-1054918022>. Sorry for the delay.

favorite_groups: add id fallback for updated_at order

---

app/javascript/src/styles/common/dtext.scss

Fix [spoiler] tags not hiding embedded images

---

config/danbooru_default_config.rb

See https://stackoverflow.com/questions/77855137

Recommend using `rails secret` instead of `rake secret`

---

app/logical/source/extractor/skeb.rb
test/unit/sources/skeb_test.rb

This solution does not involve tinkering with cookies, therefore also making https://github.com/danbooru/danbooru/pull/5644#issuecomment-1958933920 irrelevant.
An alternative would be getting the cookies the new way (https://github.com/danbooru/danbooru/issues/5773#issuecomment-2188898418).

#5773: Fix skeb extractor

---

app/logical/source/extractor/bluesky.rb
test/unit/sources/bluesky_test.rb

1. Add links to hashtags on upload page and in parsed artist commentary.
Fixes #5791
2. Adds upload support for posts with video embeds.
Fixes #5814

bluesky extractor tweaks

---

app/controllers/media_assets_controller.rb
app/views/media_assets/show.html.erb
test/functional/media_assets_controller_test.rb

Media Assets: link to associated uploads in metadata

---

app/logical/sandbox.rb

chore: update sandbox.rb

---

app/logical/source/extractor/odaibako.rb
app/logical/source/url.rb
app/logical/source/url/null.rb
app/logical/source/url/odaibako.rb
test/unit/sources/odaibako_test.rb

A free art requests site. Used to allow only sending requests, but now also lets artists to respond with attached images.

sources: add odaibako extractor

---

app/logical/source/extractor/bluesky.rb
app/models/site_credential.rb
config/danbooru_default_config.rb
test/unit/sources/bluesky_test.rb

BlueSky: refactor to use loginless api

---

app/logical/source/extractor/dc_inside.rb
app/logical/source/url.rb
app/logical/source/url/dc_inside.rb
test/unit/sources/dc_inside_test.rb

A Korean board, somewhat similar to Arca.live.

sources: add DC Inside extractor

---

app/logical/source/extractor/bluesky.rb
test/unit/sources/bluesky_test.rb

Fixes #5971, it was a text encoding issue

Fix #5971: Allow unicode in bluesky alt text

---

app/logical/bulk_update_request_processor.rb
test/unit/bulk_update_request_test.rb

BURs: Validate and optimize pool nukes

---

app/logical/source/extractor/xiaohongshu.rb
app/models/site_credential.rb
config/danbooru_default_config.rb

I hope you like giving them your phone number to get these.
From what I can tell they at least don't expire very quickly (~1week and counting)

Xiohongshu: Use all credentials
