app/views/posts/show.html.erb

Currently `og:image` is a relative url, it should be canonical according to spec http://ogp.me/ and I have set it to be the same as `twitter:image:src`.
Discovered this problem while working on my own project which use opengraph data for link preview.

make og:image canonical according to spec

---

app/views/posts/index.atom.erb

Right now, Atom feeds have 'Danbooru' set as their name, forcing the user to manually rename them.

Rename Atom feeds to include tags in their name

---

app/assets/javascripts/notes.js

In addition to preventing the event when starting translation mode, prevent it when stopping translation mode.
Clicking the "add notes" (#translate) link to stop translation mode currently triggers the link and scrolls the page back to the top.

Translate link toggle fix

---

app/views/static/site_map.html.erb

Fix a typo causing the unordered list for the reports section to display incorrectly.

Site map reports list fix

---

INSTALL.debian

The script will now copy the database configuration files to /var/www/danbooru2/shared/config only after chowning the parent of the target directory.

Fix install script permission deny when copying config files

---

app/models/user.rb
app/views/users/search.html.erb
db/migrate/20160917180923_add_index_to_users_bit_prefs.rb

See #2644 for details.
Array index failed to work with `not (column && ARRAY[])` syntax, so excluded bits are searched almost the same way as before, except omitting the unnecessary bitstring conversion - turns out, postgres can `&` bigints just fine. 
It's possible to change sql function to create array with negative integers for unset bits and positive for set bits. It would allow complete index support, but storage requirements skyrocket and it needs to know max bit count, so I deemed it wasn't worth it.

Index and form for bit preferences

---

app/models/post.rb
app/models/tag.rb

This should take care of #2664. 
@r888888888 requesting code review. I don't think it would break anything, it simply extracts `source:"..."` verbatim from tag string before splitting the rest on spaces. I have two concerns about other code, though:
* What's the purpose of `.gsub(/[%,]/, "")` in `Tag.scan_tags`? I put source extraction before it, since I figured that source _can_ contain commas and percents.
* `source:none` will set post source to nil. `source:""` and `source:` will set it to empty string. Should something be done about that?

Allow quoted source: metatag, allow source: metatag when editing posts

---

app/logical/sources/strategies/pixiv.rb
app/models/post.rb
test/unit/post_test.rb

* Makes `illust_id_from_url` a public class method instead of a protected instance method so that `Post#parse_pixiv_id` can use it.
* Also make `illust_id_from_url` swallow the exception that `illust_id_from_url!` throws so that `parse_pixiv_id` can use it.

Refactor Post#parse_pixiv_id to use illust_id_from_url (fix #2695)

---

app/models/user.rb
config/danbooru_default_config.rb

The default config has `start_as_gold?` and `start_as_contributor?` methods but they don't actually do anything. `git log -G start_as` indicates they never have done anything.
This PR removes those methods and replaces them with a more general `customize_new_user` method for setting the starting user level, permissions and defaults for any other settings.

Make starting user level and default settings configurable.

---

app/models/user.rb

The first user created is automatically made an admin, but that user doesn't start with approval permission. Just giving yourself approval permission doesn't seem to work either (not sure why). I ended up having to make another admin and using that account to give approval permission to my first admin.

Give full permissions to the starting admin.

---

app/models/artist.rb
test/fixtures/vcr_cassettes/artist-test/21e234db9c1ba2648f3b04b47dd84349137691cd.yml
test/fixtures/vcr_cassettes/artist-test/455987fd06411784f89f9eff6832807fe8bab9b4.yml
test/fixtures/vcr_cassettes/artist-test/72b0ef658bb36cb909776b4f4d2c3c1cfd4eaacc.yml
test/fixtures/vcr_cassettes/artist-test/7467395b781080266d00137810930d582aec0648.yml
test/fixtures/vcr_cassettes/artist-test/7e541859685456b205ee26f92edb2311b776f722.yml
test/fixtures/vcr_cassettes/artist-test/b48b1231489a68e43002dc1f07c0a29e28c4625b.yml
test/fixtures/vcr_cassettes/artist-test/e49e6da7c554f89861b8d8137c549e01ef2fddf1.yml
test/fixtures/vcr_cassettes/artist-test/e806ab9d47b5e3ef6d81d61268e2121c5c7b6356.yml
test/unit/artist_test.rb

This partially addresses issue #2696. I added some bonus test cases for the artist finder to make sure this didn't cause any regressions. Run them with `ruby -I lib:test test/unit/artist_test.rb -n "/twitter artists/"` to avoid running the whole test suite.

Artist finder: Don't return bogus results for non-matching twitter artists

---

app/controllers/comments_controller.rb
app/models/comment.rb
app/models/post.rb
test/functional/comments_controller_test.rb
test/functional/posts_controller_test.rb
test/unit/comment_test.rb
test/unit/post_test.rb

Fixes these issues:
> C. Posts
> "last_noted_at" is settable
>
> D. Comments
> "do_not_bump", "is_deleted", "post_id" are settable
Also fixes an issue with being able to create comments on nonexistent post ids.

Partial fixes for #2704

---

app/models/post.rb
test/unit/post_test.rb

vote.destroy sets the score in the database but not on the in-memory post. So just reload the post from the db to get the updated score, don't duplicate the logic of setting it again.

Post#unvote!: Return correct score (fixes #2709).

---

app/controllers/artist_commentaries_controller.rb
app/controllers/artists_controller.rb
app/controllers/notes_controller.rb
app/controllers/pools_controller.rb
app/controllers/posts_controller.rb
app/controllers/wiki_pages_controller.rb
app/models/artist.rb
app/models/artist_commentary.rb
app/models/note.rb
app/models/pool.rb
app/models/post.rb
app/models/wiki_page.rb
test/factories/artist_commentary.rb
test/functional/artist_commentaries_controller_test.rb
test/functional/artists_controller_test.rb
test/functional/notes_controller_test.rb
test/functional/pools_controller_test.rb
test/functional/posts_controller_test.rb
test/functional/wiki_pages_controller_test.rb

80895ef: adds test cases.
c46b31a: applies the fix. I added checks to both the controllers and models for completeness. The model checks aren't exercised though, the controllers prevent anything from getting that far.

Prevent reverting to foreign versions (fixes #2711).

---

app/controllers/tag_aliases_controller.rb
app/controllers/tag_implications_controller.rb
app/models/tag_alias.rb
app/models/tag_implication.rb
test/functional/tag_aliases_controller_test.rb
test/functional/tag_implications_controller_test.rb
test/unit/tag_alias_test.rb
test/unit/tag_implication_test.rb

101771a: adds tests.
789dede: validates status and forum_topic_id.
7e3284c: prevents assignment of tag alias/implication status.

Fix mass assignment vuln to tag alias/implication status (partial fix for #2704).

---

app/controllers/artist_commentaries_controller.rb
app/controllers/bans_controller.rb
app/controllers/delayed_jobs_controller.rb
app/controllers/ip_bans_controller.rb
app/controllers/mod_actions_controller.rb
app/controllers/note_versions_controller.rb
app/controllers/post_appeals_controller.rb
app/controllers/post_events_controller.rb
app/controllers/post_flags_controller.rb
app/controllers/saved_searches_controller.rb
app/controllers/super_voters_controller.rb
config/initializers/active_record_api_extensions.rb

Don't see any reason /artist_commentaries shouldn't be public.
Also make /bans.json and /mod_actions.json accessible in the API.
EDIT: Added missing JSON/XML responses for a few more things (super voters, saved searches, posts events, and ip bans), and made a few more pages that were blocked for logged out users public (note versions, posts appeals, post flags, post events, and super voters).

Fix missing JSON/XML templates, make more pages public (#2721)

---

app/models/tag_alias.rb
app/models/tag_implication.rb
test/functional/tag_implication_requests_controller_test.rb

Creates a mod action any time an alias or implication is changed. This includes creations, edits to pending aliases/implications, deletions, and approvals. Also it logs each status change from pending -> queued -> processing -> approved.
Also changes calls from `update_column` to `update` so that the `create_mod_action` callback will run at every point in the lifecycle. 
Note: this breaks a test case in `test/unit/tag_alias_correction_test.rb`. I think it's because the change to `update` causes the `after_save :clear_all_cache` hook on tag aliases to clear the cache more often, which the test doesn't expect.

Log tag aliases+implications

---

app/models/post.rb
test/unit/post_test.rb

c01e03b: validate post ratings so you can't set invalid ratings via the API.
0006b76: 	fix rating locks so they're obeyed in all cases.
See commit messages for details.
Note that 0006b76 makes changing the rating of a rating-locked post an error. Another option would be to make builders silently ignore rating locks. I'm not sure which behavior would be best.

Validate post ratings and fix ratings locks

---

app/controllers/notes_controller.rb
test/functional/notes_controller_test.rb

Prevents moving notes between posts. Note that if you attempt to set `post_id` the API still returns `200 OK`, but the attempt is silently ignored. cf. #1582.

Fix vuln allowing users to move notes between posts.

---

app/models/post.rb
test/unit/post_test.rb

Fixes a regression introduced in #2727: rating locks were ignored when adding the rating: metatag. This was because rating lock enforcement was moved to a validation callback, but processing the rating: metatag happened after validation in a `before_save` callback.
Fixing this also fixed a couple small bugs with the source: metatag: pixiv ids weren't set when using source:, and whitespace wasn't trimmed.
See commit messages for details.
EDIT: Github shows a weird commit ordering, read them in this order:
* 0b7cd71
* 899f008 
* 07921d2 
* 8b46726
* 52491f4

Fix metatag editing so that rating:s obeys rate locks, source:blah updates pixiv id

---

app/logical/downloads/rewrite_strategies/pixiv.rb
app/logical/sources/site.rb
app/logical/sources/strategies/pixiv_whitecube.rb

Make the bookmarklet work for URLs like this:
* http://www.pixiv.net/whitecube/user/607414/illust/59510800
* http://www.pixiv.net/whitecube/user/772090/illust/59595705 (ugoira)

Fix upload bookmarklet for Pixiv whitecube URLs.

---

app/models/post.rb
test/factories/user.rb
test/unit/post_test.rb

Enables these metatags to be added to posts:
* `locked:rating` / `-locked:rating`
* `locked:notes` / `-locked:notes`
* `locked:status` / `-locked:status`
* `upvote:yes` / `downvote:yes`
`locked:` is for #1716.
`upvote:` / `downvote:` are for completeness, since we already have `fav:`. They're a little strange in that you can say `upvote:whatever` and still upvote the post, but that's how `fav:` works too.

Add locked:{rating,status,notes} + upvote:/downvote: metatags

---

app/controllers/bulk_update_requests_controller.rb
app/controllers/tag_aliases_controller.rb
app/controllers/tag_implications_controller.rb
app/logical/alias_and_implication_importer.rb
app/models/artist.rb
app/models/bulk_update_request.rb
app/models/tag_alias.rb
app/models/tag_implication.rb
app/models/user.rb
test/factories/tag_alias.rb
test/factories/tag_implication.rb
test/unit/artist_test.rb
test/unit/bulk_update_request_test.rb
test/unit/tag_alias_test.rb

Several bugfixes:
* Attribute the "tag alias has conflicting wiki pages" message to the alias approver, not to the first admin.
* Merge the conflicting wiki pages message and the alias approval message into one forum post.
* Fix a bug with approvers not being set on aliases/implications in bulk update requests.
* Fix a bug with the approver not being set on the banned_artist implication when banning an artist.

Fix "conflicting wikis" message; fix alias/implication approvers in BURs (#2715)

---

app/controllers/notes_controller.rb

Bug: creating a note then saving it doesn't remove the red border indicating it's unsaved.
Broken by 8df1496 / PR #2729.
Ref: #2747, http://danbooru.donmai.us/forum_topics/13348

Fix notes appearing unsaved after saving them (fix #2747)

---

app/models/post.rb
test/unit/post_test.rb

Make e.g. `hatsune_miku_(cosplay)` automatically add `hatsune_miku` and `cosplay`.
Perform autotagging after aliasing so that `*_(cosplay)` aliases (e.g. `hestia_(dungeon)_(cosplay)` -> `hestia_(danmachi)_(cosplay)`) can take effect first, just in case that matters (honestly, it probably doesn't, but whatever).
ref: http://danbooru.donmai.us/forum_topics/13367

Autotag character_(cosplay) -> character, cosplay.

---

app/controllers/maintenance/user/dmail_filters_controller.rb
app/models/dmail_filter.rb
test/functional/maintenance/user/dmail_filters_controller_test.rb
test/unit/dmail_test.rb

47f663e: Don't filter dmails from moderators (fix #2757).
a16b91e: 	Fix exploit allowing dmail filters to be set on other users.
Exploit:
curl \
-u $USERNAME:$API_KEY \
-X PUT "http://danbooru.donmai.us/maintenance/user/dmail_filter.json?dmail_id=1" \
-d "dmail_filter[words]=a&dmail_filter[user_id]=2"
...where dmail_id is any dmail you own (doesn't matter which) and user_id is the victim. They can't already have a dmail filter. This can be exploited to hide dmails sent to the victim without their knowledge.

Don't filter dmails from moderators; fix dmail filter exploit.

---

app/logical/downloads/file.rb

Discussed in http://danbooru.donmai.us/forum_topics/13411. Currently we rewrite certain image board sources to `Image board` on upload. But that's counterproductive, even if the source goes dead it can be useful for tracking things down. It should be retained.

Don't clobber image board sources.

---

app/views/favorite_group_orders/edit.html.erb
app/views/pool_orders/edit.html.erb

Don't display hidden posts on pool/favgroups order pages (fix #2762).

---

app/controllers/uploads_controller.rb
app/views/post_flags/_new.html.erb
app/views/uploads/new.html.erb
config/danbooru_default_config.rb

Does #2767: pulls the upload/flag notices from wiki pages so that adjusting them doesn't require code changes. Also removes the bookmarklet notice, I think that should go in the wiki so it can be edited too.

Pull upload/flag notices from wiki pages.

---

app/helpers/forum_topics_helper.rb
app/models/forum_topic.rb
app/views/forum_topics/_form.html.erb

* Replaces the blank option in the level dropdown with a `Public` option.
* Refactors stuff so that the allowed levels are defined in one place. Edit `MIN_LEVELS` to change the allowed levels.

Fix #2772: Topics set as mod+ can't be reverted to public ones.

---

app/models/post.rb

Normalize http://yande.re sources to either
https://yande.re/post/show/1234
or
https://yande.re/post?tags=md5:7289b37841079917485c8403aeebc28d
for the sidebar. See [this bigquery](https://bigquery.cloud.google.com:443/savedquery/446593546541:825b3514deef49c0b5dd2e2e227f1c13) for a test of these regexes against the database; everything is handled except for a few hundred posts from dl.dropbox.com.

Normalize yande.re sources from image URL -> html page URL.

---

config/application.rb
test/functional/comment_votes_controller_test.rb
test/unit/comment_test.rb
test/unit/user_test.rb

Restricting users from upvoting their own comments broke some tests. Switch these tests to downvoting instead.

Fix failures in commenting tests. 

---

app/assets/javascripts/notes.js
app/views/notes/_note.html.erb

Problem: Create a note with body `<i>foo&shy;bar`. Save it, refresh the page, and edit the note. Now you see `<i>foobar</i>` in the edit box even though that is not the actual note body.
The issue is the sanitized body is used instead of the raw body for the edit box. This prevents translators from being able to see and edit the unsanitized note text. So this patch just switches to using the raw note instead.

Use raw note body instead of sanitized body for note edit box.

---

app/assets/javascripts/uploads.js

I'm still getting issue #1375 (upload preview image is displayed at full size) when uploading http://i2.pixiv.net/img-original/img/2016/06/02/23/45/45/57194045_p0.jpg with the bookmarklet.
The issue seems to be that the resizer attempts to poll the image's height before resizing it, but that fails if the image takes >2 seconds to download. This just waits until the image is fully downloaded before resizing it instead.

Fix upload preview image displayed at full size (fixes #1375, #2471)

---

app/assets/javascripts/uploads.js

From http://danbooru.donmai.us/forum_topics/9127?page=143#forum_post_124074: when uploading, if you hit the enter key in the tag edit box multiple times it will cause a double post.
The submit button is disabled after first press to prevent this, but the enter key isn't. This disables the enter key after first press as well.

Prevent double uploading when hitting enter key in tag edit box more than once.

---

app/assets/javascripts/blacklists.js

As reported in [forum #124005](http://danbooru.donmai.us/forum_topics/9127?page=143#forum_post_124005): `video_with_sound` posts still play audio even when they're blacklisted.
This patch disables playback when a post is blacklisted. If blacklists are toggled off then playback is reenabled.

Prevent video_with_sound posts from autoplaying when blacklisted.

---

app/assets/javascripts/application.js
app/views/posts/partials/show/_ugoira_original.html.erb
app/views/reports/contributors.html.erb
app/views/reports/janitor_trials.html.erb
app/views/reports/user_promotions.html.erb

From http://danbooru.donmai.us/forum_topics/9127?page=144#forum_post_124118: The ugoira player is broken on safebooru. Example: http://safebooru.donmai.us/posts/2568626?original=1. The cause is `ugoira_player.js` not loading due to this error:
Asset filtered out and will not be served: add
`Rails.application.config.assets.precompile += %w( ugoira_player.js)`
to `config/initializers/assets.rb` and restart your server
This PR instead moves it into application.js so it's minified with everything else. Also it fixes a related stupidtable.js error on these pages:
* http://safebooru.donmai.us/reports/user_promotions
* http://safebooru.donmai.us/reports/contributors
* http://safebooru.donmai.us/reports/janitor_trials

Fix broken ugoira player on safebooru.

---

app/models/pool_archive.rb

`/users/1` and `/static/site_map` throw this exception:
ActiveRecord::AdapterNotSpecified exception raised
'archive_development' database is not configured. Available: ["development", "test", "production", "ro_development", "ro_test", "ro_production"]
app/models/pool_archive.rb:6:in `<class:PoolArchive>'
app/models/pool_archive.rb:1:in `<top (required)>'
app/views/static/site_map.html.erb:56:in `_app_views_static_site_map_html_erb__2188261936972743716_31997600'
because I don't have an `archive_development` database on my dev instance. This makes it optional.

Fix "'archive_development' database is not configured." exception.

---

app/assets/javascripts/notes.js
app/assets/stylesheets/common/000_vars.css.scss
app/assets/stylesheets/specific/comments.css.scss
app/controllers/comments_controller.rb
app/models/comment.rb
app/models/pool_archive.rb
app/views/comments/partials/index/_threshold.html.erb
config/routes.rb

* `/comments.json`: accept `id` param and allow `id` and `post_id` to take comma-delimited lists of ids (cf. #1345, #2455).
* `/comments/1.json`: return `updater_name` too.
* Other minor cleanups, should be self-explanatory.

Various minor comment code cleanups

---

app/models/post_appeal.rb

Fix this exception:
undefined method `is_deleted?' for nil:NilClass
app/models/post_appeal.rb:72:in `resolved?'
app/views/post_appeals/index.html.erb:23:in `block in _app_views_post_appeals_index_html_erb__2678117644687662585_70170674603580'
app/views/post_appeals/index.html.erb:17:in `_app_views_post_appeals_index_html_erb__2678117644687662585_70170674603580'
app/controllers/post_appeals_controller.rb:13:in `index'
that occurs on these pages:
* http://danbooru.donmai.us/post_appeals?limit=1&page=a2928
* http://danbooru.donmai.us/post_appeals?limit=1&page=a2929
* http://danbooru.donmai.us/post_appeals?limit=1&page=a2930
* http://danbooru.donmai.us/post_appeals?limit=1&page=a2931
* http://danbooru.donmai.us/post_appeals?limit=1&page=a2934
* …

Fix `undefined method `is_deleted?' for nil` on /post_appeals.

---

app/models/user.rb

ref: http://danbooru.donmai.us/forum_topics/9127?page=148#forum_post_124769
Bug:
Platinum users get this error when commenting:
No route matches {:action=>"show", :controller=>"posts", :id=>nil} missing required keys: [:id]
Fix:
The issue was that `CurrentUser.role` was nil for Platinum users, which caused `Comment.create(create_params, :as => CurrentUser.role)` to silently ignore the create_params because the nil role wasn't in the attr_accessible whitelist.
Despite this, things worked accidentally for other models because they had `attr_accessible ..., :as => [:default]` in their whitelists, where the comment model didn't.

Fix bug preventing Platinum users from commenting.

---

app/assets/javascripts/autocomplete.js
app/helpers/application_helper.rb
app/views/comments/_form.html.erb
app/views/dtext/_form.html.erb
app/views/forum_posts/partials/edit/_form.html.erb
app/views/forum_posts/partials/new/_form.html.erb
app/views/forum_topics/_form.html.erb

Fix comment @mention autocomplete (broken in 1257639). Also fix forum post autocomplete (didn't work when editing forum posts). Does so by adding an `autocomplete-mentions` class to dtext fields where autocomplete should happen.

Fix @mention autocomplete for comments & forum posts.

---

app/models/post.rb
app/views/comments/partials/show/_comment.html.erb

6e62a4c: Pageloads of posts with large numbers of favorites are slowed down by the favorites list in the sidebar loading users one at a time. This costs hundreds of queries for some posts. 
4e8006a fixes a similar problem with each commenter being loaded one at a time instead of all at once.
Test case: `post #1` has ~300 favorites and ~140 comments. It's ~500ms slower to load when logged in (fav list is rendered) versus logged out (fav list isn't rendered). This PR reduces the number of queries on this page from 400+ to 25.

Reduce SQL queries on /posts/:id

---

app/models/post.rb

Tiny optimization for updating posts. Fixes a timeout the `bad_id` mass update had:
PG::QueryCanceled: ERROR: canceling statement due to statement timeout : SELECT 1 AS one FROM "posts" WHERE ("posts"."md5" = '8c8e17136bc28912abb828a58f0249de' AND "posts"."id" != 304893) LIMIT 1

Posts: don't revalidate md5 uniqueness on every update.

---

app/models/post.rb

ref: http://danbooru.donmai.us/forum_topics/9127?page=152#forum_post_125391
PR #2819 broke the ordering of the favlist. This puts it back in the order of users who favorited the post first.

Fix ordering of favlist

---

app/controllers/related_tags_controller.rb
app/logical/related_tag_query.rb
app/views/related_tags/show.html.erb
app/views/tags/_secondary_links.html.erb

Made a very basic search form and listing for related tags, mostly using existing methods that handle JSON requests. I feel like there's a lot of room for the improvement, like for example actually displaying tag count, but this works, too.

Related tags html page (fixes #2750)

---

app/views/post_votes/create.js.erb

ref: http://danbooru.donmai.us/forum_topics/9127?page=152#forum_post_125487
Introduced in 5445b341bcd77dee941623ed7e36e751fa2b64a1. Toggling the voting links only on success made it so that the unvote link wasn't shown after an "already voted" error.

Fix voting not showing 'undo vote' link if you already voted.

---

app/assets/javascripts/artist_commentaries.js
app/views/artist_commentaries/_form.html.erb
app/views/posts/show.html.erb

ref: http://danbooru.donmai.us/forum_topics/9127?page=152#forum_post_125482
The bug was `$('#add-commentary-dialog form')` selecting the wrong form to submit.
Also included is a minor clean up of the artcomm partial to pass in the post, not just use `@post` implicitly.

Fix artist commentary dialog submitting wrong form.

---

app/models/user.rb
app/models/user_name_change_request.rb
app/presenters/user_presenter.rb
app/views/users/_statistics.html.erb

Does a few things:
* Makes previous names visible to member+.
* Makes all previous name change requests visible to admins or the requester. This is so rejected name changes are accessible. Rejections don't actually happen any more, but still.
* Links to the actual name change request. Mainly intended for admins.
Example: http://devbooru.evazion.ml/users/52664

Fix #2830: Lower Permission to See Previous Usernames

---

app/helpers/application_helper.rb
app/logical/moderator/ip_addr_search.rb
app/views/artist_commentary_versions/index.html.erb
app/views/artist_versions/index.html.erb
app/views/dmails/show.html.erb
app/views/ip_bans/index.html.erb
app/views/maintenance/user/dmail_filters/edit.html.erb
app/views/moderator/ip_addrs/_ip_listing.erb
app/views/moderator/ip_addrs/_user_listing.erb
app/views/note_versions/index.html.erb
app/views/pool_versions/index.html.erb
app/views/post_versions/_listing.html.erb
app/views/wiki_page_versions/index.html.erb
db/migrate/20170112021922_add_ip_addr_indexes_to_tables.rb
db/migrate/20170112060921_change_ip_addr_to_inet_on_post_appeals.rb
db/structure.sql
test/unit/moderator/ip_addr_search_test.rb

I had some trouble with 63c218d71daaef653d4241a2e369e663cef68f58 still erroring out on the ip search page because it was doing a `select ... from pool_versions` but I didn't have an `archive_development` db with a `pool_versions` table. In dealing with that I fixed various other ip search issues:
* Use `link_to_user` on the ip search page so that usernames are colorized.
* Link ip addresses to ip searches everywhere.
* Search several more tables that had been overlooked.
* Add indexes on ip addrs for tables that didn't have them.
* Fix `creator_ip_addr` on `post_appeals`: it was mistakenly declared as type `integer` instead of `inet`. I think all the current data in that column is garbage because of this, so the migration just nulls it.
Also I learned that postgres has an index type for …

IP search fixes

---

app/logical/sources/strategies/base.rb

The root cause is [here](https://github.com/r888888888/danbooru/blob/3ad639521ff70db4198be0d1e44f808503c102c6/app/logical/sources/strategies/pixiv.rb#L314-L316). Pixiv posts can be in an "Original" category, so we fake up a tag in that case, but that can create a duplicate. I deemed it better to uniq the tags for all sources.

Fix #2839: "Original" tag shows up twice in Pixiv source data

---

app/models/user_name_change_request.rb
app/views/user_name_change_requests/new.html.erb

PR #2842 introduced an exploit making username change reasons visible in the API. orz. This fixes it.
This also removes the reason field from the request form. There's no point in asking for a reason when requests are auto-approved now.

Fix user name change reasons being public in API

---

app/controllers/user_feedbacks_controller.rb
app/models/user.rb
app/models/user_feedback.rb
app/models/user_name_change_request.rb

Hides name change requests and feedbacks for deleted users (usernames matching /user_[0-9]+~*/).

Fix #2851: Account deletion should remove name change requests.

---

app/assets/javascripts/autocomplete.js
app/logical/post_query_builder.rb
test/unit/post_test.rb

Also fixes an issue with `order:comment_asc` returning uncommented on posts first. This lists them last so that `order:comment_asc` properly returns the list of least-recently-commented-on posts.

Add order:comment_bumped, order:comment_bumped_asc metatags.

---

app/assets/stylesheets/common/simple_form.css.scss
app/controllers/comments_controller.rb
app/models/comment.rb
app/views/comments/search.html.erb

ref: http://danbooru.donmai.us/forum_topics/13649
* Adds more options to /comments/search.
* Restyles the form to use inline labels, since adding these options made the form pretty long. This matches the forms on /tags and /pools, except a bit cleaner as it's done in CSS rather than hardcoded as tables in html.

Add more options to /comments/search

---

.env
.gitignore
Gemfile
Gemfile.lock
Procfile
app/models/pool_archive.rb
app/models/post_archive.rb
app/models/post_read_only.rb
config/danbooru_default_config.rb
config/initializers/danbooru_config.rb
config/initializers/secret_token.rb
config/state_checker.rb
config/unicorn/unicorn.rb
script/install/database.yml.templ

This is a stab at adding dotenv support, a la danbooru's microservices. The goal is to be able to define your config entirely in `.env`. I find this easier to manage, especially when running multiple instances in parallel.
* Adds a simple `Procfile`.
* Adds a `unicorn.rb` config that takes settings from the environment. Recommended use is `RAILS_ENV=<development|production> foreman start`.
* Allows passing Rails secrets in an env var instead of `~/.danbooru/secret_token`.
* Allows configuring `danbooru_default_config.rb` using env vars instead of `danbooru_local_config.rb`. The behavior is that e.g. `DANBOORU_PIXIV_LOGIN`, if present, overrides `pixiv_login` in your local config.
* Allows configuring databases via `DATABASE_URL` instead of `database.yml`. Note that Rails' handling of …

Add dotenv support

---

app/assets/javascripts/artists.js
app/assets/javascripts/favorite_groups.js
app/assets/javascripts/forum_posts.js
app/assets/javascripts/notes.js
app/assets/javascripts/paginator.js
app/assets/javascripts/pools.js
app/assets/javascripts/post_mode_menu.js
app/assets/javascripts/post_popular.js
app/assets/javascripts/posts.js
app/assets/javascripts/shortcuts.js
app/assets/javascripts/uploads.js
app/assets/javascripts/utility.js
app/assets/javascripts/wiki_pages.js
app/views/artists/_secondary_links.html.erb
app/views/forum_topics/_secondary_links.html.erb
app/views/pools/_secondary_links.html.erb
app/views/static/keyboard_shortcuts.html.erb
app/views/wiki_pages/_secondary_links.html.erb

* Adds E to edit, shift+D to delete hotkeys to artists, pools, wiki, forum.
* Adds left arrow, right arrow bindings for prev/next page. (cc @RaisingK and @Moebius-Strip, I think their userscripts do this).
* Refactors hotkeys to use `.on()` instead of `.bind()`. `.bind()` is deprecated as of jquery 3.0. ref: https://api.jquery.com/bind/
* Binds hotkeys using jquery event namespaces so that it's possible for userscripts to override our keybindings. e.g. `$(document).off("danbooru.edit")` unbinds the `edit` hotkey. ref: https://api.jquery.com/on/#event-names:
> An event name can be qualified by event namespaces that simplify removing or triggering the event. For example, "click.myPlugin.simple" defines both the myPlugin and simple namespaces for this particular click event. A click event …

Add additional hotkeys

---

Gemfile.lock

This fixes a couple gems that had problems with ruby 2.4's [Integer unification](https://blog.heroku.com/ruby-2-4-features-hashes-integers-rounding#unified-integers). Note that rails 4.2.7.1 also has an issue (see: github.com/rails/rails/issues/25125), so Danbooru still doesn't run under 2.4 yet.

Update gems for ruby-2.4.

---

app/models/post.rb

As described in [topic #13677](http://danbooru.donmai.us/forum_topics/13677), I think Danbooru is sending failed uploads to IQDBS. This could happen if an `after_save` callback times out, since `after_create` runs before `after_save`.
The IQDB database will also have to be regenerated to purge invalid post IDs from it. I think it would be better if MD5s were stored in IQDB instead of post IDs, that way it'd be easier to maintain consistency.

Don't send failed uploads to IQDB (possible fix for #2867).

---

app/assets/javascripts/autocomplete.js
app/logical/post_query_builder.rb
app/models/tag.rb

Adds a `filetype:` metatag. This is primary for `filetype:png` searches, but it actually works well for other file types even though the column isn't indexed. `filetype:mp4 order:id_asc` is the worst case at ~3.5s on my system.

Add filetype: metatag.

---

app/assets/javascripts/forum_posts.js
app/assets/javascripts/notes.js
app/assets/javascripts/posts.js

Disables the left/right hotkeys for going to the prev/next page due to complaints that it interferes with horizontal scrolling of wide images.
Also fixes a bug with `shift+r` to mark the forum as read not working, and another issue with a mouseup handler on notes being rebound instead of unbound.

Disable left/right keys for prev/next page on /posts/:id.

---

app/models/note.rb
app/models/post.rb
test/functional/posts_controller_test.rb
test/helpers/saved_search_test_helper.rb
test/unit/comment_test.rb
test/unit/moderator/tag_batch_change_test.rb
test/unit/post_test.rb
test/unit/saved_search_test.rb
test/unit/tag_alias_test.rb

Fixes various failing test cases, see the commits for details.
I still get some failures, particularly a bunch of `Net::HTTP::Persistent::Error: too many connection resets (due to closed stream - IOError)` exceptions in the pixiv tests. Not sure why.

Fix various failing tests

---

app/helpers/application_helper.rb
app/views/user_mailer/dmail_notice.html.erb
config/application.rb
test/mailers/previews/user_mailer_preview.rb

Fixes #2887. Depends on https://github.com/r888888888/dtext_rb/pull/12. This makes the email notice you get when you receive a dmail use absolute urls instead of relative urls.
You can preview the mailer by going to `/rails/mailers` (you'll need to disable the `*other -> not_found` route for this to work).

Fix: Incorrect Relative Links for User Feedbacks #2887

---

app/views/layouts/default.html.erb
db/migrate/20170218104710_add_indexes_to_dmails.rb
db/structure.sql

Adds indexes on dmails and slightly optimizes the dmail notice logic (should shave off a couple sql queries).

Dmails: add indexes on is_read and is_deleted (fix #2886)

---

app/controllers/moderator/post/queues_controller.rb
app/presenters/post_presenter.rb
app/presenters/tag_set_presenter.rb
app/views/comments/partials/index/_header.html.erb
app/views/moderator/post/queues/show.html.erb
app/views/post_disapprovals/_compact_counts.html.erb
app/views/post_disapprovals/_counts.html.erb

This does several things:
* formats detailed disapproval messages using dtext on the `/posts/NNN` page and in the modqueue.
* in the modqueue, shows detailed disapproval messages for all disapproval types (disinterest/breaks rules/poor quality). Currently only distinterest messages are shown for some reason?
* fixes a minor N+1 queries problem on the modqueue page. Reduces the total number of sql queries on that page from 47 to 13.
* formats tag lists as colorized links, like in the `/comments` index.

modqueue: link tags, optimize sql, use dtext in disapproval reasons.

---

app/logical/user_name_validator.rb
app/models/user.rb
app/models/user_name_change_request.rb
test/unit/user_test.rb

Addresses #2894. Also makes sure that usernames in name change requests are validated the same way that new accounts are validated.

Disallow unicode whitespace in usernames (#2894).

---

app/controllers/admin/users_controller.rb
app/controllers/comments_controller.rb
app/controllers/dmails_controller.rb
app/controllers/legacy_controller.rb
app/controllers/maintenance/user/deletions_controller.rb
app/controllers/moderator/post/posts_controller.rb
app/controllers/post_versions_controller.rb
app/controllers/posts_controller.rb
app/controllers/uploads_controller.rb
app/controllers/user_name_change_requests_controller.rb
app/controllers/users_controller.rb
app/controllers/wiki_pages_controller.rb

These are redundant because ApplicationController rescues these exceptions already.

Remove redundant rescue_from calls.

---

app/logical/d_text.rb
app/logical/mentionable.rb
app/models/comment.rb
app/models/dmail.rb
app/models/forum_post.rb
test/unit/comment_test.rb
test/unit/dmail_test.rb
test/unit/forum_post_test.rb
test/unit/user_test.rb

Continuing on http://danbooru.donmai.us/forum_topics/13760:
6994231: send \@mention dmails from DanbooruBot instead of the mentioner.
6e3ddb6: don't save copies of dmails sent by DanbooruBot in DanbooruBot's outbox.
46280f2: include the mentioner in the subject line of the dmail. The template is this:
```
Subject:
#{creator_name} mentioned you in a comment on post ##{post_id}
Body:
@#{creator_name} mentioned you in a \"comment\":/posts/#{post_id}#comment-#{id} on post ##{post_id}:
[quote]
#{DText.excerpt(body, "@"+user_name)}
[/quote]
```
Also changes the excerpt to be the paragraph containing the \@mention, plus the preceding and following paragraphs for context. Currently the excerpt is the 100 characters surrounding the mention, but this tends to mangle dtext by cutting things off in …

Send @mention dmails from DanbooruBot

---

app/controllers/upload_tags_report_controller.rb
app/helpers/upload_tags_report_helper.rb
app/models/upload_tags_report.rb
app/views/upload_tags_report/show.html.erb
config/routes.rb

Quick implementation for  #2863. This is a naive approach: I created a new read-only `UploadTagReport` model by extending `Post` and adding methods for comparing versions. This allows for easy pagination, but I have a sneaking suspicion it doesn't really fit Rails' MVC paradigm, and it should have gone into `logical` instead, with methods like `search` to return collection of some other class having `Post` as an instance variable; but I was completely baffled about applying pagination to such things. @r888888888 ?
Ideally, to make the report more useful, there should also be a way to exclude posts where all tags were added by uploader. This fits numbered pagination even less, unfortunately, and I'm not familiar enough with sequential paginator to make it work on something like that. …

Implement #2863: basic upload tags change report

---

app/assets/javascripts/mod_queue.js
app/assets/stylesheets/common/000_vars.scss
app/assets/stylesheets/specific/mod_queue.scss
app/models/post.rb
app/views/moderator/post/queues/random.html.erb
app/views/moderator/post/queues/show.html.erb

ref: http://danbooru.donmai.us/forum_topics/13646?page=7#forum_post_127569
This would highlight posts in the modqueue that contain certain "bad" tags:
highlighted red: `duplicate`, `md5_mistmatch`, `resized`, `upscaled`, `downscaled`.
highlighted yellow: `hard_translated`, `self_upload`, `nude_filter`, `photoshop`, `screencap`.

Modqueue: highlight uploads containing "bad" tags.

---

db/migrate/20170302014435_remove_default_ip_addr_from_dmails.rb
db/structure.sql
test/unit/dmail_test.rb

Bug introduced in 1400f64; that commit changed dmails so that `creator_ip_addr` defaulted to `CurrentUser.ip_addr` like this:
```ruby
after_initialize :initialize_attributes, if: :new_record?
def initialize_attributes
self.from_id ||= CurrentUser.id
self.creator_ip_addr ||= CurrentUser.ip_addr
end
```
...but `creator_ip_addr` already defaulted to 127.0.0.1 from the database, so the ||= assignment didn't work. Remove the database default so we always default to `CurrentUser.ip_addr` instead.

dmails: don't default IP addr to 127.0.0.1 in database (fixes #2908).

---

config/initializers/simple_form.rb
config/locales/simple_form.en.yml
lib/templates/erb/scaffold/_form.html.erb

This regens the simple form config using `rails generate simple_form:install`. It seems to fix #2913 for me, although I'm not really sure why. I'm guessing that minlength validations default to enabled when `b.optional :minlength` isn't set in the initializer.

Possible fix for "Unable to Create New Topics With 255 Characters or Less" (#2913)

---

app/assets/javascripts/artist_commentaries.js
app/presenters/post_presenter.rb

Fixes this issue reported in https://danbooru.donmai.us/forum_topics/9127?page=164#forum_post_128360:
> When you use the fetch commentary feature to add commentary when there is existing commentary, Danbooru seems to fetch the URL listed as source. I.e.,
>
> Source: https://i1.pixiv.net/img-original/img/2017/01/18/00/56/32/60988872_p0.jpg
>
> I think this should be a link to the HTML page.

When merging artcomms, list source as html page url, not image url.

---

app/controllers/sources_controller.rb
app/logical/sources/site.rb
app/views/static/error.json.erb

Does a couple very minor things in the sources controller:
* Adds /sources.xml support.
* Makes all json responses include a backtrace on error, not just those on /sources.json.

Add /sources.xml endpoint; include backtraces in json

---

app/logical/post_sets/post.rb
app/views/posts/partials/index/_posts.html.erb

As discussed in https://danbooru.donmai.us/forum_topics/13828, this would add a notice to /posts when results are removed due to being banned or censored. The purpose is so that when a member searches for a banned artist or for loli, they get some explanation of why the results are empty.
Demo:
http://devbooru.evazion.ml/posts?tags=banned_artist
http://devbooru.evazion.ml/posts?tags=loli

/posts: add notice when posts are hidden.

---

app/logical/moderator/dashboard/queries/tag.rb
app/logical/moderator/dashboard/report.rb

http://danbooru.donmai.us/moderator/dashboard is broken due to a reference to the post versions table. 
The problem is the tag updates section is supposed to show the list of top post updaters filtered by a given user level, but doing that requires joining on users, which isn't possible any more. So this just does the filtering in ruby.

Fix post version reference on /moderator/dashboard

---

app/models/post_event.rb
test/functional/post_events_controller_test.rb

Fixes an issue reported in https://danbooru.donmai.us/forum_topics/13831 ("Why are appeals made on deleted posts automatically resolved?"):
/posts/:id/events incorrectly lists appeals as always being resolved. This is because events UNION together appeals and flags, which doesn't quite work because for appeals is_resolved is a method, not an
attribute. is_resolved was hardcoded to true so it'd work in the UNION.
This changes PostEvent to be a wrapper object around PostFlag / PostAppeal, instead of a UNION. PostEvent delegates everything to the inner flag/appeals object, so that is_resolved works correctly.
Also, this incidentally fixes a problem with /posts/:id/event.xml not serializing correctly (see https://danbooru.donmai.us/posts/2651416/events.xml).

/posts/:id/events: list is_resolved correctly for appeals.

---

app/helpers/post_appeals_helper.rb
app/helpers/post_flags_helper.rb
app/views/comments/partials/show/_comment.html.erb

There was an accusation on the forum about certain flags being from a sockpuppet. This would make flagger and appealer IPs visible next to the flag reason so that mods can detect such cases more easily.
This would also make commenter IPs visible in the comments. There's a certain regular commenter who I suspect of sockpuppeting.

Make commenter/flagger/appealer IPs visible to mods

---

app/logical/moderator/dashboard/queries/tag.rb
app/models/post_event.rb
app/presenters/post_presenter.rb
test/functional/post_events_controller_test.rb

Fixes a few bugs in the last round of pull requests I sent:
47ecf03 - /posts/:id/events - fixes an exception when page is viewed by a mod.
2aa3f9c - /moderator/dashboard: fix exception when PostArchive isn't enabled (see http://testbooru.donmai.us/moderator/dashboard).
d1debec - Fix XSS in post thumbnail data attributes (I added a `data-source` attribute but I forgot to escape it).

Fix exceptions on /posts/:id/events, /moderator/dashboard; fix XSS in data-source.

---

app/logical/moderator/dashboard/queries/artist.rb
app/logical/moderator/dashboard/queries/comment.rb
app/logical/moderator/dashboard/queries/mod_action.rb
app/logical/moderator/dashboard/queries/note.rb
app/logical/moderator/dashboard/queries/post_appeal.rb
app/logical/moderator/dashboard/queries/tag.rb
app/logical/moderator/dashboard/queries/upload.rb
app/logical/moderator/dashboard/queries/user_feedback.rb
app/logical/moderator/dashboard/queries/wiki_page.rb
app/views/moderator/dashboards/_activity_appeal.html.erb
db/migrate/20170319000519_add_created_at_index_to_versions.rb
db/structure.sql

This optimizes the http://danbooru.donmai.us/moderator/dashboard page in two ways:
* Adds `created_at` indexes that were missing on a few version tables.
* Converts the queries to use active record instead of raw sql. This fixes some issues with users being loaded one-by-one in multiple places. Doing this cuts the number of sql queries executed by the page in half.

/moderator/dashboard: optimize sql queries

---

app/helpers/artists_helper.rb
app/helpers/tags_helper.rb
app/helpers/wiki_pages_helper.rb
app/logical/post_sets/post.rb
app/models/post.rb
app/models/tag.rb
app/models/tag_implication.rb
app/presenters/wiki_page_presenter.rb
app/views/posts/partials/index/_excerpt.html.erb

Fixes #2931. In addition:
* adds `(learn more)` links next to the alias / implication lists in wiki excerpts.
* shows alias / implication lists even for tags that don't have a wiki entry.

Fix #2931: mention automated implications on *_(cosplay) wikis.

---

app/models/post.rb

Fixes an exception caused by the `animated_gif` autotagger trying to access the gif file, which fails if the file isn't present due to #2500.
This is the lazy fix. The real fix would be to do the autotagging at post creation instead of on post update. This would be a slight change in behavior though, since then it would be possible to remove the `animated_gif` tag, whereas now you can't.
```ruby
Magick::ImageMagickError exception raised
unable to open image `/var/www/danbooru2/releases/20170322212609/public/data/f0e32c0e2d906c4932858866346f98b5.gif': No such file or directory @ error/blob.c/OpenBlob/2712
app/models/post.rb:177:in `ping'
app/models/post.rb:177:in `is_animated_gif?'
app/models/post.rb:684:in `add_automatic_tags'
app/models/post.rb:638:in `normalize_tags' …
```

Fix exception when autotagging animated_gifs

---

app/presenters/presenter.rb

Fixes this exception that happens when a post has a NULL source:
TypeError exception raised
no implicit conversion of nil into String
app/presenters/presenter.rb:3:in `escapeHTML'
app/presenters/presenter.rb:3:in `h'
app/presenters/post_presenter.rb:91:in `data_attributes'
app/presenters/post_presenter.rb:24:in `preview'
app/presenters/post_set_presenters/base.rb:15:in `block in post_previews_html'
app/presenters/post_set_presenters/base.rb:14:in `post_previews_html'
app/views/posts/partials/index/_posts.html.erb:3:in `_app_views_posts_partials_index__posts_html_erb___2716396856929289512_70158315986180'
app/views/posts/index.html.erb:39:in `_app_views_posts_index_html_erb__1345252938355811220_70158296799280'
app/controllers/posts_controller.rb:16:in `index'

Fix exception in `h(post.source)` when source is nil (fixes #2940).

---

app/models/post.rb
app/models/post_vote.rb
app/models/user.rb
app/presenters/presenter.rb
test/unit/post_test.rb
test/unit/post_vote_test.rb

Fixes three favorite moving bugs:
* Upvotes on the parent post were performed by the favorite mover, rather than the user that favorited the post.
* Favorites by supervoters didn't give the parent a supervote (a consequence of the above bug).
* Non-gold supervoters didn't upvote the post when favoriting.

Upvote correctly when moving favorites (partial fix for #2936)

---

app/models/saved_search.rb
test/unit/saved_search_test.rb

Fixes an exception when searching for a nonexistent saved search label (e.g. `search:aoijoiqwf`):
NoMethodError exception raised
undefined method `empty?' for nil:NilClass
app/logical/post_query_builder.rb:113:in `block in add_saved_search_relation'
app/logical/post_query_builder.rb:106:in `each'
app/logical/post_query_builder.rb:106:in `add_saved_search_relation'
app/logical/post_query_builder.rb:237:in `build'
app/models/post.rb:1624:in `tag_match'
app/models/post.rb:1172:in `block in fast_count_search'
config/initializers/active_record_extensions.rb:16:in `with_timeout'
app/models/post.rb:1171:in `fast_count_search'
app/models/post.rb:1162:in `fast_count'
app/logical/post_sets/post.rb:106:in `get_post_count'
app/logical/post_sets/post.rb:122:in `posts' …

Fix exception when searching for `search:adfijoioi`.

---

app/controllers/reports_controller.rb
app/logical/reports/upload_tags.rb
app/models/post.rb
app/views/reports/upload_tags.html.erb
app/views/users/_statistics.html.erb

Should close out #2863:
* Links to upload tag report in user profiles
* Shows thumbnails instead of post ids.
* Fixes a couple N+1 queries issues.

Fix upload tags report (closes #2863)

---

app/controllers/post_versions_controller.rb
app/controllers/reports_controller.rb
app/models/post_archive.rb

Fixes a N+1 problem when a post version fetches the previous post version to calculate a diff.
page | before | after
------|--------|------
/reports/upload_tags | https://i.imgur.com/Eb5NOLN.png | https://i.imgur.com/mTgz2fJ.png
/post_versions |  https://i.imgur.com/uL1xIKq.png | https://i.imgur.com/hSh4Qs8.png

Post archives: fix final N+1 problem.

---

Gemfile
Gemfile.lock
app/models/pool.rb
app/models/post.rb
test/unit/pool_test.rb
test/unit/post_archive_test.rb

Should fix #2950. Sends post/pool versions in an `after_commit` hook so that they're sent only after the post is successfully saved to the db.
The offending post version will still need to be deleted.

Fix #2950: Post Versions: "undefined method" error for specific edit

---

app/logical/downloads/rewrite_strategies/pixiv.rb
app/logical/sources/strategies/pixiv.rb

Detects and rewrites the new manga gallery sample url format:
* https://i.pximg.net/img-master/img/2014/05/15/23/53/59/43521009_p1_master1200.jpg
to original urls:
* http://i2.pixiv.net/img-original/img/2014/05/15/23/53/59/43521009_p1.jpg

Fix i.pximg.net manga gallery samples (fix #2946)

---

app/models/post.rb
test/unit/post_test.rb

Bug: when moving favorites to a parent post, hidden favorites weren't moved. This is because `favorited_users` doesn't include favorites that are hidden from `CurrentUser`.
related: #2936.

Move hidden favorites when moving favs.

---

app/models/favorite.rb
app/models/post.rb

Fixes an exception when moving favorites. Caused by me forgetting to include `belongs_to :user` in 7779375.
Also wraps fav movement in a transaction to ensure that if anything fails then the whole transfer is rolled back.
related: #2936
ref: https://danbooru.donmai.us/forum_topics/9127?page=171#forum_post_129261

Fix exception when moving favorites

---

app/controllers/iqdb_queries_controller.rb
app/logical/iqdb/download.rb
app/views/iqdb_queries/create_by_post.js.erb
app/views/iqdb_queries/create_by_url.html.erb
config/routes.rb
test/functional/iqdb_queries_controller_test.rb

This adds json/xml api endpoints to `/iqdb_queries`, plus an `/posts/1234/similar.json` endpoint. This also makes `/iqdb_queries` accessible via GET. Currently `/iqdb_queries` is POST only, which is inconvenient for userscripts because of cross-origin restrictions.
Available endpoints:
* `GET /posts/1234/similar.json`
* `GET /iqdb_queries.json?post_id=1234`
* `GET /iqdb_queries.json?url=<url>`

Add API support to /iqdb_queries

---

app/controllers/post_appeals_controller.rb
app/controllers/post_flags_controller.rb
app/models/post_appeal.rb
app/models/post_flag.rb
app/views/post_appeals/_search.html.erb
app/views/post_appeals/index.html.erb
app/views/post_flags/_search.html.erb
app/views/post_flags/index.html.erb

This does a few things to improve usability of the flags and appeals pages:
* adds a tag search field for filtering by tags.
* adds uploader, approver, and flagger/appealer columns.
* adds `»` links that let you narrow your search to flags for a given uploader/approver/flagger.
* adds a flag/appeal count so you can see when a post has by flagged/appealed multiple times.
Screenshots:
* https://i.imgur.com/oMjadDh.png
* https://i.imgur.com/3YPuhMB.png

Improve /post_flags, /post_appeals pages

---

app/assets/javascripts/artists.js
app/assets/javascripts/pools.js
app/assets/javascripts/wiki_pages.js
app/controllers/artists_controller.rb
app/controllers/wiki_pages_controller.rb
app/models/artist.rb
app/models/pool.rb
app/models/wiki_page.rb
app/views/artists/_search.html.erb
app/views/wiki_pages/search.html.erb
db/migrate/20170329185605_add_updated_at_index_on_wiki_pages.rb
db/structure.sql

This fixes various issues with the autocomplete on the artists, wikis, and pools pages:
* de7a8cf, 3852143: autocomplete for artists and wikis currently gives poor results. This makes artists and wikis perform autocomplete the same way that tag autocomplete is performed.
* fa908a6: filter deleted artists from autocomplete (cf #2945).
* 00d0d08: *don't* filter pools marked as inactive from autocomplete. For pools, `is_active = false` doesn't mean the pool is deleted, it means the series is "complete" (no more posts will be added).
* 24e3705: fix an ambiguous column exception when doing https://danbooru.donmai.us/artists?search[empty_only]=true&search[name]=hammer*.
* 85a39ca, bb2f0ff, 6740285: optimize some queries to make autocomplete faster.
* fcc5521: add an `updated_at` index for wiki …

Improve autocomplete on /artists, /wiki_pages, and /pools.

---

app/views/posts/partials/show/_options.html.erb

This adds a confirmation dialog to the Approve/Undelete links in the post sidebar. This is to prevent accidental approvals.
From https://danbooru.donmai.us/forum_posts/129311:
> On a side note, I don't know how desired it would be, but I'd like if we could have an option to double-check if we want to approve a post that's either flagged/pending/deleted outside of the mod queue when clicking 'Approve' from the sidebar. This is because I accidentally click the approve option when I meant to click the delete option (they're right next to each other on the sidebar).

Add confirm dialog to sidebar approve/undelete links.

---

app/models/tag_alias.rb
app/models/wiki_page.rb
app/views/wiki_pages/_form.html.erb
test/functional/wiki_pages_controller_test.rb

Does two things:
* Disallows renaming wiki entries unless the corresponding tag is empty. A `Force rename` checkbox lets you skip the validation.
* Allows Members to rename wiki entries. This was disallowed in the web ui but not in the api. I don't see a need to restrict this, renames can always be reverted.

Fix #2964: prevent renaming wikis with non-empty tags.

---

app/helpers/application_helper.rb
app/views/post_appeals/_new.html.erb
app/views/post_flags/_new.html.erb
app/views/posts/show.html.erb

This adds dtext preview to the flag and appeal dialog boxes.
A caveat: this makes the `<textarea>` box for the reason bigger, too big in fact. The font size is bigger as well. The `textarea` CSS ought to be fixed so that textareas are styled consistently sitewide. I avoided that for now because it's a bigger change.
ref: https://danbooru.donmai.us/forum_topics/13927

Add dtext preview to flags and appeals

---

test/unit/post_archive_test.rb

This is just a testcase demonstrating that using the `pool:<name>` metatag doesn't save a post version. #2972.

Test pool metatag not saving bug (#2972).

---

app/views/post_appeals/new.html.erb
app/views/post_flags/new.html.erb
test/functional/tag_subscriptions_controller_test.rb
test/unit/downloads/pixiv_test.rb
test/unit/sources/pixiv_test.rb

Fix some Pixiv tests that fail due to the switch to https://i.pximg.net. Also fixes a tag subscription test, and an exception on the `/post_flags/new` and `/post_appeals/new` pages.

Fix failing Pixiv tests

---

app/models/post_appeal.rb
app/models/post_flag.rb
app/views/post_appeals/_search.html.erb
app/views/post_flags/_search.html.erb
db/migrate/20170416224142_add_reason_ts_vector_index_to_post_flags_and_appeals.rb
db/structure.sql

This would add full text search for flag and appeal reasons. This is so that searches like `quality check` will match variations like `rechecking quality`.
Note that the index here is defined as an expression index: `USING gin (to_tsvector('english', reason))`. This way avoids the need to have a separate index column with a trigger function that updates that column, as is done is most other places using a gin index.

Add full text search for flag/appeal reasons

---

db/structure.sql

A couple of `bank_transactions` and `bank_balances` tables slipped into structure.sql with  da06bee0ab19c683a278a787e9c87b78d7ec3993. I take it this was an accident.

Remove bank_balances, bank_transactions from structure.sql.

---

app/assets/stylesheets/common/000_vars.scss
app/assets/stylesheets/common/tables.scss
app/assets/stylesheets/specific/bans.scss
app/controllers/bans_controller.rb
app/helpers/application_helper.rb
app/models/ban.rb
app/models/user_feedback.rb
app/views/bans/_search.html.erb
app/views/bans/index.html.erb
test/unit/ban_test.rb

This would add some improvements to the `/bans` page:
* adds a search form.
* adds columns for the banner, ban creation time, and ban duration.
* color code bans as expired or unexpired.
The result should be a lot more usable: [before](https://i.imgur.com/gTxeVMW.png), [after](https://i.imgur.com/E93Pamj.png).

Improve /bans listing

---

app/models/saved_search.rb
app/models/tag_subscription.rb
test/unit/saved_search_test.rb
test/unit/tag_subscription_test.rb

Migrating tag subscriptions to saved searches is broken. The problem is that the migration code still uses the `tag_query` / `category` params instead of `query` / `labels`. Consequently migrating a subscription deletes it without creating any saved searches.
This fixes the bug. It also skips deleting the subscription after it is migrated. This is so the user can verify it was moved properly before deleting it themselves.

Fix broken tag subscription migrations.

---

app/assets/stylesheets/specific/notes.scss
app/logical/d_text.rb

This would allow the `<ruby>`, `<rb>`, `<rp>`, and `<rt>` HTML tags to be used in notes. This is so that translators can mark up furigana without resorting to CSS hacks.
Discussion:
* https://danbooru.donmai.us/posts/2697885
* https://danbooru.donmai.us/forum_topics/13353?page=1#forum_post_130038
References:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby
* https://www.w3.org/TR/css-ruby-1/
* https://jsfiddle.net/3L4zszzs/2/

Allow <ruby> tags for marking up furigana in notes.

---

app/models/upload.rb

This file can't be uploaded: https://img.pawoo.net/media_attachments/files/000/133/785/original/06d859c9db2b0060.mp4.
The problem is that filetype detection during upload rejects it. It's an mp4 with an `ftyp` of `avc1`, but this `ftyp` isn't on the whitelist.
According to http://www.ftyps.com/, there are a large number of valid `ftyp` designations. It might be better to use ffmpeg or something to detect the filetype.

Support mp4s of ftyp "avc1"

---

app/assets/javascripts/autocomplete.js
app/views/artist_commentaries/search.html.erb
app/views/comments/search.html.erb
app/views/meta_searches/tags.html.erb
app/views/moderator/bulk_reverts/new.html.erb
app/views/moderator/post/queues/show.html.erb
app/views/moderator/tags/edit.html.erb
app/views/notes/search.html.erb
app/views/post_appeals/_search.html.erb
app/views/post_flags/_search.html.erb
app/views/posts/partials/common/_search.html.erb
app/views/posts/partials/index/_edit.html.erb
app/views/posts/partials/index/_mode_menu.html.erb
app/views/posts/partials/show/_edit.html.erb
app/views/related_tags/show.html.erb
app/views/tag_alias_requests/new.html.erb
app/views/tag_aliases/index.html.erb
app/views/tag_implication_requests/new.html.erb
app/views/tag_implications/index.html.erb
app/views/tags/_quick_search.html.erb
app/views/tags/_search.html.erb
app/views/uploads/new.html.erb
app/views/users/edit.html.erb
app/views/wiki_pages/_form.html.erb

Tag autocomplete doesn't work in the `/posts` search box in the responsive layout. It also doesn't work in a few other places, namely the tag aliases and implications pages, the moderator mass edit page, and the bulk revert page.
This fixes it by marking all inputs that should be autocompleted with a  `data-autocomplete` attribute. This should be less fragile than the current method of hardcoding a big list of html ids in the javascript.
In doing this I converted some search forms over to simple form. This wasn't entirely necessary, but it's generally shorter and it helps ensure that forms are formatted consistently across the site.

Fix broken tag autocomplete on multiple pages

---

app/models/artist.rb
app/models/wiki_page.rb
test/functional/wiki_pages_controller_test.rb

Fixes #2990. `/wiki_pages?search[order]=post_count` didn't include wiki pages that didn't belong to a tag. This was due to doing an inner join on the tags table instead of a left outer join.

Fix #2990: Wiki Autocomplete Misses On Certain Meta-wikis

---

app/logical/related_tag_calculator.rb
app/presenters/post_set_presenters/post.rb
test/unit/related_tag_calculator_test.rb

Searching for single metatags such as `order:rank` or `user:evazion` or `fav:evazion` is somewhat slow. The culprit is the related tags sidebar. The related tags calculator calls `Tag.category_for` in its inner loop, which causes a memcache lookup on every iteration. At 100 posts per page and 20-30 tags per post, this led to 2000-3000 total memcache calls, which significantly slows the pageload.
This removes the `category_constraint` option from `RelatedTagCalculator.calculate_from_posts` entirely. As far as I can tell it isn't used anywhere.

Fix slow related tag calculations when searching single metatags.

---

app/views/posts/partials/common/_secondary_links.html.erb

The `sub:<name>` metatag doesn't work any more, so the navbar link should be removed.

Remove tag subscriptions link from /posts navbar.

---

app/assets/javascripts/comments.js
app/controllers/comments_controller.rb
app/logical/d_text.rb
app/logical/mentionable.rb
app/models/comment.rb
app/models/forum_post.rb
test/unit/comment_test.rb

From https://danbooru.donmai.us/forum_topics/9127?page=177#forum_post_130215:
> I found a weird bug on this [comment](https://danbooru.donmai.us/posts/2700454#comment-1682984). If you try to reply it, only the first paragraph appears on the comment box, while the other two are completely omitted.
There are two problems here:
* That comment has a `[quote][/QUOTE]` block, but the `[quote]` stripping code doesn't recognize uppercase `[/QUOTE]` tags.
* There are three separate `[quote]` stripping implementations (!): one for forum posts, one for \@mentions, and one for comments. The one for comments is in javascript.
This refactors things so that `DText.quote` is a single implementation that everything uses. There were slight differences between each version, but the one for \@mentions looked …

Fix [quote] stripping for comments, forum post replies.

---

app/views/post_appeals/_search.html.erb

The [/post_appeals](http://danbooru.donmai.us/post_appeals) search form is missing a blank option for the Resolved dropdown.

/post_appeals: add blank option to Resolved dropdown.

---

app/models/artist.rb
app/views/artists/_search.html.erb
test/unit/artist_test.rb

Fixes #2994. Adds these fields to the /artists search form:
* URL
* Creator
* Active?
* Banned?
* Has Tag?
And adds these params to the API:
* `search[name_matches]`
* `search[other_names_match]`
* `search[group_name_matches]`
* `search[any_name_matches]`
* `search[url_matches]`
* `search[has_tag]`
`has_tag=true` means the artist has a nonempty tag. `has_tag=false` means the artist entry doesn't have a tag or the tag is empty. `has_tag=false` is equivalent to `empty_only=true`.

Fix #2994: More options for artist search page

---

app/controllers/users_controller.rb
app/models/user.rb
test/functional/users_controller_test.rb

Fixes #1551. Allows users to see their account settings in /users.json. Also includes various other privileges and limits like whether they can upload or comment, their current upload limits, etc.

Fix #1551: Allow hidden user API attributes to be seen by the owner

---

app/assets/javascripts/notes.js
app/models/note.rb
test/unit/note_test.rb

Fixes #1566. Disallows blank note bodies instead of setting them to `(empty)`. There are about ~20 blank notes in existence, but they're all deleted. There were about ~60 active notes with `(empty)` bodies as well, all of which were either mistakes or vandalism. Disallowing blank notes should prevent these mistakes.

Fix #1566: disallow blank note bodies.

---

db/migrate/20170428220448_remove_name_and_category_from_saved_searches.rb
db/structure.sql

`name` and `category` haven't been used since saved searches were rewritten.

Saved searches: drop unused name and category columns.

---

app/models/saved_search.rb
app/models/tag.rb
app/models/tag_alias.rb
test/factories/tag_alias.rb
test/unit/saved_search_test.rb

Fixes #2995. Normalize the query \*except\* for the tag ordering when the saved search is saved. Normalize everything \*including\* the ordering when the search is sent to listbooru.
This normalization applies tag aliases as well, which should mean that rewriting saved searches when an alias is approved isn't necessary.

Fix #2995: Saved searches’ tags are getting reordered

---

app/assets/stylesheets/common/responsive.scss
app/assets/stylesheets/specific/posts.scss

From https://danbooru.donmai.us/forum_topics/9127?page=178#forum_post_130472:
> There is a problem with the translation notes: on the mobile site the picture is under the taglist, but the notes are above said taglist and not on the pic.
> The notes bug I can reproduce on [post #2706242](https://danbooru.donmai.us/posts/2706242) when the browser width is between 410px and 660px.
The problem is the responsive tag list was replaced by the regular sidebar in b7f207180c52a43bed9f477c660580bd0055d2eb, but the regular sidebar is still `float: left`. This fixes it to be `float: none`.
This also moves the taglist back beneath the image, like it was with responsive tag list, except using CSS instead of duplicating the markup. This means it works on all pages too, including for the sidebars on …

Fix tag list for responsive layout.

---

app/logical/post_query_builder.rb
app/models/comment.rb
app/models/tag.rb
test/unit/post_test.rb

Adds these metatags:
* `noter:any` - all posts with notes.
* `noter:none` - all posts without notes.
* `commenter:any` - all posts with comments.
* `commenter:none` - all posts without comments.
These tags are similar in purpose to `order:note` and `order:comment`, but without forcing an ordering. Saying `noter:any` to mean "posts that have notes" is kind of unintuitive, but it's chosen to be consistent with `approver:any`.

Add noter:<any|none>, commenter:<any|none> metatags

---

app/models/post_approval.rb
test/unit/post_test.rb

Bug: approving a deleted post logs the wrong thing as the post id for the mod action. Instead of logging the post id, it logs the id of the PostApproval.

Log correct post id when approving deleted posts.

---

app/assets/stylesheets/common/responsive.scss
app/assets/stylesheets/common/simple_form.scss
app/views/layouts/_main_links.html.erb

https://danbooru.donmai.us/forum_topics/9127?page=179#forum_post_130662:
> ...the top menu (the one you open with that blue thing beside the site's name) is behind everything else. So you can't click on parts of it. In posts it's like this - https://my.mixtape.moe/klsxqi.png In the pools section it's even worse, can't click on almost anything. Also the input fields are larger than the rest of the page - https://my.mixtape.moe/iuhewy.png
Fixes the responsive menu to not overlap the content. Fixes `<input>` sizes to be more reasonable. Fixes the `More »` link from line breaking in between `More` and `»`.

Fix responsive menu

---

app/logical/downloads/file.rb

Sets pawoo sources to the html page (https://pawoo.net/@kv18/6441531)  instead of the image file (https://img.pawoo.net/media_attachments/files/000/500/335/original/f682902651c2ca82.png) after upload.

Fix pawoo sources after upload.

---

app/models/post.rb
test/unit/post_test.rb

Discussion: https://danbooru.donmai.us/forum_topics/9127?page=179#forum_post_130592:
Current DeviantArt sources as linked as http://misumi_illustration.deviantart.com/gallery/#/db7ibsi in the sidebar. This relies on a javascript redirect on DeviantArt's end which doesn't work for everyone. This links the source as http://misumi-illustration.deviantart.com/art/Lethargic-friends-677740338 instead.
The comments in 1baffb3 are just documentation, the only change in the regexes was adding a `prnt` subdomain.

Fix links to DeviantArt sources

---

app/models/user.rb
test/unit/api_key_test.rb

Fixes Gold+ users having the same API limits as Members if they haven't generated an API key. This can affect tag scripting, among other things.
#3023, #2693.

Fix API limits being lowered when user doesn't have api key.

---

app/logical/session_loader.rb
app/models/user.rb
test/factories/user.rb
test/functional/sessions_controller_test.rb

Bug: logging in with an expired ban throws an exception when `User#unban!` calls `ban.destroy`. `ban` doesn't exist; users have many `bans` instead. Despite this bug, the `is_banned` flag is still cleared, so the next login attempt succeeds in any case.
This just removes the `ban.destroy` call, since expired bans shouldn't be destroyed to begin with.

Fix exception when user with expired ban logs in.

---

app/assets/javascripts/blacklists.js
app/assets/javascripts/posts.js
app/models/artist_version.rb
app/models/note.rb
app/models/post.rb
app/models/wiki_page.rb

Fixes #2352. Makes posts, notes, wiki pages, and artist versions return raw usernames instead of "pretty" names (names with spaces instead of underscores) in the API.

Fix #2352: Return raw usernames in API instead of pretty names.

---

config/initializers/active_record_api_extensions.rb
test/functional/users_controller_test.rb

Fixes #3024 by stripping `?` from API attributes globally. This means it applies to both JSON and XML.

Fix #3024: strip '?' from API attributes

---

app/models/post.rb
app/models/post_flag.rb
test/unit/post_approval_test.rb
test/unit/post_flag_test.rb

Discussion: https://danbooru.donmai.us/forum_topics/14010
Adds a three day cooldown after a post has been flagged before it can be flagged again. This cooldown only applies to user-generated flags, not to system-generated `Unapproved in three days` flags.

Add 3 day cooldown between flags

---

app/assets/stylesheets/specific/posts.scss
app/views/layouts/default.html.erb

Discussion: https://danbooru.donmai.us/forum_topics/14010?page=1#forum_post_130629
This would change the flag border color from red to blue for non-approvers. Non-approvers can't do anything about flagged posts so IMO calling them out does nothing but create drama.
This is accomplished by setting a `data-can-approve-posts` attribute on the `<body>` element and styling borders based on that. This is to avoid making the thumbnail markup unnecessarily dependent on the current user, which precludes fragment caching (it's still precluded by other things, but it would be nice if it were possible).

Change flag borders from red to blue for non-approvers.

---

app/controllers/delayed_jobs_controller.rb
app/helpers/application_helper.rb
app/views/delayed_jobs/cancel.js.erb
app/views/delayed_jobs/destroy.js.erb
app/views/delayed_jobs/index.html.erb
app/views/delayed_jobs/retry.js.erb
app/views/delayed_jobs/run.js.erb
config/initializers/delayed_jobs.rb
config/routes.rb

Adds admin-only run, cancel, retry, and delete actions to the `/delayed_jobs` listing:
* Run: set the job to run immediately.
* Cancel: marks the job as failed. Prevents the job from running, effectively putting it on pause.
* Retry: unmarks the job as failed. Allows the job to run again, effectively unpausing a cancelled job.
* Delete: delete the job entirely.
Also adjusts the layout of `/delayed_jobs` a bit to fix column widths and make things easier to read.
This is mainly intended to support #3015, but it could also be useful for dealing with aliases/implications.

Add ability to start/stop delayed jobs.

---

app/logical/backup_service.rb
app/logical/null_backup_service.rb
app/logical/s3_backup_service.rb
app/models/post.rb
config/danbooru_default_config.rb

Currently images are backed up to S3 by a cronjob that runs every 30 minutes. This would instead backup images immediately when a post is created or replaced. The backup is done in a delayed job, so if there's any kind of transient failure then the job will keep retrying until it succeeds. Failures would also be visible in the delayed jobs listing, which is nice for monitoring.
This would also make it easier for one to use backup methods other than S3. Just subclass `BackupService`, implement the `backup` method, and set `Danbooru.config.backup_service` to your custom service.

Backup posts to S3 on creation/replacement

---

app/models/comment.rb
test/unit/comment_test.rb

https://danbooru.donmai.us/comments.json?group_by=comment returns comments in an undefined order instead of most recent first. This is because of the default ordering not being applied due to `Comment.search` bailing early when no params are given.

Fix /comments.json returning results in undefined order.

---

app/assets/javascripts/uploads.js
app/controllers/uploads_controller.rb
app/logical/downloads/rewrite_strategies/deviant_art.rb
app/logical/downloads/rewrite_strategies/pixiv.rb
app/logical/downloads/rewrite_strategies/twitter.rb
app/logical/sources/site.rb
app/logical/sources/strategies/base.rb
app/logical/sources/strategies/pixiv.rb
app/logical/sources/strategies/pixiv_whitecube.rb
app/logical/sources/strategies/twitter.rb
app/models/upload.rb
app/views/uploads/new.html.erb

Commentary on the uploads page has multiple issues:
* The commentary box isn't available if you don't use the bookmarklet.
* Commentary isn't populated when the title is present but the description is not (#3037).
* Special html characters are escaped (`&` -> `&amp;`) as a side effect of stripping html. This is not desired.
* Loading the commentary from the source blocks the page load.
This fixes the above issues in the following way:
* Makes the commentary box always present on the uploads page.
* Adds `dtext_title` and `dtext_commentary` fields to `/source.json`. These contain the commentary converted from whatever markup format the source uses to our own dtext format.
* Populates the commentary box using the above fields in `/source.json`. We fetch `/source.json` already, so we can …

Fix commentary box on upload page (fixes #3037)

---

app/logical/sources/strategies/base.rb
test/unit/sources/pixiv_test.rb

https://danbooru.donmai.us/forum_topics/9127?page=184#forum_post_131127:
> Error: undefined method `include?' for nil:NilClass
Fix a bug in a2a6a0c (#3038). If the fetched commentary is `nil`, then `CGI::unescapeHTML` will throw an exception.

Fix exception when fetched commentary is nil.

---

app/assets/javascripts/posts.js
app/controllers/moderator/post/posts_controller.rb
app/helpers/delayed_jobs_helper.rb
app/models/post.rb
app/models/upload.rb
app/presenters/post_presenter.rb
app/views/moderator/post/posts/_replace.html.erb
app/views/moderator/post/posts/replace.html.erb
app/views/posts/partials/show/_options.html.erb
app/views/posts/show.html.erb
config/routes.rb
test/unit/post_test.rb

Fixes #2949. Adds the ability to replace the image file of an existing post.
* Adds a "Replace Image" link in the options sidebar. Replacement is approvers up.
* A delayed job deletes the old files 3 days later. This gives time for recovery in case of mistakes.
* A mod action is logged containing all the old file metadata, to track what exactly changed.
Some corner cases are not handled yet and so are disallowed:
* Replacing posts that have notes is disallowed. Notes need to be rescaled to the new image dimensions.
* Replacing posts hosted on S3 is disallowed. There needs to be a way to delete S3 hosted files.
* Replacing ugoiras is disallowed. The old frame data will need to be replaced.

Fix #2949: Sample image replacement ability

---

app/controllers/comments_controller.rb
app/controllers/forum_topics_controller.rb
app/views/comments/index.atom.builder
app/views/comments/index_by_comment.html.erb
app/views/comments/index_by_post.html.erb
app/views/forum_topics/index.atom.builder
app/views/forum_topics/index.html.erb
app/views/forum_topics/show.atom.builder
app/views/forum_topics/show.html.erb
app/views/static/site_map.html.erb
app/views/users/show.html.erb
test/functional/comments_controller_test.rb
test/functional/forum_topics_controller_test.rb

Fixes #3036. Adds the following:
* Adds `/comments.atom`, `/forum_topics.atom`, and `/forum_topics/1234.atom`.
* Adds RSS feed links in the site map.
* Adds feed discovery links to `/comments` and `/forum_topics`.
* Adds feed discovery links on `/users/1234` for tracking new comments on your uploads, and for tracking new comments on posts you've commented on.

Fix #3036: Add Additional ATOM Feeds (forum_posts, comments)

---

app/assets/javascripts/uploads.js
app/views/uploads/new.html.erb

#3038 made the commentary box always present on the uploads page, but some non-bookmarklet uploaders complained about mistaking it for the tags box. This:
* adds a show/hide toggle button to the commentary.
* hides the commentary box by default.
* shows the commentary box when the source autofills it in.

Add commentary toggle button on uploads page.

---

app/logical/sources/strategies/pixiv.rb

Fixes #3046. The problem was that translated tags expects `tags` to be an array of `[tag_name, search_link]` pairs, not an array of `[tag_name]`.

Fix #3046: Server Only Grabbing/Using First Character of Pixiv Tags/Tools

---

app/controllers/forum_topics_controller.rb
app/models/forum_topic.rb
test/functional/forum_topics_controller_test.rb

Visiting `/forum_topics/1234.json` records a forum topic visit. But simply performing an API request shouldn't mark a thread as read. This makes it so that visits are only recorded for HTML requests.

Don't record forum topic visits for API requests.

---

app/models/user_name_change_request.rb
test/factories/user_name_change_request.rb
test/unit/user_name_change_request_test.rb

Provence reported that when attempting to change his name from `provence.` to `Provence`, it was instead changed to `provence`. The cause is the `desired_name` being normalized to lowercase, which we don't want.

Fix username changes forcing new name to lowercase.

---

app/logical/daily_maintenance.rb

Currently delayed jobs are pruned after one week. But replacing a post spawns a file deletion job that runs in 30 days. This increases the job pruning threshold to 45 days to avoid deleting these jobs.

Avoid pruning post replacement delayed jobs.

---

config/danbooru_default_config.rb

Fixes #3051. People outside Danbooru are unlikely to need this and it requires additional configuration to work, so disable it by default.

Fix #3051: disable S3 proxy by default.

---

app/logical/sources/strategies/pixiv.rb

Fixes #3054. The problem was that `get_profile_from_page` returns a pair, `[artist_name, profile_url]`. Switch to using the API instead, since we're already using it for everything else.

Fix #3054: Artist link broken on Post Upload page

---

app/controllers/moderator/post/posts_controller.rb
app/controllers/post_replacements_controller.rb
app/models/post.rb
app/models/post_replacement.rb
app/views/moderator/post/posts/replace.html.erb
app/views/post_replacements/_new.html.erb
app/views/post_replacements/new.html.erb
app/views/posts/partials/show/_options.html.erb
app/views/posts/show.html.erb
config/routes.rb
test/factories/post_replacement.rb
test/functional/post_replacements_controller_test.rb

Adds a basic controller for post replacements. The create action is moved from the `moderator/post/posts` controller to here. The index action doesn't have a view, but it does provide API access to replacements at least.
API endpoints added:
* `POST /post_replacements.json`
* `GET /post_replacements.json`
* `GET /posts/1234/replacements.json`

Add post replacements controller.

---

app/controllers/artists_controller.rb
app/models/artist.rb

Problem: autocomplete on the `/artists` page is slow. The cause is that `/artists.json` includes the `domains` list for each artist, which is slow to calculate.
This changes it so that `domains` is only returned by `/artists/1234.json`, not `/artists.json`. We do the same thing with `/users/1234.json` for certain fields that are too heavy to calculate for `/users.json`.

Don't return `domains` in /artists.json.

---

app/logical/sources/strategies/pixiv.rb
test/functional/artists_controller_test.rb
test/unit/artist_test.rb
test/unit/artist_url_test.rb

Fixes #3048. Normalizes Pixiv URLs to `http://www.pixiv.net/member.php?id=#{id}/` instead of `http://img.pixiv.net/img/#{moniker}/`.

Fix #3048: Artist Lookup Failing Due to Changing Usernames

---

app/controllers/moderator/post/posts_controller.rb
app/logical/post_pruner.rb
app/models/post.rb
app/models/post_flag.rb
test/unit/post_test.rb

https://danbooru.donmai.us/forum_topics/9127?page=185#forum_post_131440
The three day flagging cooldown prevents flagged posts from being manually deleted. This does two things:
* Makes `delete!` call `flag!` itself, instead of making the caller flag the post beforehand.
* Makes all deletions (automatic or manual) ignore any flagging rate limits.

Fix flagging cooldown preventing manual deletions.

---

app/models/post_flag.rb
test/unit/post_flag_test.rb
test/unit/post_test.rb

Discussion: https://danbooru.donmai.us/forum_topics/13177?page=25#forum_post_131285
Disallows flagging pending posts. This was previous attempted in #1327, but it was reverted due to it preventing pending posts from being deleted. But #3063 ensured that deletions always set the `is_deletion` flag, which lets us ignore this validation when we're deleting posts.

Disallow flagging pending posts.

---

app/controllers/comments_controller.rb
app/logical/post_query_builder.rb
db/migrate/20170519204506_fix_last_noted_at_index_on_posts.rb
db/structure.sql

Fixes #3000.
* Adds back the `posts.id` secondary sort for unindexed metatags where it doesn't hurt performance anyway.
* Redefines the `last_noted_at` and `last_commented_bumped_at` indexes to be `DESC NULLS LAST` so that `order:note` and `order:comment_bumped` use these indexes. Currently the indexes default to `ASC NULLS LAST`, which isn't compatible with the queries we do.

Fix #3000: order: metatags aren't indexed.

---

app/controllers/forum_topics_controller.rb

Fix #3069: Reverse forum post order for forum topic Atom feed

---

app/assets/stylesheets/specific/posts.scss
app/helpers/application_helper.rb
app/logical/anonymous_user.rb
app/views/layouts/default.html.erb

Fixes #3073. Adds `data-user-is-<role>` data attributes to the `<body>` element. This allows one to use CSS to show/hide page elements based on the current user's permissions.

Fix #3073: Add attribute "data-is-moderator" to the <body> element.

---

app/models/ban.rb
app/models/dmail.rb
test/unit/dmail_test.rb

Fixes a bug with dmail title search not being correctly case-insensitive.
EDIT: also fixes a similar bug when searching ban reasons.

Fix case sensitivity bug in dmail title search.

---

app/logical/post_query_builder.rb

Fixes #672. Ensures that the `date:` and `age:` metatags use the `created_at` index. See the comments on #672 for further discussion.

Fix date:, age: metatags to use the index. (fix #672).

---

app/models/artist_commentary.rb
app/models/artist_version.rb
app/models/forum_topic.rb
app/models/note.rb
app/models/note_version.rb
app/models/pool.rb
app/models/pool_archive.rb
app/models/post_appeal.rb
app/models/post_archive.rb
app/models/post_flag.rb

This allows giving comma-separated lists of IDs to `search[*_id]` params in a number of places where it currently isn't possible.

Allow search[*_id] params to accept lists of ids in more places

---

app/controllers/bulk_update_requests_controller.rb
app/models/bulk_update_request.rb
app/views/bulk_update_requests/_search.html.erb
app/views/bulk_update_requests/index.html.erb
test/unit/bulk_update_request_test.rb

Adds a basic search form to the [/bulk_update_requests](https://danbooru.donmai.us/bulk_update_requests) page. The added search fields are Creator, Approver, Status, and Order. Also adds `search[forum_topic_id]` and `search[forum_post_id]`, which aren't in the form but are accessible for the API.

Add search form to /bulk_update_requests.

---

app/logical/sources/site.rb
app/models/wiki_page.rb
app/views/wiki_pages/search.html.erb
test/unit/wiki_page_test.rb

Fixes #3070. Allows using `*` wildcards when searching wiki pages by "other names".
The way that other names are stored as a string of space-separated words makes the query somewhat awkward. It also prevents it from being indexed. However, the size of the wiki pages table is small enough that the search isn't too slow.

Fix #3070: add wildcard support to wiki "other names" search.

---

app/logical/post_query_builder.rb
app/models/post.rb
db/migrate/20170526183928_change_source_to_non_null_on_posts.rb
db/structure.sql
test/unit/post_test.rb

Fixes #3090 by enforcing blank sources to be the empty string instead of NULL.

Posts: redefine source column to be non-NULL (fixes #3090).

---

app/logical/related_tag_calculator.rb
app/models/post.rb

`RelatedTagCalculator#calculate_from_sample` is called when clicking the General / Artist / Copyright / Characters buttons during tag editing. Currently it's slow because it counts up the tags in ruby, and because it makes repeated calls to memcache in the inner loop when filtering tags by category.
This changes it to do the counting and filtering entirely in SQL using a GROUP BY tag / COUNT(*) aggregation. For most tags calculating the related tags takes 200-250ms with a sample size of 300. This also makes it more feasible to increase the sample size.

Optimize related tags calculation

---

app/models/pool.rb
app/models/post.rb

Fixes #3091. Adding a post id to a pool's `post_ids` string is non-atomic, hence the pool should be locked to avoid a race condition. Adding a pool to a post's `pool_string` is also non-atomic, hence the post should be locked as well.

Fix #3091: Inconsistency between pool_string and pool.post_ids.

---

app/logical/moderator/tag_batch_change.rb

https://danbooru.donmai.us/forum_topics/9127?page=187#forum_post_131849:
> Is there a reason why there are so many mass update actions on the mod action page:
http://danbooru.donmai.us/mod_actions
> Is not the first tag I observe that from. Is is really wanted that it creates so many listings? Because it gets kinda confusing if you read the same entry over and over again.
This fixes two problems:
* Mass updates fail when trying to move saved searches because `query_array` doesn't exist (I removed it in 0b63dd32d1747fcbfce3f54eb4ead45269f37e24 but forgot to update this callsite).
* When the mass update delayed job fails, it tries again later but it generates a new modaction each time it tries again.

Mass updates: fix exception when moving saved searches.

---

config/initializers/core_extensions.rb
test/unit/string_test.rb
test/unit/user_test.rb

Related to #3070. This allows escaping `*` wildcard characters in searches. This makes it possible to search for things that may contain `*` characters: artist other names, usernames, pool names, note bodies, etc.
These are the escaping rules:
* `*` - wildcard
* `\*` - literal `*`
* `\\` - literal `\`
In other words: to search for strings containing a `*`, say `*\**`. For strings containing a `\`, say `*\\*`.

Allow backslash escaping wildcards in wildcard searches.

---

app/helpers/artist_versions_helper.rb
app/helpers/post_versions_helper.rb

Fixes missing spaces between tags on [/post_versions](https://danbooru.donmai.us/post_versions).
https://danbooru.donmai.us/forum_topics/9127?page=188#forum_post_132042:
> When viewing tag history in individual posts all non added tags at last edit appears without any spaces making it looks really awkward, at least Firefox add in line breaks here and there while Explorer just gives me a long string of text. Global changes page seems to be affected too.

Fix missing spaces between tags on /post_versions

---

app/assets/javascripts/posts.js

Partial fix for #3074.  It resizes images automatically if it detects a mobile layout.  It currently does nothing for Anonymous since they don't get a resize link.

Resize images for mobile layout

---

app/assets/javascripts/posts.js
app/assets/javascripts/shortcuts.js
app/controllers/moderator/post/approvals_controller.rb
app/views/moderator/post/approvals/create.js.erb
app/views/moderator/post/approvals/create.json.erb
app/views/posts/partials/show/_notices.html.erb

Fixes #3099:
* Fixes error in the `shift+o` shortcut that prevented it from showing the "post was approved" notice.
* Fixes error in the approve action in the mode menu that prevented it from showing the "post was approved" notice, and from removing the blue border.
* Fixes the `shift+o` shortcut to hide the flag/appeal notice bars.

Fix #3099: NilClass error for approval API request

---

app/assets/javascripts/post_mode_menu.js

Bug: when using edit mode from the mode menu, each time you click a thumbnail the height of the tag edit box increases by 4px. This causes the edit box to constantly grow as you click thumbnails.
This is due to `scrollHeight` including vertical padding. The fix is to ignore the padding.

Fix height of tag edit box in edit mode.

---

app/controllers/forum_topics_controller.rb
app/models/forum_topic.rb
test/functional/forum_topics_controller_test.rb

Bug: [/forum_topics.json](https://danbooru.donmai.us/forum_topics.json) and [/forum_topics.atom](https://danbooru.donmai.us/forum_topics.atom) always return stickied topics first.
This fixes topic listing to only sticky topics in the HTML response, not API responses.

Forum topics: don't list sticky topics first in json/atom responses.

---

app/logical/downloads/rewrite_strategies/art_station.rb
app/logical/sources/strategies/art_station.rb
test/unit/downloads/art_station_test.rb
test/unit/sources/art_station_test.rb

Fixes #3108. Adds support for https://dantewontdie.artstation.com/projects/YZK5q style urls during source fetching and download rewriting.

Fix #3108: support https://$artist.artstation.com/projects/$id urls

---

app/logical/nico_seiga_api_client.rb
test/unit/sources/nico_seiga_test.rb

Fixes #3117. For some reason `doc.response.image.description` returns nil even though the description element exists. Switch to `Hash.from_xml` to avoid this.

Fix #3117: Nicoseiga handler grabbing wrong commentary source

---

app/assets/javascripts/uploads.js
app/logical/sources/site.rb
app/logical/sources/strategies/base.rb
test/unit/sources/pixiv_test.rb

Bug: The `"Gallery. Tags may not apply to all images."` warning doesn't appear when uploading from non-Pixiv galleries, namely Twitter and ArtStation.
The problem is that the check relies on a `page_count` field that is only set for Pixiv. The fix is to return the `image_urls` list and check that instead to see if it's a single image or a gallery.
Test case: https://danbooru.donmai.us/uploads/new?ref=https%3A%2F%2Ftwitter.com%2Fpon0737%2Fstatus%2F866610987192811520&url=http%3A%2F%2Fpbs.twimg.com%2Fmedia%2FDAbSAUAWsAIhy35.jpg%3Aorig

Fix gallery warning for non-Pixiv galleries.

---

app/assets/stylesheets/specific/posts.scss
app/views/artist_commentaries/index.html.erb
app/views/comments/index_by_comment.html.erb
app/views/moderator/dashboards/show.html.erb
app/views/posts/partials/common/_inline_blacklist.html.erb
app/views/users/show.html.erb

Fixes #3121. Adds blacklist controls to these pages:
* /comments?group_by=comment
* /users/$ID
* /artist_commentaries
* /moderator/dashboard

Fix #3121: No Blacklist Box on the various controllers

---

app/logical/downloads/file.rb
app/logical/sources/site.rb
app/logical/sources/strategies/art_station.rb
app/models/post.rb
test/unit/sources/art_station_test.rb

A few fixes for ArtStation:
* Recognize <http://www.artstation.com/artwork/cody-from-sf> style URLs.
* Change source from image URL to HTML page URL after upload.
* Include only images in `image_urls`. ArtStation posts can contain Youtube videos and 3D models ([example](https://www.artstation.com/artwork/1Grqo)), but those should be ignored by the batch upload bookmarklet.
* Normalize sources to <https://www.artstation.com/artwork/XPGOD> for the sidebar.
* Fix `Fetch source data` to work when uploading from a direct image URL ([example](https://danbooru.donmai.us/uploads/new?url=https://cdna.artstation.com/p/assets/images/images/006/029/978/large/amama-l-z.jpg&ref=https://www.artstation.com/artwork/4BWW2)).

Multiple ArtStation fixes

---

db/migrate/20170608043651_add_pending_flagged_indexes_to_posts.rb
db/structure.sql

Problem: the modqueue loads slowly. This is because it queries for pending or flagged posts, but these columns are unindexed.
This adds partial indexes on `is_flagged` and `is_pending`, which speeds up the modqueue as well as `status:pending` and `status:flagged` searches. This would add more indexes to the posts table, but since these are partial indexes the cost should be minimal.

Add partial indexes on is_pending, is_flagged.

---

app/models/post_replacement.rb
test/unit/post_replacement_test.rb

Allows replacing ugoira posts. Fixes #3133, which was caused by replacing a post with a ugoira but not saving the ugoira's frame data.

Fix #3133: Allow replacing ugoira posts

---

app/assets/javascripts/artist_commentaries.js
app/logical/sources/strategies/deviant_art.rb
test/unit/sources/deviantart_test.rb

Fixes an issue raised in [topic #14125](https://danbooru.donmai.us/forum_topics/14125). Currently we strip HTML from DeviantArt commentaries, but this tends to produce bad results that require manual cleanup.
This instead converts HTML into DText syntax. We recurse through the HTML and map HTML elements to their DText equivalents. For most elements there is a 1-to-1 mapping, except for `<img>` tags, where we just output the tooltip instead.
Test case: http://noizave.deviantart.com/art/test-post-please-ignore-685436408

Autoconvert DeviantArt commentary from HTML to DText

---

app/assets/javascripts/related_tag.js

Fixes #3139. Removes the `[open]` link to the right of the artist URL. Makes the URL itself into a link instead.

Fix #3139: XSS in Related Tags javascript.

---

app/logical/sources/strategies/deviant_art.rb
config/danbooru_default_config.rb
test/unit/sources/deviantart_test.rb

Fixes #3138. Logs in to DeviantArt so that we're able to fetch login-only images. This is the login flow:
* `GET https://www.deviantart.com/users/login` - get the CSRF tokens, `validate_key` and `validate_token`.
* `POST https://www.deviantart.com/users/login` - post the `username`, `password`, `validate_key`, and `validate_token`.
* Save the session cookies, `auth` and `userinfo`. There is a third cookie, `auth_secure`, but it doesn't seem to be needed. Login works without it.

Fix #3138: Support DeviantArt login-only works.

---

app/helpers/post_versions_helper.rb

Fixes this issue from https://danbooru.donmai.us/forum_topics/9127?page=188#forum_post_132424:
> In post changes history, added tags have line breaks in random places.
> See an example: http://i.imgur.com/1Ko9EpR.png
9bf85ee2b3aaeea071f6b2428c8b9017065bfb1f removed whitespace that was between the `<ins>`/`<del>` elements, but it turns out this whitespace is significant, as tags wordbreak differently without it.

Fix wordbreaks in tags on /post_versions

---

app/logical/related_tag_query.rb
app/models/wiki_page.rb
test/unit/related_tag_query_test.rb

Fixes #1608. The bug was that when using the `Related tags` button on an aliased tag, `/hm -> hatsune_miku` for example, we pulled wiki tags from the nonexistent `/hm` wiki instead of from the `hatsune_miku` wiki.

Fix #1608: Show wiki page of alias consequent for Related Tags

---

app/assets/javascripts/uploads.js

Fixes #1908. Makes `E` focus the tag edit box on the uploads page.

Fix #1908: Allow E shortcut to work on upload page.

---

app/models/post.rb
test/unit/post_replacement_test.rb

Bug: if a user replaces a post with another image, then replaces the post back to the original image, then the deletion job for the original image will still run. The will delete the original file, but that file is now in use again and should not be deleted.
@r888888888 this fix needs to be deployed soon because the first batch of deletion jobs will start going through in the next couple days.

Post replacements: don't delete files currently in use.

---

app/models/artist_commentary.rb
db/migrate/20170613200356_change_fields_to_non_null_on_artist_commentaries.rb
db/structure.sql
script/fixes/047_trim_artcomm_whitespace.rb
test/unit/artist_commentary_test.rb

Fixes #2174:
* Adds some commentary tests, since there aren't any currently.
* Migrates commentary fields to be non-nullable. Currently blank commentaries are either null or the empty string, which makes searching more complicated; this ensures they can only be the empty string.
* Trims whitespace from commentary fields on save.
* Adds a fix script to trim whitespace from existing commentaries. Commentaries can't be trimmed in place, they have to be resaved so that new commentary versions will be recorded. It may take 5-10 minutes to update all the affected commentaries (approx. ~16,000 on my machine).

Fix #2174: Trim whitespace from artist commentary

---

Gemfile
Gemfile.lock
app/models/post.rb
test/helpers/iqdb_test_helper.rb
test/test_helper.rb
test/unit/post_test.rb

Fixes #3156, plus a couple more bugs with expunging posts:
* Fixes `Post.delete_files` to skip the check that the files are still in use. We don't want this when the post is being expunged.
* Fixes the `delete_files` / `remove_iqdb_async` callbacks to run only after the transaction successfully commits. Testing this required adding the [test_after_commit](https://github.com/grosser/test_after_commit) gem to fix an issue with `after_commit` hooks not firing during testing.
* Fixes expunging posts not removing images from iqdb. There was a `File.exists?(preview_file_path)` check that always failed because the files were already deleted by this point. I don't know what the purpose of this check was, but it doesn't seem necessary.
Also removes an unused `update_iqdb` method.

Fix #3156: Expunging posts is broken

---

app/logical/post_query_builder.rb
app/models/tag.rb

This adds support for the following metatags:
* `-approver:any`
* `-approver:none`
* `-flagger:any`
* `-flagger:none`
* `-appealer:any`
* `-appealer:none`
* `-pool:any`
* `-pool:none`
* `-parent:any` (`-parent:none` was implemented already)
* multiple `-parent:<number>` metatags
I think the support for that has been rejected before, but I don't see any reason to do that; it's a thing that users might try in their search, and currently it will get them confusing results. Also, I'm working on making autocomplete for metatags more intelligent, and having `metatag` and `-metatag` support different sets of values is becoming a pain.

Add more support for negated existing metatags

---

app/logical/sources/strategies/twitter.rb
test/unit/sources/twitter_test.rb

Fixes #3162:
* Convert hashtags and mentions to DText links.
* Replace http://t.co URLs with the actual URL.
* Strip the http://t.co URL linking to the tweet itself.

Fix #3162: Twitter commentary links

---

app/views/static/bookmarklet.html.erb

Fixes #3159:
* Use HTTPS in the bookmarklet if the user is connected via HTTPS. Also use the same hostname the user is currently using (i.e., if they're using https://sonohara.donmai.us, the bookmarklet will use sonohara too).
* Fix a typo in the page id.
* Update the description to better explain what the bookmarklet does, why you should use it, and how to install it.

Fix #3159: Upload bookmarklet not provided using same protocol accessed page.

---

app/controllers/note_previews_controller.rb
app/logical/d_text.rb
app/logical/note_sanitizer.rb
app/views/notes/_note.html.erb
test/unit/note_sanitizer_test.rb

Improves a few things with sanitizing notes:
* Moves the sanitization code from `logical/d_text.rb` to `logical/note_sanitizer.rb`. Sanitizing notes doesn't really have anything to do with DText, so it seemed a little out of place there.
* Allows the `<rtc>`, `<sub>`, `<sup>`, `<hr>`, and `<wbr>` tags.
* Marks all links as `rel="nofollow"`.
* Allows all tags to use the `style` attribute. Currently only a few tags allow `style`, which makes translators resort to dummy wrapper `<span>`s in some cases. Also allows the `title` attribute, just because.
* Makes the list of allowed CSS properties explicit. Currently we use `Sanitize::Config::RELAXED`, but it was unclear to me what exactly that allowed.
* Adds some tests. Currently sanitization is untested.

Improve note sanitization

---

app/models/upload.rb
test/factories/upload.rb
test/unit/upload_test.rb

Fixes #3168. Converts nil sources on upload to the empty string.

Fix #3168: API upload can't handle unset source.

---

app/logical/pixiv_api_client.rb
app/logical/sources/strategies/pixiv.rb
test/unit/sources/pixiv_test.rb

Fixes #2458. Converts links inside Pixiv commentaries to DText in this manner:
* https://www.pixiv.net/member_illust.php?mode=medium&illust_id=1234
=> [pixiv #1234](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=1234) [»](https://danbooru.donmai.us/posts?tags=pixiv:1234)
=> `pixiv #1234 "»":[/posts?tags=pixiv:1234]`
* https://www.pixiv.net/member.php?id=1234
=> [user/1234](https://www.pixiv.net/member.php?id=1234) [»](https://danbooru.donmai.us/artists?search[url_matches]=https://www.pixiv.net/member.php?id=1234)
=> `"user/1234":[https://www.pixiv.net/member.php?id=1234] "»":[/artists?search[url_matches]=https://www.pixiv.net/member.php?id=1234]`
That is, it links to the post or user on Pixiv, as well as to a post or artist search on Danbooru.

Convert Pixiv commentaries to DText (fix #2458)

---

Gemfile
Gemfile.lock
app/logical/note_sanitizer.rb
config/danbooru_default_config.rb
test/unit/note_sanitizer_test.rb

Fixes #1911. Converts absolute links in notes (e.g. `http://sonohara.donmai.us/posts/1234`) to relative links (`/posts/1234`). This is so that users stay on the same domain and on HTTPS when following links inside notes.
Doing this required adding a `Danbooru.config.hostnames` config option listing all domain names that the site is known under.

Convert absolute links in notes to relative links (fix #1911)

---

app/logical/sources/strategies/twitter.rb
test/unit/sources/twitter_test.rb

Fixes #3171. Fetches translated tags for Twitter.

Fix #3171: Translate Twitter Hashtags to assist with tagging

---

app/logical/downloads/rewrite_strategies/base.rb
app/logical/downloads/rewrite_strategies/pawoo.rb
app/logical/pawoo_api_client.rb
app/logical/sources/strategies/pawoo.rb
app/models/artist.rb
config/danbooru_default_config.rb
test/unit/artist_test.rb
test/unit/sources/pawoo_test.rb

Several fixes for Pawoo. Should close out #2981.
* Fetch tags and commentary.
* Convert commentary to dtext.
* Rewrite `/small/` image URLs to `/original/`.
* Fix artist finder returning bogus results when no match is found.
* Fix status ID parser to get ID from the normalized URL. This fixes `Fetch source data` not working with the batch bookmarklet ([testcase](https://danbooru.donmai.us/uploads/batch?url=https%3A%2F%2Fpawoo.net%2F%40evazion%2F19451018)).

Multiple Pawoo fixes (closes #2981)

---

app/logical/sources/strategies/nijie.rb
app/models/artist.rb
test/unit/artist_test.rb
test/unit/sources/nijie_test.rb

Fixes #3176. Fetches commentary and adds batch bookmarklet support. Also fixes artist finder returning bogus results when there are no matches (cf #2696).

Fix #3176 - Nijie: fetch commentary + support batch bookmarklet

---

app/assets/stylesheets/common/simple_form.scss
app/controllers/post_replacements_controller.rb
app/helpers/application_helper.rb
app/models/post_replacement.rb
app/views/post_replacements/_new.html.erb
app/views/post_replacements/index.html.erb
app/views/posts/show.html.erb
app/views/static/site_map.html.erb
config/routes.rb
test/unit/post_replacement_test.rb

A few improvements for post replacements:
* Adds a basic `/post_replacements` view.
* Adds ability to upload a replacement as a file from your computer.
* Adds a `Final Source` option to the replacement dialog. If present, the post's source field will be set to this value after replacement. This makes changing the source field back to the HTML page after replacement easier.
* Fixes a bug with `/post_replacements?search[creator_name]` not working.
* Fixes the awkward size of the source field in the replacement dialog (and incidentally fixes the size of the reason field in the flag dialog).

Post replacements: Add view; allow replacing from uploaded file.

---

app/logical/downloads/rewrite_strategies/tumblr.rb
test/helpers/download_helper.rb
test/test_helper.rb
test/unit/downloads/pixiv_test.rb
test/unit/downloads/tumblr_test.rb

Fixes #3178. Rewrites Tumblr URLs in this manner:
```
http://40.media.tumblr.com/d8c6d49785c0842ee31ff26c010b7445/tumblr_naypopLln51tkufhoo2_500.png
=> http://data.tumblr.com/d8c6d49785c0842ee31ff26c010b7445/tumblr_naypopLln51tkufhoo2_raw.png
```
Some URLs don't have a `_raw` version, so we test `_raw, _1280, _540, _500` in turn until we find the first one that exists. Tumblr has a few slight variations on the URL format above (see the comments and tests), but that's the basic idea.

Fix #3178: Rewrite Tumblr image samples

---

Gemfile
Gemfile.lock
app/logical/downloads/file.rb
app/logical/downloads/rewrite_strategies/tumblr.rb
app/logical/sources/strategies/tumblr.rb
app/logical/tumblr_api_client.rb
config/danbooru_default_config.rb
test/unit/downloads/tumblr_test.rb
test/unit/sources/tumblr_test.rb

Adds basic upload support for Tumblr (#3184):
* Fetches tags.
* Fetches commentary.
* Adds batch bookmarklet support.
* Allows uploading from the HTML page using the bookmarklet.
This uses the Tumblr API, which is documented here: https://www.tumblr.com/docs/en/api/v2#posts. You'll need to register an app at https://www.tumblr.com/oauth/register to get an OAuth consumer key.
Tumblr has an official client lib at https://github.com/tumblr/tumblr_client, but it's unmaintained and the version of Faraday that it depends on conflicts with the version required by the Twitter gem. So instead I wrapped the API with HTTParty, which turned out quite simple.
One complication with Tumblr is that there are several types of posts - photo posts, text posts, video posts, plus some others less relevant to …

Add Tumblr integration (#3184)

---

app/models/artist_commentary_version.rb
app/views/artist_commentary_versions/index.html.erb

Fixes #3187 for `/artist_commentary_versions`:
* Formats commentaries in `/artist_commentary_versions` as DText.
* Also adds post thumbnails to `/artist_commentary_versions`. Thumbnails aren't shown when viewing the history of a single post, as that would be redundant.

Fix #3187: DText is not enabled on certain views 

---

app/assets/stylesheets/specific/posts.scss
app/controllers/post_replacements_controller.rb
app/models/post_replacement.rb
app/views/post_replacements/_new.html.erb
config/danbooru_default_config.rb
test/unit/post_replacement_test.rb

* Approvers frequently need to remove certain tags (`replaceme`, `image_sample`, `jpeg_artifacts`, etc) after replacing a post. This adds a `Tags` field to the post replacement dialog, prefilled with a list of such tags to be removed from the post.
* When the replacement comes from an uploaded file, record this as `file://#{filename}` in the replacement url.
* When the replacement comes from an URL, record the final URL used by the upload process instead of the initial URL given by the user. These differ if the upload process rewrites the URL from sample to full size.

Post replacements: streamline removing tags; fix replacement url.

---

app/assets/stylesheets/specific/uploads.scss
app/views/uploads/batch.html.erb

Attempt at #3194. As mentioned in #3194, this loads the full image, which will be slow if the gallery contains many large images.
Screenshot:

#3194: Display thumbnails on batch upload page

---

app/logical/d_text.rb
app/logical/sources/strategies/deviant_art.rb
app/logical/sources/strategies/nijie.rb
app/logical/sources/strategies/pawoo.rb
app/logical/sources/strategies/tumblr.rb
test/unit/sources/deviantart_test.rb
test/unit/sources/nijie_test.rb
test/unit/sources/tumblr_test.rb

#3184:
* Factors out the HTML-to-DText conversion code from the Pawoo/Nijie/DeviantArt strategies to `DText.from_html`.
* Adjusts some minor whitespace issues along the way (strips extraneous whitespace, adds newlines between block elements).
* Finally converts Tumblr artist commentaries to DText.

Tumblr: convert artist commentaries from HTML to DText (#3184)

---

app/models/tag_implication.rb
test/unit/bulk_update_request_test.rb
test/unit/tag_implication_test.rb

Fixes #3200. Disallows transitive implications: if `a -> b -> c` already exists, don't allow `a -> c`.
Caveat: if `b -> c` already exists, and we make a BUR for `a -> b` and `a -> c`, then the BUR validates even though `a -> c` is redundant. It only fails when the BUR is approved. This is because the BUR doesn't actually create the implications until the BUR is approved, so the redundant implication isn't seen yet.

Fix #3200: Disallow creation of superfluous implications

---

app/controllers/artists_controller.rb
app/controllers/bulk_update_requests_controller.rb
app/controllers/dmails_controller.rb
app/controllers/favorites_controller.rb
app/controllers/forum_posts_controller.rb
app/controllers/iqdb_queries_controller.rb
app/controllers/maintenance/user/api_keys_controller.rb
app/controllers/maintenance/user/dmail_filters_controller.rb
app/controllers/notes_controller.rb
app/controllers/reports_controller.rb
app/controllers/saved_searches_controller.rb
app/controllers/uploads_controller.rb
app/controllers/users_controller.rb
app/controllers/wiki_pages_controller.rb
app/views/artists/_show.html.erb
app/views/artists/show.html.erb
app/views/artists/show_or_new.html.erb
test/functional/artists_controller_test.rb
test/functional/dmails_controller_test.rb
test/functional/users_controller_test.rb

Fixes #3203:
* Adds an `/artists/show_or_new` page that displays a "Artist does not exist. Create new artist entry." message when the artist doesn't exist yet. This makes  `/artists/show_or_new` work the same way that `/wiki_pages/show_or_new` does.
* Allows banned users to edit their account settings, read/delete their dmails, and manage their saved searches, dmail filters, and API key.
* Allows anonymous users to access various other pages; see commits.

Fix #3203: Overly restrictive permissions

---

app/logical/pixiv_api_client.rb
app/logical/sources/site.rb
app/logical/sources/strategies/base.rb
app/logical/sources/strategies/pixiv.rb
app/models/tag.rb
test/unit/sources/pixiv_test.rb

Fixes #3208:
* Only suggest the Danbooru tag with the same name if there is no matching wiki other name. Example: if we have the Pixiv tag `Fate` and the Danbooru tag `fate_(series)` with other name `fate`, suggest that, not the Danbooru tag `fate`.
* Don't suggest tags that are empty or whose wiki is deleted.
* Only split tags on `/` if there are no other matches, and only do this for Pixiv.
* For Pixiv, only include traditional media tags in the tag list, not digital media (Photoshop, SAI, etc).
* Add some tests.

Fix #3208: Fix translated tag suggestions for Pixiv.

---

app/models/key_value.rb
db/migrate/20170709190409_drop_key_values.rb
db/structure.sql

Removes this unused KeyValue model and drops the table. AFAICT this hasn't been used since e2c2a83.

Remove unused KeyValue model (#3206).

---

app/assets/javascripts/autocomplete.js
app/assets/javascripts/posts.js
app/assets/javascripts/saved_searches.js
app/controllers/saved_searches_controller.rb
app/models/saved_search.rb

Fixes #3214:
* Autocomplete the `search:<label>` metatag.
* Make label autocompletion do a prefix match instead of a substring match. Example: `search:ar` matches `artists`, not `characters`. This is how tags and most other things are autocompleted.
* Make the saved search dialog trigger autocomplete after typing the first letter of the label. This threshold was increased to 2 in da06bee0ab19c683a278a787e9c87b78d7ec3993 but I don't see why, the endpoint isn't any slower for one character.

Fix #3214: Add autocomplete for saved searches.

---

app/controllers/uploads_controller.rb
app/logical/downloads/file.rb
app/logical/downloads/rewrite_strategies/art_station.rb
app/logical/downloads/rewrite_strategies/base.rb
app/logical/image_proxy.rb
app/logical/pixiv_api_client.rb
app/logical/sources/strategies/deviant_art.rb
config/danbooru_default_config.rb
test/helpers/download_helper.rb

Fixes #3224. The bug was that dA requires a valid user agent to be sent or it will return a 403. 
This fixes it by adding a `Danbooru.config.http_headers` config option that configures the default http headers sent with outgoing requests. Various other places are also refactored to use this option instead of setting the user agent in each place manually.

Fix #3224: 403 Forbidden when logging in to DeviantArt.

---

app/logical/note_sanitizer.rb
test/unit/note_sanitizer_test.rb

Fixes #3225. Swallows the `InvalidURIError` exception that Addressable raises when it parses a malformed url.

Fix #3225: Exception in NoteSanitizer#relativize_links.

---

app/controllers/users_controller.rb

Currently after saving your account settings you are redirected back to your profile page. This is annoying when you're working on custom CSS and you have to go back to the settings page every time you make a change. This would instead keep you on the settings page after saving your settings.

Redirect back to settings page after saving account settings.

---

app/models/pool.rb
app/models/post.rb
app/presenters/post_presenter.rb
app/views/moderator/post/queues/_post.html.erb
app/views/posts/partials/show/_nav_links.html.erb
test/unit/post_test.rb

Fixes #3229:
* Wrap `expunge!` in a transaction.
* Destroy post replacement records on expunge.
* Fix `Post#pools` to include deleted pools so that `Post#remove_from_all_pools` truly does remove posts from all pools. Fix `Post#remove_pool!` as well so that posts can be removed from deleted pools (cf #1109).
* Fix `update_children_on_destroy` to properly run callbacks when reparenting children. This ensures that the `has_children` flag is set on the new parent and new post versions are recorded for reparented posts.
* Try to simplify the `update_has_children_flag` logic while we're at it.

Fix #3229: Post expungement bugs

---

app/logical/post_search_context.rb
app/presenters/post_presenter.rb
app/views/posts/partials/show/_nav_links.html.erb
app/views/posts/partials/show/_search_seq.html.erb

Fixes #1156. Makes the sequential post navigator default to a `status:any` search when the search is blank.

Fix #1156: Allow sequential search navigator to work without a search.

---

app/controllers/legacy_controller.rb
app/models/post.rb
app/presenters/post_presenter.rb
app/views/legacy/posts.json.erb
app/views/legacy/posts.xml.erb

Related to #3237. Fixes hidden attributes being exposed in the data attributes of the `#image-container` element, and in the `/post/index.xml` legacy API.
The Better Better Booru userscript exploits these loopholes to make censored posts visible to unprivileged users.

Fix censored post exposures in data attributes / legacy API (#3237)

---

app/models/post.rb
app/models/post_replacement.rb
app/models/upload.rb
test/unit/post_replacement_test.rb

Fixes #3235:
* Does an md5 check to prevent deleting any files that belong to a post.
* Allows replacing a post with the same file that it's already using. This allows one to restore the images for posts with missing or corrupted images in one step.

Fix #3235: Replacements deleting files currently in use.

---

app/logical/post_query_builder.rb
test/unit/post_test.rb

Fixes #2344. Fixes searches so that when the `Deleted post filter` option is on, deleted posts are properly filtered from `-status:pending`, `-status:flagged`, `-status:banned`, and `status:banned` searches.

Fix #2344: Negating status metatag breaks deleted post filter.

---

app/controllers/artists_controller.rb
app/models/artist.rb
app/models/artist_url.rb
test/unit/artist_test.rb

Fixes #2346. Validates that URLs in artist entries are well-formed. This doesn't attempt to automatically fix bad URLs as suggested in #2346. Instead it just returns a validation error and leaves it up to the user to fix their mistake.

Fix #2346: Artist URLs: auto add 'http', remove non-links

---

app/controllers/tag_aliases_controller.rb
app/controllers/tag_implications_controller.rb
app/models/tag_alias.rb
app/models/tag_implication.rb
app/models/tag_relationship.rb
app/views/tag_aliases/_listing.html.erb
app/views/tag_aliases/index.html.erb
app/views/tag_implications/index.html.erb

Fixes #2633. Adds options for filtering `/tag_aliases` and `/tag_implications` by status and by tag type, and for ordering results.
The code for searching aliases and implications is the same, so this factors it out (along with some other shared code) into a `TagRelationship` superclass that aliases and implications both inherit from.

Fix #2633: Search for status:active at tag_aliases and tag_implications

---

app/models/artist_commentary.rb
app/views/artist_commentaries/search.html.erb

Fixes #2502. Adds a `Deleted?` option to the `/artist_commentaries` search form. Choosing "no" filters empty commentaries out of the results.

Fix #2502: Exclude empty commentary from searches.

---

app/logical/d_text.rb
app/logical/mentionable.rb
app/models/comment.rb
app/models/forum_post.rb
test/unit/comment_test.rb

Fixes #2736. The bug was that mentions weren't processed when added during an edit. This fixes it so that mentions added by an edit will get processed.

Fix #2736: Comment mention dmail didn't go through

---

app/models/user.rb
app/presenters/user_presenter.rb
app/views/uploads/new.html.erb
app/views/users/_statistics.html.erb

Fixes #3262:
* Allow mousing over the upload limit on profile pages to show the full formula for the upload limit calculation. In particular, show how the upload limit multiplier is derived from the deletion confidence.
* Makes it so that you can hover over your used upload slots to see the time remaining until your next available upload.
See screenshots below:

Fix #3262: Add time remaining for upload limits on user profiles

---

app/controllers/pools_controller.rb
app/models/pool.rb
test/factories/pool.rb
test/unit/pool_test.rb

Fixes #3263:
* Strips leading / trailing underscores from pool names.
* Strips consecutive underscores (`___`) inside pool names.
* Disallows blank pool names.
* Disallows asterisks (this conflicts with wildcards in `pool:touhou*` searches).
* Disallows numeric-only names (this is ambiguous in `pool:1234` searches).

Fix #3263: Remove leading whitespace on pool names

---

script/install/nginx.danbooru.conf

On Ubuntu 16.04 LTS, the break in the config causes nginx to fail to restart

update nginx config

---

app/logical/sources/strategies/deviant_art.rb

This should fix #3260.
Unlike this projects, all other DA scrapers I found ([1][0], [2][1]) require that both
`auth` and `auth_secure` are set.
While the current approach, for some reason, seems to have worked fine in
the past, it has stopped functioning on some systems, sometimes
permanently (apparently sometimes only temporarily).
I don't have the means to find out the reason behind that, since all
configurations I've tried (mobile, VPN, and regular connection +
4 seperate accounts) resulted in me being effectively logged out and
unable to view mature works after deleting the `auth_secure` cookie.
The `if auth_cookie` part might not actually be necessary, its only
purpose is to prevent unintended breakage due to lack of information
on my part.
[0]: …

Keep auth_secure cookie from deviantart

---

app/assets/javascripts/posts.js

This issue was first brought up on the [Danbooru forums](http://danbooru.donmai.us/forum_topics/14489).
Basically, the user reported that the images were appearing at their full size instead of being resized for the mobile screen.  I investigated it with my Samsung Galaxy S6 using Chrome and confirmed the above issue.
Using the developer's console for Chrome on my desktop PC using the above mobile layout, I checked the variables and discovered that the culprit was the `window.innerWidth` variable.  It was being set to the window size to include the width of the full-size image.  I then checked Firefox's mobile layout using the same tools and saw that the `window.innerWidth` was being set to the actual screen size as it had previously done for both browsers.  So Chrome might have changed …

Fix window resizing issue in mobile mode

---

INSTALL.debian

Starting in Debian 9.0, libssl1.0-dev is required for the install step of building Ruby 2.3.1.

Fixing dependencies for newer releases of Debian (>=9.0)

---

app/assets/stylesheets/specific/z_responsive.scss
app/views/posts/index.html.erb

I brought up the idea on the [Danbooru forum](http://danbooru.donmai.us/forum_topics/14535) about having an extra search box at the top of the post index due to the necessity to always having to scroll through ~50 rows of images to reach the search box.
@kittey however brought up the useful suggestion to just have a link at the top which redirects to the search box, which is a good compromise and relatively simple to code.
So the following presents a link next to the **Post**, **Wiki**, **Artist**, etc links at the top of the image content when in the responsive view.

Added searchbox link to responsive view

---

app/assets/javascripts/autocomplete.js

The [jQuery Web Storage API](https://plugins.jquery.com/storageapi/) uses the period '.' as a special character when saving and retrieving data.  It's telling the API that whatever is left of the period is the entry name, and whatever is to the right of it is an attribute of that entry.
So when a user types in '.', the program does a lookup in the "" entry with the "" attribute, which doesn't exist so the program throws an exception.  Basically, anything with a period is currently unstorable.
The following code therefore does a substitution of all periods with the Unicode character \uFFFF which is a [guaranteed non-character](http://www.fileformat.info/info/unicode/char/ffff/index.htm).

Substitute nonusable period in local storage saves

---

app/assets/javascripts/autocomplete.js

This issue was brought to light as a result from the userscript I developed in [topic #14474](http://danbooru.donmai.us/forum_topics/14474).  Basically, the number of keys in local storage is not a good metric to measure how full the current storage is.
A userscript could store thousands of smaller values, which would trip an unnecessary pruning.  My userscript falls into this category, however at 4000 entries, it only entails around 210K characters being stored at around 50 characters per item.
Conversely, a userscript could store one massive value in local storage, but would not trip necessary pruning which could break the autocomplete.
The average Danbooru autocomplete stored item was observed to be around 600 characters (sampling around 1750 stored items).  With the current item limit …

Use current local storage size for pruning calculations

---

app/assets/javascripts/related_tag.js

The fix on #3333 does work, however it uses the focus() function to accomplish this which switches focus back to the tag box. This works mostly fine on a large display, however on smaller displays, this causes the user to lose their view on the tags they're attempting to add. For tags on the bottom of the list, this necessitates scrolling back down after each tag add.
After experimenting, I found that setting a timeout on only the portion that updates the cursor value is sufficient to have it survive whatever Chrome is doing to clobber the cursor position normally. Using that instead, the cursor still gets updated however the focus isn't forced back to the tag box each time.

Use timeout on tag box cursor calculation

---

app/models/upload.rb

Following the discussion [in this thread](http://danbooru.donmai.us/forum_topics/14593), this modifies the behavior of the upload validator to permit admins to bypass the length check on video. Because admins tend to be smart, and not stupid, I doubt that this feature will be abused.
This is more of a stop gap measure. @BrokenEagle's [solution](http://danbooru.donmai.us/forum_posts/137906) is far better suited towards a long term system, but I think it's unnecessary until exceptions to the upload limit start becoming a regularly requested thing.
Finally, I'd like to point out that [this comment](http://danbooru.donmai.us/forum_posts/137852) noted that flash animations don't have a length limit.
Edit: It's worth noting this solution really only solves my problem if at least one active …

Skip validation of video duration if user is admin

---

app/helpers/post_flags_helper.rb
app/logical/anonymous_user.rb
app/logical/post_query_builder.rb
app/models/post_event.rb
app/models/post_flag.rb
app/models/user.rb
app/views/post_flags/index.html.erb
test/unit/post_flag_test.rb

Fixes #3349.  It shows all flags to a user, but removes the Creator ID unless you are the flag creator or a moderator that isn't the post uploader.  Similarly the entire flag is hidden if searching by ``creator_id`` or ``creator_name`` (or ``flagger:username`` on posts).  That will prevent users from seeing flags on their own uploads when searching this way, and therefore being able to determine in a roundabout way who flagged their upload.

Disallow a user from seeing flagger's name on own uploads

---

app/assets/javascripts/autocomplete.js

This issue was reported on Discord.  Basically, on Firefox, the jQuery webstorage API, $.localStorage, would return non-keys when the keys function was called.  This included **setItem**, **getItem**, **removeItem**, **key**, **clear** and **length**.  This would cause errors, as when the reduce function was processing, it would encounter length, and try to find localStorage.length.length, which would be _undefined_, which caused the whole thing to return **NaN**.  This would cause the pruning to never take place, as **NaN** is never greater than any number.
All of the $.localStorage.keys() have therefore been replaced with Object.keys(localStorage), which doesn't have this issue.  Admittedly, it's not as much of an issue in the second case, but was replaced for consistency.

Fixed issue with pruning calculation in Firefox

---

app/assets/javascripts/autocomplete.js
app/assets/javascripts/related_tag.js
app/assets/stylesheets/specific/posts.scss
app/logical/post_query_builder.rb
app/logical/tag_category.rb
app/models/post.rb
app/models/tag.rb
app/presenters/post_presenter.rb
app/presenters/tag_set_presenter.rb
app/views/layouts/default.html.erb
app/views/posts/partials/show/_edit.html.erb
app/views/posts/show.html.erb
app/views/related_tags/show.html.erb
app/views/tag_aliases/index.html.erb
app/views/tag_implications/index.html.erb
app/views/tags/_search.html.erb
app/views/tags/edit.html.erb
app/views/uploads/new.html.erb
config/danbooru_default_config.rb
db/migrate/20171106075030_add_tag_count_meta_to_posts.rb
db/structure.sql
test/unit/tag_test.rb

Fixes #3292.  Most of the configuration logic for the tag categories was first moved out of all of the affected files and into the configuration file.  This will facilitate greater control over tag categories for anyone that uses a Danbooru instance, to include renaming, adding, or removing categories.
Some of the logic was left in still though, such as when one category affected another, or something only affected a single category.
One such case was for the new **meta** tag category.  An additional restriction of Builder+ only was applied to that as per Type-kun's suggestion, but since it only affected that category, it was left in the corresponding model and controller files.  However, it could always be moved out to the configuration file as well if necessary.

Migrated tag logic into config file and added fifth tag category meta

---

app/models/comment.rb

Fixes #3351.  Changes the definition for visible and hidden based on whether the user is a moderator.  This prevents the "Show all comments" link from appearing for deleted comments on Builder- users, since they can't see deleted comments anyways.

Change visible/hidden on comments for moderators

---

app/assets/javascripts/related_tag.js
app/views/uploads/batch.html.erb

Fixes #3366, which was caused because the batch view unknowingly had the incorrect value of `#c-uploads #a-new`, which caused it to run the related tag Javascript when it shouldn't.
This therefore fixes two problems present:
1. Renames batch view to the correct ID of `#c-uploads #a-batch`
2. Wraps the JSON parse in related tags with a try/catch for all other unknown cases
As a side note, this bears going through the remaining views and checking that they have the correct IDs as well, though I didn't want to do that as part of an urgent fix request.

Fix upload batch view and related tag script (#3366)

---

app/controllers/bulk_update_requests_controller.rb
app/logical/forum_updater.rb
app/logical/mentionable.rb
app/logical/tag_alias_request.rb
app/logical/tag_implication_request.rb
app/models/bulk_update_request.rb
app/models/forum_post.rb
app/models/tag_alias.rb
app/models/tag_implication.rb
app/models/tag_relationship.rb
test/unit/bulk_update_request_test.rb
test/unit/tag_alias_request_test.rb
test/unit/tag_alias_test.rb

Fixes #3374:
* Changes alias/implication/BUR forum update messages to look like this:
```
The bulk update request #1386 (forum #139259) has been approved by @HillsideMoose.
```
* Refactors aliases/implications to share the same messages.
* Overrides @mention notifications when updating the forum so that we don't dmail the approver.
* Fixes a bug with the `forum_post_id` not being saved when an alias or implication request is created.

Fix #3374: List approver in BUR approval messages

---

app/logical/downloads/file.rb
app/logical/sources/strategies/twitter.rb
test/functional/sources_controller_test.rb
test/unit/sources/twitter_test.rb

Fixes #3377. Broken in #3368; the twitter source strategy didn't know how to parse the status ID when it was only present in the referrer URL.

Fix #3377: Batch bookmarklet doesn't fetch artist/tags from twitter

---

app/models/post_replacement.rb
test/unit/post_replacement_test.rb

Fix #3323: Exclude post replacements from Mod Actions 

---

app/models/tag.rb
config/danbooru_default_config.rb
test/unit/post_test.rb

Fixes #3387 by making the `rating:s` and `-status:deleted` tags not count against the user's tag limit. These tags are already free when in safe mode or when the `Deleted Post Filter` option is turned on, so they may as well be free always.

Fix #3387: Safebooru: Two tag searches fail for members.

---

app/models/post.rb
app/models/tag.rb
script/fixes/051_purge_invalid_tags.rb
test/unit/post_test.rb

Fixes #3390:
* Adds a fix script to purge tags with invalid names from the tags table. Only empty gentags are purged. This will purge invalid metatags from the tags table, along with a bunch of other invalid unicode tags and typo tags. About ~27k tags will be purged: [invalid-tags.json](https://storage.googleapis.com/evazion/danbooru/invalid-tags.json).
* Fixes `Post#get_count_from_cache` to only lookup the count in the tags table when the search is for a single "simple" tag. Don't attempt to lookup multi-tag searches, metatags (`rating:s`), negated tags (`-touhou`), wildcard tags (`*touhou*`), etc in the tags table.

Fix #3390: Searching certain metatags results in an empty paginator

---

app/controllers/pools_controller.rb
app/models/pool.rb

This issue was noticed because of the conversation in [topic #5388](http://danbooru.donmai.us/forum_topics/5388).  Basically, a Gold user was able to add a post to a pool by going through the update function.  The following therefore blocks access to the Edit HTML function for those that can't delete a pool (Platinum-).  Additionally, it raises a validation error which handles users coming though the API.
I thought about restricting add access for all users when a pool is deleted, but then that would require a lot more work for little to no benefit.  Plus, those users could always just undelete a pool if the really wanted to add to it.

Add additional restrictions on updating deleted pools

---

app/logical/anonymous_user.rb
app/logical/current_user.rb
app/models/user.rb
app/views/users/edit.html.erb
config/danbooru_default_config.rb
test/unit/current_user_test.rb

Fixes #3392. Adds an `enable_safe_mode` account setting.

Fix #3392: Add safe mode account setting.

---

app/assets/javascripts/uploads.js
app/views/uploads/new.html.erb

This adds in the third validation from #3352.  As explained on that issue, doing it this way is quicker and more responsive to the user as all the information is already available at the client.  
I took out the `error_messages_for` since the view ERB and Javascript code will cover all of those cases, but I left the original validation error pushes in the uploads model because the user will get those if they try to upload from the API.  The button is left as an `<input>` with a `value="Submit"` to take advantage of existing CSS that styles that button.  The `name="commit"` was left out as it's not sent anyways as a result of using the _trigger_ action with "submit", which is done for the **Return** key anyways so there shouldn't be an issue.

Moved input existence validations to client (#3352)

---

app/logical/downloads/rewrite_strategies/pixiv.rb
app/logical/pixiv_api_client.rb
app/views/static/error.html.erb
test/unit/downloads/pixiv_test.rb
test/unit/sources/pixiv_test.rb

Fixes #3395:
* 5ba6373: Fixes a broken download test. A test post was deleted from Pixiv.
*  183a7e0: Fixes a failbooru when uploading a deleted Pixiv post. The API error message from Pixiv had the encoding set to ASCIII-8BIT instead of UTF-8.
* 0b5ed16: Fixes a `PixivApiClient::Error` when uploading a Pixiv image for a deleted work. Makes the Pixiv URL rewriter return the URL as-is if there's a bad ID error. This is a partial fix, because really we shouldn't fetch the source data at all during the rewrite process unless it's necessary.

Fix #3395: Bookmarklet on pixiv url with deleted post page returns failbooru, and trying to upload it returns an error 

---

app/controllers/posts_controller.rb
app/controllers/uploads_controller.rb
app/models/application_record.rb
app/models/post.rb
app/models/tag.rb
app/models/upload.rb
app/views/layouts/default.html.erb
test/unit/post_test.rb

This is a proof of concept demonstrating how the soft validations from #3352 can be done fully server-side. This adds two type of warnings:
* When new general tags are created, a `Created 2 new tags: <tag1>, <tag2>, ...` notice is displayed. This warns users about typos.
* When an artist tag is created and it doesn't have an artist entry, a `Artist <name> requires an artist entry. Create new artist entry.` notice is displayed. This reminds users to create artist entries.
The approach is to use standard Rails validations to perform these checks during the post saving process, but to store the warnings inside `post.warnings` instead of `post.errors`. This way we can add soft errors that don't prevent the object from saving. Then in the controller we simply set `flash[:notice] = …

Post editing: add warning when creating new tags (#3352)

---

app/logical/post_sets/post.rb
app/models/post.rb
app/presenters/post_presenter.rb
app/views/posts/partials/index/_posts.html.erb

It seems about once every few months a user asks on the forum why they can't view certain posts after they have upgraded to Gold+.  [Topic #14724](http://danbooru.donmai.us/forum_topics/14724) is just the latest, but if you look back, you can see it happens pretty often, probably moreso than gets reported.
This issue occurs mostly because the error message is confusing as pointed out by @kittey on the above topic.  It tells Gold+ users to upgrade to Gold when it hides content in Safe Mode.  Going by his recommendation to fix this issue, I changed the error message to redirect Gold+ users to Danbooru or to adjust their user settings due to #3392.  The wiki that was linked doesn't exist yet (**Help:User Settings**), but such a wiki probably should exist and I plan on creating one.  A hard …

Changed safe mode error message for Gold+ users

---

app/models/favorite_group.rb
test/unit/post_test.rb

Fixes a race condition when adding posts to favgroups. If you tried to add posts to a favgroup very quickly using a script, some posts wouldn't get added. Adding a post to a favgroup was non-atomic, so some updates would clobber others.
This is the same bug as the pool bug from #3091 (fixed in 31b58e17b).

Fix race condition when adding posts to favgroups

---

app/assets/javascripts/autocomplete.js
app/models/tag.rb
db/migrate/20171127195124_add_trigram_index_to_tags.rb
db/structure.sql

Implements #3406. During autocompletion, if no matches are found (presumably because of a typo), then we do a fuzzy name search and return the tags that the closest to what the user typed.
A trigram index is added to make this efficient. A query takes about 100ms-150ms on my machine.
The best way to see how this feels is to try it for yourself. I have it running on http://devbooru.tk:10000/. Some things it's able to correct:
* `longhaie` -> `long_hair` (simple typos)
* `miku_hatsune` -> `hatsune_miku` (wrong name order)
* `ataraxia` -> `fate/hollow_ataraxia` (missing words)

Fix #3406: Autocorrect typos during autocomplete

---

app/views/layouts/default.html.erb

I noticed this bug recently due to leaving several Dmails unread for script testing purposes.
Basically, if you get a new mail and then hide the notice, it will set the ID to the most recent unread Dmail.  However, if that message gets read, then it will no longer be the most recent unread, causing the prior ID equality check to fail, causing the user to get the unread mail notice even though there is no new mail.
So instead of checking for equality, it now checks for presence in case the cookie doesn't exist, then it checks that the most recent Dmail ID is greater than the cookie's value.

Fix Dmail so that prior unread mail won't cause notice to appear

---

app/views/comments/_index_by_comment.html.erb

Related to issue #3291.  The resolution of that issue allows deleted comments to be shown on all other views but the `group_by=comment` partial view, since that partial has its own check for deleted comments as well.  Therefore, this adds the same fix used with the prior issue on the **index_by_comment** view.

Fix deleted comments visibility on partial index by comment

---

app/models/dmail.rb
app/models/user.rb
config/danbooru_default_config.rb
config/initializers/system_user.rb
test/unit/dmail_test.rb
test/unit/post_disapproval_test.rb
test/unit/post_replacement_test.rb
test/unit/user_test.rb

Proposed fix for #3408:
* Members who send spam dmails to 10 different users within a 24 hour window are automatically banned for 3 days. These numbers are open for adjustment.
* Note that recipients can mark dmails as spam manually. This is why the threshold is spam sent to 10 \*different\* users.
* Spammers are banned so that there there's visibility into who the system is taking action against. It might be better to block spammers silently, but there would need to be another way of notifying mods when someone is blocked.
* The ban is only 3 days so that in the unlikely event someone is falsely banned, it won't be forever. Moderators should verify bans and extend them as needed.

Fix #3408: More automated measures against spammers

---

app/models/application_record.rb
app/models/artist.rb
app/models/artist_commentary.rb
app/models/artist_version.rb
app/models/bulk_update_request.rb
app/models/comment.rb
app/models/dmail.rb
app/models/favorite_group.rb
app/models/forum_post.rb
app/models/forum_topic.rb
app/models/note.rb
app/models/pool.rb
app/models/pool_archive.rb
app/models/pool_version.rb
app/models/post_appeal.rb
app/models/post_archive.rb
app/models/post_flag.rb
app/models/post_replacement.rb
app/models/post_version.rb
app/models/tag.rb
app/models/tag_relationship.rb
app/models/tag_subscription.rb
app/models/upload.rb
app/models/user.rb
app/models/user_feedback.rb
app/models/wiki_page.rb
app/models/wiki_page_version.rb
test/unit/application_record.rb

Implements #3430:
* Refactors to add a `search` method to `ApplicationRecord` which handles the `search[id]` param. The `search` method in each model now calls `super` first to handle `search[id]`.
* Adds support for `search[created_at]` and `search[updated_at]` params while we're at it. It's easy and nearly every model has these columns.
* `Tag#parse_helper` and `PostQueryBuilder#add_range_relation` are used to parse the params, so that ranges (e.g. `search[id]=1..10`) are supported. These methods should probably be factored out to make this cleaner.

Fix #3430: Accept the search[id] param in all controllers 

---

app/models/artist.rb
test/unit/artist_test.rb

Fixes #2696. Adds a blacklist of bogus domains to the artist finder. When the artist finder's directory-stripping algorithm reaches a bogus domain, it will terminate instead of returning incorrect matches.
This blacklist was chosen by running the artist finder over every post in the last year and collecting cases where it found bogus matches.

Fix #2696: Bogus results on non-matching URL searches for Artists

---

app/controllers/favorite_groups_controller.rb
app/logical/post_query_builder.rb
app/models/favorite_group.rb
app/models/tag.rb

This fixes a long existing hole in the privacy settings.  Previously, users could still check a user's favorites or favorite groups by using the post query.  Additionally, favorite groups could be found by enumerating them manually.
However, this now brings up the issue of a user wanting to only have some of their favorite groups public, and some private.  Having a favorite group public provides a nice way of showing a group of posts a user has collected so others can look at, such as demonstrating a certain issue.
The above should be handled as a separate pull though.  The simplest way to implement would be to add an ``is_public`` value to all favorite groups which overides any privacy settings.  So if ``is_public`` were true, then it would show the favorite group no matter what. …

Fix incorrect showing of favorites and favorite groups with privacy settings enabled

---

app/assets/javascripts/related_tag.js
app/logical/related_tag_query.rb

I first brought up this idea on the [forum](http://danbooru.donmai.us/forum_topics/14709).  Basically the **list_of_*** character wikis contain a lot of useful information that is currently awkward to access when tagging a post, since you have to add the **list_of_*** text, click the related tag button, and then remember to remove that **list_of_*** when done so that you don't inadvertently create a tag, all without autocomplete since the tag either doesn't exist or is empty.
The above is why I haven't migrated the characters on several different copyright wikis, as I find having the list of characters right at hand extremely convenient.  Having this pull in place would allow a lot of these copyright wikis to be cleaned up and made more efficient.
This pull would only be active on …

Add character list wikis to copyright related tag response

---

app/controllers/post_replacements_controller.rb
app/models/post_replacement.rb
app/views/post_replacements/index.html.erb
config/routes.rb
db/migrate/20171218213037_add_metadata_to_post_replacements.rb
db/structure.sql
test/functional/post_replacements_controller_test.rb
test/unit/post_replacement_test.rb

Fixes #3324:
* Tracks the changes in the image metadata - the md5, file size, file extension, image width, and image height - in the post replacement history.
* Adds a `PUT /post_replacements/:id.json` endpoint for updating an existing replacement's metadata. This is to allow for metadata in old replacements to be backpopulated. 
Screenshot of `/post_replacements`:

Fix #3324: Incorporate replacement comment info in the replacement history

---

app/models/post.rb
test/unit/post_test.rb

Fixes #3440. Applies implications after automatic tags are added.

Fix #3440: Implications aren't applied to automatic tags.

---

app/models/favorite_group.rb
app/views/favorite_groups/edit.html.erb
db/migrate/20171219001521_add_is_public_to_favorite_groups.rb
db/structure.sql

Builds onto #3433 by giving the option to make favorite groups public.  It also changes how the index search parameters are handled, showing only the public favorite groups instead of throwing a permission error.

Give option to make favorite groups public

---

app/models/post.rb

Fixes #3444.  The validation only applies to non-**General**/**Meta** tags since **General** tags are already covered and **Meta** tags can be empty before they get used.  It provides an hour leeway before throwing the warning, coinciding with the current merge time on post versions IIRC.  This should give the user ample time to fix or refix tagging errors.
Unfortunately, the above check can't be used to detect underused tags for the red CSS styling and hover error, unless we want to apply that to all non-**Meta** tags with a post count of 1.  However, displaying the warning from above should be sufficient.

Fix #3444: Add validation warning for non-general/meta tags

---

app/models/post.rb

@nonamethanks noticed this issue and brought it up on Discord.  Basically, Danbooru was considering all tags with a post count of 1 to still be new tags by the tag validator.  This caused the notice to appear when incrementing the post count from 1 to 2.
This is because at the time that the validator function is running, the delayed job which increments the post count has not yet run.  Therefore, it should only accept tags that have a post count of 0 and below.
I checked this pull on both new and existing empty tags, and it worked for both cases.

Fix cutoff for what is considered an added tag

---

app/controllers/application_controller.rb

http://danbooru.donmai.us/posts/js/bf.js
http://danbooru.donmai.us/posts/js/jquery.js
http://danbooru.donmai.us/prepare.js
Fixes a double render error in requests like those above. First `StaticController#not_found` is rendered, then a second render happens inside `rescue_from Exception, :with => :rescue_exception` due to Rails raising an `ActionController::InvalidCrossOriginRequest` exception.

Fix double render error in `/blah.js`.

---

config/routes.rb

Fixes an error with requests to http://danbooru.donmai.us/favorites/1234 not returning the normal `not found` 404 page.
This error is coming up a lot in New Relic due to certain bots trying to crawl `/favorites/$post_id` pages, even though those pages don't exist.
EDIT: Also fixed some other invalid routes under `/posts` and `/explore/posts`.

Fix "The action 'show' could not be found for FavoritesController"

---

app/logical/sources/strategies/base.rb
test/unit/sources/pixiv_test.rb

Fixes #3450. Resolves aliases in translated tags. For example, say we lookup `遠坂凛` and find both `tohsaka_rin` and `toosaka_rin`. We apply aliases so that `tohsaka_rin` becomes `toosaka_rin`, which is then returned as the only translated tag after duplicate tags are filtered out.

Fix #3450: Aliased tags show up under translated tags.

---

app/controllers/tags_controller.rb
app/logical/alias_and_implication_importer.rb
app/models/tag.rb
app/models/tag_alias.rb
test/functional/tags_controller_test.rb
test/unit/tag_test.rb

Fixes #3448. Lowers the limit to 1000 for builders. Admins are allowed to change anything. Fixes a bug with limits not being enforced when the category is changed via `/tags/1234/edit`.

Fix #3448: Lower the limit for tag category changes

---

app/assets/javascripts/autocomplete.js.erb
app/assets/javascripts/related_tag.js.erb
app/assets/stylesheets/application.scss
app/assets/stylesheets/erb/posts.scss.erb
app/logical/tag_category.rb
app/views/layouts/default.html.erb
app/views/posts/show.html.erb
app/views/uploads/new.html.erb
config/danbooru_default_config.rb

Fixes #3455.  ~~Also, I didn't consider worth it to add the very short category names of **ch** and **co**.~~

Fix 3455: Convert tag category Javascript/CSS assets to ERB

---

app/logical/session_loader.rb

Possible fix for #3460. We were trying to update the user's last ip addr before we had initialized their statement timeout. Set their statement timeout earlier, before updating anything in the database, to avoid potential timeouts here.

Fix #3460: Timeout in `update_last_ip_addr`.

---

app/logical/sources/strategies/nico_seiga.rb

Fixes the first part of #3457. Avoids the unnecessary redirect to http://www.nicovideo.jp after logging in to NicoSeiga.

Fix #3457: Timeout when fetching source data from NicoSeiga.

---

app/controllers/users_controller.rb
app/logical/session_loader.rb
test/functional/users_controller_test.rb

Fixes #3464. Also fixes the account signup page not showing an error message when signup failed.

Fix #3464: CurrentUser.ip_addr isn't set for anonymous users.

---

app/models/post.rb
test/unit/post_test.rb

Fixes #1563. Adds a warning when an upload has less than 10 general tags.
The idea of warning about uploads with not enough tags has been proposed more than a few times over the years. Exactly how many is "not enough" is of course debatable. I chose 10 gentags because ~97% of posts from the past year have at least this many tags. This puts the threshold well below what most posts have.

Fix #1563: Warn users attempting to upload with very few tags.

---

app/logical/post_query_builder.rb

@nonamethanks  brought up this issue on Discord.  He indicated that the "status:active -status:flagged" search doesn't work, for one since only one status metatag is allowed, but also because **status:active** currently also includes flagged posts.
As a solution, the `is_flagged` flag is added to both the **status:active** and **-status:active** searches as applicable.  An alternate solution could be to set `is_pending` to true on flagged posts, but that would affect the code in a lot more places.

Fix status:active so that it doesn't show flagged posts

---

app/views/post_replacements/index.html.erb

This was missing from the **Tags** input on post_replacements/index.

Add autocomplete to tags input on post replacements

---

app/assets/stylesheets/specific/iqdb_queries.scss
app/controllers/iqdb_queries_controller.rb
app/views/iqdb_queries/check.html.erb
app/views/static/site_map.html.erb
config/routes.rb

A partial fix of #2833.  I say partial since it would be nice to eventually add support for local files, and so I'd like to keep that issue open at least for now.
I converted the endpoint to a singular resource since it doesn't really need the actions that resources do, and I added an additional named action since it didn't make sense to have the standalone page on the new or edit action.

Initial add of IQDB standalone page

---

db/migrate/20171230220225_change_timestamps_to_non_null_on_tags.rb
db/structure.sql
script/fixes/052_fix_tag_timestamps.rb

Fixes #3480. Initializes `created_at` and `updated_at` for any tags where these fields are null, and redefines the columns to be `NOT NULL`.

Fix #3480: NoMethodError error when adding artist tag to post.

---

app/logical/post_sets/post.rb
app/views/posts/index.html.erb

Fixes #3484:
* Shows the wiki tab only for simple tag searches that could have a wiki, not for metatags / wildcard tags / negated tags etc.
* Simplifies `PostSets::Post#hide_from_crawler?` and makes it hide all metatags.

Fix #3484: /posts: don't show wiki tab for metatags

---

app/views/artist_commentary_versions/_revert_listing.html.erb
app/views/artist_commentary_versions/_standard_listing.html.erb
app/views/artist_commentary_versions/index.html.erb
app/views/artist_versions/_revert_listing.html.erb
app/views/artist_versions/_standard_listing.html.erb
app/views/artist_versions/index.html.erb
app/views/note_versions/_revert_listing.html.erb
app/views/note_versions/_standard_listing.html.erb
app/views/note_versions/index.html.erb
app/views/pool_versions/_revert_listing.html.erb
app/views/pool_versions/_standard_listing.html.erb
app/views/pool_versions/index.html.erb
app/views/post_versions/_revert_listing.html.erb
app/views/post_versions/_standard_listing.html.erb
app/views/post_versions/index.html.erb

First ran this by @evazion on Discord.  Basically, it doesn't make sense to put revert links on the version indexes except when searching by instance, as the revert lacks all context to what changes have taken place before or after.  Undo links on **post_versions** don't have this issue since it displays all of the changes made in that version, therefore it's known that undo will reverse all of those changes.
Different partials were created primarily since an entire column was being removed for most of the tables.  The one exception was **post_versions** since there may be an undo link in that column that may need to be displayed, but it was also separated into partials just to keep things standard.  **wiki_page_versions** wasn't done since the revert link for that exists in the …

Differentiate version index views with reversion links

---

app/assets/javascripts/autocomplete.js.erb

I discovered this after seeing that autocomplete was saving metatags when it shouldn't, e.g. ``source:none``, ``id:1234``, etc.  
I also found a few other things that needed fixing or removed since they weren't needed.
1. Add parent metatag defaults any and none
2. Add missing user-based metatags to user source (appealer, flagger, upvote, downvote)
3. Remove all negative metatags since the prior code strips the '-'

Fix metatag handling in autocomplete

---

app/views/artist_versions/_revert_listing.html.erb
app/views/artist_versions/_standard_listing.html.erb
app/views/pool_versions/_revert_listing.html.erb
app/views/pool_versions/_standard_listing.html.erb
app/views/post_versions/_revert_listing.html.erb
app/views/post_versions/_standard_listing.html.erb

User unbreakable and chinatsu reported on Discord that there was some spacing issues on the post versions table on Firefox and Internet Explorer where the **Tags** section would run off the screen.
https://cdn.discordapp.com/attachments/310846683376517121/397908244590231553/unknown.png
This was caused due to the changes in #3486.  I checked the other affected versions and fixed a few other problem areas.
1. **Other Names** on artist versions
2. **Changes** on pool versions
I left both the **Original** and **Translated** columns alone on the artist commentaries even though they can both get long, as it may be beneficial to see where the carriage returns are at.
Went back and removed the pipe character '|' on the post version standard listing as it's not needed.

Fix spacing issues on versions

---

app/models/tag.rb

I discovered the other day that the fuzzy name matching on autocomplete results didn't have the **antecedent_name** field defined in the results which luckily doesn't affect the Javascript as ``undefined`` evaluates to ``false``.  Additionally, it was also returning information it didn't need to, i.e. the entire tag record.
http://danbooru.donmai.us/tags/autocomplete.json?search[name_matches]=f-22_raptor
```
[{
"id": null,
"name": "f-22_raptor",
"post_count": 98,
"category": 0,
"antecedent_name": null
}]
```
http://danbooru.donmai.us/tags/autocomplete.json?search[name_matches]=f-22_rapter
```
[{
"id": 1347519,
"name": "f-22_raptor",
"post_count": 98,
"related_tags": "f-22_raptor 98 airplane 81 aircraft 81 jet 74 military 67 military_vehicle 55 fighter_jet 52 highres 47 1girl 41 ace_combat …
```

Fix fuzzy autocomlete results

---

app/models/artist.rb
app/models/wiki_page.rb

Fixes #2974.  Besides artist edits that don't affect the wiki, it also prevents updating the **updater_id** on wiki page saves where nothing has changed.

Fix erroneous updates to wiki page when nothing changes

---

app/models/post.rb
app/models/tag.rb

Fixes #3494.  Besides handling not allowing existing root tags to not be changed via *_(cosplay), I also discovered that *_(cosplay) tags weren't converted to use the alias form of the root tag.
Given the example alias of ``/nm -> nishizumi_miho``
How it was:
- /nm_(cosplay) => char:nishizumi_miho, cosplay, /nm_(cosplay)
How it changed:
- /nm_(cosplay) => char:nishizumi_miho, cosplay, nishizumi_miho_(cosplay)
The "char:" was left in for the case that a brand new character tag will be created.

Fix how cosplay tags are handled

---

app/models/mod_action.rb
app/models/post.rb
app/models/user_name_change_request.rb

I checked the moderator actions and noticed that name changes were being set to the **other** category because it wasn't being set by the **ModAction.log** function.  Seems like that's one that was missed in #3496.
Besides the above, it was also asked by an approver to add a mod action for moving a post's favorites.

Fix mod actions

---

app/assets/javascripts/posts.js

From the [Danbooru forum](http://danbooru.donmai.us/forum_posts/142755):
> Laethiel said:
> 
> On mobile (Android Chrome) but not on desktop (Windows 7, Firefox or Chrome), I'm having two issues.
> 
> 1. Images are automatically resized. I have to tap "Resize to window" to return them to full size. In settings, I have "Default image width" set to original and "Fit images to window" set to No.
> ......
This was caused by commit a95af95e when the **dm** cookie was removed.  It now uses the meta "viewport", which only gets set when ``disable_responsive_mode`` is true.

Fix the auto resize in desktop mode (ref: a95af95e)

---

app/logical/google_big_query/post_version.rb
app/logical/post_keeper_manager.rb
app/models/post.rb
app/views/posts/partials/show/_information.html.erb
db/migrate/20180116001101_add_keeper_data_to_posts.rb
test/models/post_keeper_manager_test.rb

Hide uploader information (still visible in post history) and add a new field for keeper (most frequent tagger)

implement post keepers

---

app/assets/javascripts/autocomplete.js.erb

From the [Danbooru forum](http://danbooru.donmai.us/forum_posts/142940):
> Laethiel said:
> 
> Enter is activating auto-complete, tested in both Firefox and Chrome. This is pretty awful, as, e.g., typing width:>3000 [Enter] just changes the search box contents to band-width instead of actually searching.
This is because nothing was being done with the **resp** object when a non-autocomplete metatag was being used, and instead [just returning from the function](https://github.com/r888888888/danbooru/blob/master/app/assets/javascripts/autocomplete.js.erb#L158-L177), which was causing the last autocomplete data to be used instead and therefore leading to incorrect results.
With this pull, when one of these metatags are used, it instead clears the results by returning a blank array with the …

Clear results when a non-autocomplete metatag is used

---

app/assets/javascripts/autocomplete.js.erb

Partial fix for #3545. Fixes the first point: makes the Enter key submit the form when the typed tag is an exact match for the suggested tag.

Fix #3545: Autocomplete: enter key should submit on exact match

---

app/assets/javascripts/autocomplete.js.erb

This is a better fix than #3546 for the problems with the Enter key during autocomplete. This fixes these issues:
* `abs<Enter>` inserts `absurdres` instead of searching for `abs`.
* `black_*<Enter>` inserts `black_hair` instead of searching for `black_*`.
* `rating:s<Enter>` inserts `rating:safe` instead of searching for `rating:s`.
* Pressing Enter while the cursor is in the middle of a tag behaves incorrectly (see [forum #142995](https://danbooru.donmai.us/forum_posts/142995)).
The root problem is enabling `autoFocus` on the autocomplete widget. Autofocus causes the first item in the autocomplete menu to be automatically selected when autocomplete opens. This interferes with the Enter key, since the Enter key inserts the selected item from the autocomplete menu. We only want that to …

Autocomplete: Fix issues with Enter key

---

app/assets/javascripts/artists.js
app/assets/javascripts/autocomplete.js.erb
app/assets/javascripts/pools.js
app/assets/javascripts/wiki_pages.js
app/helpers/application_helper.rb
app/views/artist_versions/search.html.erb
app/views/artists/_quick_search.html.erb
app/views/artists/_search.html.erb
app/views/pool_elements/_new.html.erb
app/views/pools/_quick_search.html.erb
app/views/pools/_search.html.erb
app/views/wiki_pages/_quick_search.html.erb
app/views/wiki_pages/search.html.erb

This cleans up autocomplete to reduce some duplicated code. In doing so, it fixes several minor bugs and makes autocomplete behave more consistently sitewide:
* Moves the artist/pool/wiki autocomplete code to `autocomplete.js`, with all the rest of the autocomplete code.
* Marks autocompleted fields with `data-autocomplete="<type>"` attributes, instead of hardcoding the field IDs in Javascript.
* Uses `Danbooru.Autocomplete.render_item` to render all autocomplete menus. This fixes usernames not being colorized when completing mentions, and post counts not being shown when completing pools on the `/pools` page.
* Sets default options on the autocomplete widget so that autocomplete behaves consistently everywhere:
1. Disables `autoFocus` everywhere (previously it was enabled on `/tags`, but …

Fix inconsistencies in autocomplete behavior

---

app/controllers/bulk_update_requests_controller.rb
app/models/bulk_update_request.rb
app/views/bulk_update_requests/_form.html.erb

Partial fix for #3554. Allows admins to edit a BUR's forum post id, so that BURs with a nil `forum_post_id` can be corrected before approval / rejection. This does take extra work, but in the long run I think it's better to fix the missing data than to work around it.

#3554: Allow admins to edit BUR forum topic/post ids

---

app/logical/downloads/file.rb
test/unit/downloads/art_station_test.rb

Fixes #3528. Adds a random URL param when downloading files to bypass any transparent caches that may  potentially alter the file.

Fix #3528: Add method to prevent image-hosting CloudFlare sites from altering the image

---

app/logical/downloads/file.rb
test/unit/downloads/art_station_test.rb

Reverts r888888888/danbooru#3551

Revert "Fix #3528: Add method to prevent image-hosting CloudFlare sites from altering the image"

---

app/logical/alias_and_implication_importer.rb
app/models/bulk_update_request.rb
test/unit/bulk_update_request_test.rb

Fixes #3554. Wraps `approve!` and `reject!` in transactions so that if there's an error in approving or rejecting a BUR, it leaves the BUR's status unchanged instead of updating the BUR but not updating the forum.

 Fix #3554: BUR approval bugs

---

app/logical/downloads/file.rb
config/danbooru_default_config.rb
script/install/nginx.danbooru.conf
test/unit/downloads/file_test.rb

Fixes #3552. Also fixes the max POST data limit in Nginx being lower than the max upload limit in the Danbooru config. This meant that files uploaded from your computer were limited to 30Mb instead of 35Mb.

Fix #3552: Upload filesize limits can be bypassed

---

app/models/upload.rb
config/danbooru_default_config.rb
test/unit/upload_test.rb

Related to #3570. Adds these limits to uploads:
* Max image width: 40000
* Max image height: 40000
* Max image resolution (width * height): 441 megapixels (equivalent to a 21000x21000 image)
These values were chosen to be slightly bigger than the current biggest images on the site. [post #442772](https://danbooru.donmai.us/posts/442772) is the tallest at 500x39401 and [post #2889454](https://danbooru.donmai.us/posts/2889454) is the highest resolution at 408 megapixels (16918x24138).
These limits are to prevent a DoS attack on the image resizer. Excessively large images can require hundreds of gigabytes of memory to resize. See [here](https://www.bamsoftware.com/hacks/deflate.html) for an example of a 6MB, 225000x225000 PNG file that would take 141GB of memory to decompress and resize.

Add limits on max dimensions of uploads

---

app/models/post.rb
test/unit/post_test.rb

Fixes #3583. Copies `translated`, `partially_translated`, `check_translation`, `translation_request`, and `reverse_translation` to the destination post. Also copies the embedded notes flag.

Fix #3583: Copying notes should also change meta tags in the destination post 

---

app/logical/storage_manager.rb
app/models/post.rb
app/views/posts/partials/show/_download.html.erb
app/views/posts/partials/show/_flash.html.erb
app/views/posts/partials/show/_information.html.erb
app/views/posts/partials/show/_notices.html.erb
app/views/posts/partials/show/_options.html.erb
app/views/posts/partials/show/_ugoira_original.html.erb
app/views/posts/partials/show/_ugoira_webm.html.erb
app/views/posts/partials/show/_video.html.erb

Possible fix for #3597. Generating tagged filenames requires a memcache fetch to get the `humanized_essential_tag_string`. Since thumbnails include `data-file-url` / `data-large-file-url` attributes, that meant we were doing a memcache fetch for each thumbnail. Changes things so that tagged filenames are only used for URLs on the post show page.

Possible fix for #3597: Poor performance since last deploy

---

app/assets/javascripts/common.js
app/controllers/iqdb_queries_controller.rb
app/logical/iqdb/download.rb

Related to #3605. Adds better error handling when iqdb lookups fail:
* Raise an error instead of returning no matches when iqdbs returns an error response.
* Include the api response returned by iqdbs in error messages.
* Display an error message when the `Find similar` link in the sidebar fails.
* Simplify the show / check actions in the controller (unrelated code cleanup).

Improve IQDB error handling

---

app/controllers/application_controller.rb
app/logical/current_user.rb
app/logical/storage_manager.rb
config/danbooru_default_config.rb

Potential fix for #3603. This saves the `root_url` for the current request in `CurrentUser.root_url`. This lets you say
```
StorageManager:SFTP.new(*all_server_hosts, base_url: CurrentUser.root_url + "data")
```
and it will set the base url to whichever protocol + domain the current user is on. This is kind of hacky, but I couldn't find a better way to pass this information in.

Fix #3603: Unable to view images on Hijiribe/Sonohara when Danbooru is blocked

---

app/logical/deviant_art_api_client.rb
app/logical/sources/strategies/deviant_art.rb
config/danbooru_default_config.rb
test/unit/sources/deviantart_test.rb

Fixes #3260. This switches from scraping the HTML to using DeviantArt's API. This should fix the problem of getting captcha'd randomly.
The API is documented here: https://www.deviantart.com/developers/. You'll need to register an app there to get the `client_id` and `client_secret`. The app doesn't need to be published.
The basic flow of the API is as follows:
* Login using OAuth2 with the client credentials grant type to get an access token.
* Scrape the work's HTML page to get its UUID from the `<meta property="da:appurl">` element. The API operates only on UUIDs and AFAIK this is the only way to get a work's UUID.
* Call `/deviation/{uuid}`, `/deviation/metadata`, and `/deviation/download/{uuid}` to get the info we need.
Sample API responses:
* Work: …

Fix #3260: Exception when uploading certain DeviantArt posts

---

app/logical/danbooru/paginator/active_record_extension.rb
app/logical/danbooru/paginator/sequential_collection_extension.rb
test/unit/paginator_test.rb

Fixes #3642. The way the sequential paginator works is that we fetch one more record than requested so that we're able to tell if there is a next page or not. This was to fix #2044. To discard that extra record from the collection, we overrode `to_a`. But in Rails 5 there was an internal refactoring and `to_a` isn't called anymore, so the extra record wasn't getting discarded.
The fix is just to override `records` instead. This is what Rails now calls instead of `to_a`. But this is still pretty hacky though. Ideally we would avoid overriding internal Rails methods like this.

Fix #3642: Issues with sequential pagination

---

app/assets/stylesheets/common/simple_form.scss
app/assets/stylesheets/common/tables.scss
app/assets/stylesheets/specific/uploads.scss
app/controllers/uploads_controller.rb
app/models/upload.rb
app/presenters/post_presenter.rb
app/views/uploads/_search.html.erb
app/views/uploads/_secondary_links.html.erb
app/views/uploads/batch.html.erb
app/views/uploads/index.html.erb
app/views/uploads/new.html.erb
app/views/uploads/show.html.erb
test/functional/uploads_controller_test.rb

Fixes #3657:
* Add more search options to the `/uploads` page. Most columns in the uploads table are now searchable, but only the most useful ones are exposed in the UI.
* Revamp the `/uploads` listing to add thumbnails, colorize tags, show source/size/dimension info, and add `»` search drilldown links where relevant.
* Link the batch uploads page and the IQDB search page in the subnav bar.
* Fix the batch upload page to be usable without the bookmarklet.
Screenshots:

Fix #3657: Add improvements to the uploads interface

---

app/assets/javascripts/application.js
app/assets/javascripts/post_tooltips.js.erb
app/assets/javascripts/posts.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/common/erb/tags.scss.erb
app/assets/stylesheets/specific/comments.scss
app/assets/stylesheets/specific/post_tooltips.scss
app/assets/stylesheets/specific/posts.scss
app/controllers/application_controller.rb
app/controllers/posts_controller.rb
app/helpers/application_helper.rb
app/presenters/post_presenter.rb
app/presenters/tag_set_presenter.rb
app/views/posts/show.html+tooltip.erb
app/views/uploads/index.html.erb
vendor/assets/javascripts/jquery.qtip.js
vendor/assets/stylesheets/jquery.qtip.css

Fixes #3664. This goes a step further and replaces the default browser tooltips with HTML tooltips. This allows tags to be colorized and clickable too.
This works as follows:
* After hovering over the thumbnail for enough time, we make a call to `/posts/{id}?variant=tooltip` to get the tooltip html and insert it into the tooltip. This template uses Rails' [variants system](http://guides.rubyonrails.org/4_1_release_notes.html#action-pack-variants).
* [qtip2](http://qtip2.com) is used to generate the tooltips. This gives us a look and feel that's close to native browser tooltips.
* To generate the tag list, we use `split_tag_list_html`, which is the same code that generates the sidebar tag list. 442964b and f299858 were refactorings to make this possible. A side effect of this is that tag …

Fix #3664: Highlight non-gentags in post tooltip

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js

Fixes #3678. Apparently we need to include `jquery_ujs` instead of `rails-ujs`. To be honest I'm not sure why rails-ujs isn't enough.

Fix #3678: "Access denied" when adding commentary.

---

app/logical/tag_alias_request.rb
app/logical/tag_implication_request.rb
app/models/application_record.rb
app/models/artist.rb
app/models/artist_commentary.rb
app/models/artist_version.rb
app/models/ban.rb
app/models/bulk_update_request.rb
app/models/comment.rb
app/models/dmail.rb
app/models/favorite_group.rb
app/models/forum_post.rb
app/models/forum_topic.rb
app/models/note.rb
app/models/note_version.rb
app/models/pool.rb
app/models/post.rb
app/models/post_appeal.rb
app/models/post_flag.rb
app/models/saved_search.rb
app/models/tag.rb
app/models/upload.rb
app/models/user.rb
app/models/wiki_page.rb
app/models/wiki_page_version.rb
config/initializers/core_extensions.rb

Fixes #3696:
* Adds `truthy?` and `falsy?` core extensions to String.
* Uses `truthy?` and `falsy?` to replace ad-hoc parsing of boolean parameters in various places.
* Uses `ApplicationRecord#attribute_matches` to handle boolean attributes consistently inside `search` methods.
* Adds support for searching various boolean attributes that previously weren't supported.

Fix #3696: API: handle boolean params consistently

---

app/logical/downloads/file.rb
app/models/upload.rb
test/unit/upload_test.rb

Fixes #3659:
Bug: if an upload timed out while downloading the file, `Upload#process!` would catch the error and attempt to retry, but since the upload was already in the 'processing' state, on the second try `process!` would bail out immediately and leave the upload stuck in the 'processing' state.
Fix: remove the retry logic from `Upload#process!`. Let `Downloads::File#download!` (which already has its own retry logic) handle it instead.
This also fixes some upload tests that got mixed up when merging the Rails 5.2 branch.

Fix uploads getting stuck in 'processing' state (fix #3659)

---

app/controllers/post_approvals_controller.rb
app/models/post_approval.rb
app/models/post_event.rb
app/views/post_approvals/index.html.erb
app/views/post_events/index.html.erb
app/views/static/site_map.html.erb
config/routes.rb
test/factories/post_approval.rb
test/functional/post_approvals_controller_test.rb
test/functional/post_events_controller_test.rb
test/unit/post_approval_test.rb

Fixes #3579:
* Adds a `/post_approvals` index.
* Adds approvals to the post events page (`/posts/:id/events`).
* Moves post events (approvals, flags, appeals, replacements) to their own section in the sitemap.
Screenshots:

Fix #3579: Add post approval index

---

app/assets/javascripts/favorites.js
app/views/posts/show.html.erb

Fixes #3633 by continuing to remove publicly available instances of the favorites string.

Fix #3633: Remove favorites meta tag

---

app/views/uploads/new.html.erb

to match the rest of the code base
For flash files I've used the file extension ([doc](http://www.dropzonejs.com/#config-acceptedFiles)) because the mime type is browser
specific and I've found at least 3 different variations for .swf so far:
1. `application/vnd.adobe.flash-movie`: [wikipedia](https://en.wikipedia.org/wiki/SWF)
2. `application/vnd.adobe.flash.movie`: [mailcap](https://pagure.io/mailcap/blob/ec8c60e6b0b02b4af9081c6913746adb0da695f5/f/mime.types#_420), firefox
2. `application/x-shockwave-flash`: [sitepoint](https://www.sitepoint.com/mime-types-complete-list/), [mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types)
I did not include .zip for Ugoiras (`application/zip`) because I got this error every time (it does work …

Make dropzone accept mp4, webm, and swf files

---

app/assets/stylesheets/common/main_layout.scss

Especially in Safari, the search button as of a recent version has been looking pretty bad.
This commit restyles the button to use the same link colours for normal and hover/focus and make it somewhat more consistent with other elements. A rough idea of what it'll look like:

Restyle search button to match rest of the UI

---

app/controllers/comments_controller.rb
app/javascript/src/javascripts/comments.js
app/models/comment.rb
app/views/comments/_form.html.erb
app/views/comments/edit.html.erb
app/views/comments/index_for_post.js.erb
app/views/comments/partials/index/_list.html.erb
app/views/comments/partials/show/_comment.html.erb

This cleans up `comments.js` and fixes a couple issues along the way:
* Fix comment edit forms flickering on page load. Mark these forms as hidden by default in the html, instead of showing them by default then hiding them later in Javascript after the page loads.
* Use [event delegation](https://learn.jquery.com/events/event-delegation/) to bind click handlers so that they only have to be bound once, and don't have to be bound again when comments are dynamically loaded by "Show all comments".
* Restore the behavior of thresholded comments being greyed out (this was lost in 6fa0ae2). Set the `below-threshold` class for thresholded comments in the html, instead of setting it in Javascript.
* Remove some dead code.

Refactor comments.js

---

app/controllers/favorites_controller.rb
app/models/favorite.rb
app/models/user.rb
app/views/favorites/_update.js.erb
app/views/favorites/create.js.erb
app/views/favorites/destroy.js.erb
app/views/static/error.js.erb
test/unit/favorite_test.rb

Fixes #3813.
This also cleans up response handling in the favorites controller. As a side effect, the `POST /favorites.json?post_id=1` action now returns the updated post (instead of just `{ success: true }`), and the `DELETE /favorites/1.json` action now returns `204 No Content`.

 Fix #3813: Favorite limit can be bypassed.

---

app/javascript/src/javascripts/comments.js
app/javascript/src/javascripts/common.js
app/javascript/src/javascripts/notes.js
app/javascript/src/javascripts/saved_searches.js
app/javascript/src/javascripts/shortcuts.js
app/javascript/src/javascripts/utility.js
app/javascript/src/styles/common/tables.scss
app/views/artist_versions/_revert_listing.html.erb
app/views/artist_versions/_standard_listing.html.erb
app/views/forum_posts/new.js.erb
app/views/forum_topics/show.html.erb

This is just some miscellaneous code cleanups for `utility.js`:
* Simplify even/odd table row striping.
* Simplify `$.fn.selectEnd()`.
* Simplify the "W to scroll up" / "S to scroll down" hotkeys.
* Replace `Utility.scroll_to` with `Element.scrollIntoView`.
* Remove `Utility.without`.

Cleanup utility.js

---

app/javascript/src/javascripts/autocomplete.js.erb
app/logical/anonymous_user.rb
app/logical/post_query_builder.rb
app/models/post.rb
app/models/tag.rb
test/unit/post_test.rb

Fixes #3753. Adds the following metatags:
* `status:modqueue` - all posts that are pending or flagged.
* `status:unmoderated` - all posts that are pending or flagged and that you haven't disapproved yet. Same thing as the modqueue page.
* `disapproval:any` - all posts that you have disapproved.
* `disapproval:none` - all posts that you haven't disapproved.
* `disapproval:<disinterest|poor_quality|breaks_rules>` - all posts that you have disapproved with the given reason.

Add status:<unmoderated|modqueue>, disapproval:<type> metatags

---

app/javascript/src/javascripts/blacklists.js
app/javascript/src/styles/common/blacklists.scss
app/javascript/src/styles/common/main_layout.scss
app/javascript/src/styles/specific/comments.scss
app/javascript/src/styles/specific/posts.scss
app/views/posts/partials/index/_blacklist.html.erb
app/views/wiki_pages/_sidebar.html.erb

Fixes #3709. Allows one to use OR searches in blacklists ( `~tag1 ~tag2`). Also truncates long blacklist rules to fit on one line, like this:

Fix #3709: Provide OR capability for blacklist items

---

app/logical/sources/strategies/twitter.rb
test/unit/sources/twitter_test.rb

This fixes the Twitter strategy to not error out when given a direct image url but not a referer url. This can happen when uploading a direct image url from Twitter without the bookmarklet.

Twitter: fix handling of direct image urls without a referer url.

---

app/logical/sources/strategies/deviant_art.rb
test/unit/sources/deviantart_test.rb

Fixes #3864:
* Fixes the DeviantArt strategy erroring out in certain cases where we can't do the API call because the image URL doesn't contain the deviation ID.
* Fixes the artist finder to still work even if we can't perform the API call, if the URL contains the artist name.
* Fixes `canonical_url` to be the image URL, if the URL contains the deviation ID, otherwise use the page URL.

Fix #3864: DeviantArt fetch source data failure

---

app/logical/daily_maintenance.rb
app/models/ban.rb
test/unit/daily_maintenance_test.rb

Fixes #3837. Adds a daily maintenance job that clears the `is_banned` flag for users who are no longer banned.

Fix #3837: Remove expired bans.

---

app/controllers/uploads_controller.rb
app/javascript/src/styles/specific/posts.scss
app/javascript/src/styles/specific/uploads.scss
app/logical/sources/strategies/base.rb
app/logical/sources/strategies/pixiv.rb
app/logical/upload_service/controller_helper.rb
app/presenters/post_presenter.rb
app/views/iqdb_queries/_matches.html.erb
app/views/sources/_info.html.erb
app/views/uploads/_image.html.erb
app/views/uploads/_post.html.erb
app/views/uploads/_related_posts.html.erb
app/views/uploads/new.html.erb

Should fix #3873. This replaces the `This post has probably already been uploaded` message with a `Related Posts` section, showing the actual thumbnails of other posts uploaded from the same source. In other words, it shows which other images were previously uploaded from the same Twitter/Tumblr/Pixiv gallery:

Fix #3873: Batch bookmarklet for tumblr reports wrong posts as already uploaded

---

app/controllers/sources_controller.rb
app/javascript/packs/application.js
app/javascript/src/javascripts/uploads.js
app/javascript/src/styles/specific/posts.scss
app/views/sources/_info.html.erb
app/views/sources/show.js.erb

This refactors how the `Fetch source data` box is rendered. Instead of calling `/source.json` and rendering the html client-side in Javascript, which is fairly messy, we call `/source.js` and have it render the html server-side.
The point of this is to simplify the code, and also to lay the groundwork for eliminating the ajax calls to `/artist/finder.json` and `/iqdb_queries.json` as mentioned in #3874. We can reduce three ajax calls to one by having `/source.js` also return the artist and iqdb matches.

Render "Fetch source data" box server-side

---

app/javascript/src/styles/common/dtext.scss
app/views/layouts/default.html.erb

Fixes #3439. Adds an external link icon to offsite links in dtext:
Also upgrades Font Awesome to 5.3.1 (this was necessary for `data-search-pseudo-elements`, see [here](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements)).

Fix #3439: Identify external links in DText.

---

app/controllers/artists_controller.rb
app/javascript/src/javascripts/posts.js.erb
app/javascript/src/javascripts/related_tag.js.erb
app/logical/sources/strategies/base.rb
app/logical/sources/strategies/twitter.rb
app/models/artist.rb
app/views/posts/partials/show/_edit.html.erb
app/views/uploads/new.html.erb
config/routes.rb
test/functional/artists_controller_test.rb
test/unit/artist_test.rb

This cleans up some things in the artist finding code. The main point of this is to replace the ajax call to `/artists/finder.json` with a call to `/sources.js`:
* On posts, automatically trigger "Fetch source data" when clicking the Edit tab, instead of triggering the artist finder button. This way we find both the artist and the translated tags in one ajax call.
* Remove the "Artist" finder button next to the source field. This button isn't necessary given that "Fetch source data" finds the artist itself.
* Remove the /artists/finder.json API endpoint. This is no longer used after removing the "Artist" finder button.
* Clean up the artist finding logic in `Artist#url_matches` such that we only lookup the url once, not multiple times.

Cleanup artist finder

---

app/controllers/artist_urls_controller.rb
app/models/application_record.rb
app/models/artist_url.rb
app/views/artist_urls/index.html.erb
app/views/artists/_secondary_links.html.erb
config/routes.rb
db/migrate/20180916002448_add_trigram_index_to_artist_urls.rb
db/structure.sql
test/functional/artist_urls_controller_test.rb
test/unit/artist_url_test.rb

Partial fix for #3900: 
* Adds an `/artist_urls` index page. This is mainly intended for api use, but there's a basic html page too.
* Adds `search[url_matches]=...` and `search[normalized_url_matches]=...` params on the `/artist_urls` page. These params are overloaded such that if the input looks like `/pixiv/` it does a regex search, otherwise if it looks like `*pixiv*` it does a wildcard search, otherwise it does an artist finder search:
```
/artist_urls?search[normalized_url_matches]=/pixiv/
/artist_urls?search[normalized_url_matches]=*pixiv*
/artist_urls?search[normalized_url_matches]=https://www.pixiv.net/member_illust.php%3Fmode=medium%26illust_id=46503128
=> /artist_urls?search[normalized_url_matches]=http://www.pixiv.net/member.php%3Fid=9948/
```
* Adds the following search …

#3900: Allow to search for urls associated with artists using wildcards

---

app/models/post.rb

This is a fix for #3934. This lowers the fast count timeout from 3 seconds to 1 second, and removes the batched search fallback.
As discussed in #3934, IMO it's better to let fast count fail fast than to take a long time trying to determine the page count.

Fix #3934: Post#fast_count has very slow worst case behavior

---

app/logical/storage_manager.rb
app/models/post.rb
app/models/tag.rb
app/presenters/post_presenter.rb
app/presenters/post_set_presenters/favorite.rb
app/presenters/post_set_presenters/pool.rb
app/presenters/post_set_presenters/post.rb
app/presenters/tag_set_presenter.rb
app/presenters/upload_presenter.rb
app/views/comments/index.atom.builder
app/views/comments/partials/index/_header.html.erb
app/views/favorites/index.html.erb
app/views/moderator/post/queues/_post.html.erb
app/views/posts/index.html.erb
app/views/posts/partials/show/_edit.html.erb
app/views/posts/show.html+tooltip.erb
app/views/posts/show.html.erb
app/views/uploads/index.html.erb

This implements the third item in #3922. Currently the post show page does these queries:
* One call to the database to get the tag counts for the sidebar taglist.
* One call to memcache to get the tag categories for the sidebar taglist.
* Another call to memcache to get the tag categories for the tag string inside the post edit form.
* Another call to memcache to get the tag categories when generating the `humanized_essential_tag_string` (used for the page title and the image filename, among other things).
This basically moves all the code dealing with these tag lists into `TagSetPresenter`, so that the tags can be fetched from the database once and reused for all these things.
I think these memcache calls, though redundant, ultimately didn't contribute much to page render time, so this …

Optimize tag set presenters

---

app/logical/maintenance.rb
app/logical/monthly_maintenance.rb
app/logical/weekly_maintenance.rb
config/schedule.rb
lib/tasks/maintenance.rake
script/install/newrelic.yml
test/unit/maintenance_test.rb

Related to #3947 and #3413. This arranges for exceptions during hourly/daily/weekly maintenance tasks to be logged to NewRelic.
This works by changing `config/schedule.rb` to run `rake maintenance:daily` instead of running `DailyMaintenence.new.daily` directly. NewRelic will automatically instrument rake tasks, as long as you add this to your `config/newrelic.yml` to enable it:
```
rake:
tasks: ["maintenance:.*"]
```
After that, maintenance runs will show up in NewRelic Insights like this:
And exceptions will show up like this:

Improve daily maintenance error handling

---

db/migrate/20181202172145_set_columns_to_not_null.rb
db/structure.sql

Fixes #3998 by adding not null constraints to these columns:
* `artist_versions.other_names`
* `artist_versions.group_name`
* `artist_versions.urls`
* `artists.other_names`
* `artists.group_name`
* `wiki_pages.other_names`
* `wiki_page_versions.other_names`

Fix #3998: Some artist histories throw exceptions.

---

app/models/tag_implication.rb
test/unit/post_test.rb

Fixes #3995. The idea of automatically implying `*_school_uniform -> school_uniform` was discussed in https://danbooru.donmai.us/forum_topics/15769.

Fix #3995: Automatically imply *_school_uniform -> school_uniform.

---

app/helpers/application_helper.rb
app/helpers/artist_versions_helper.rb
app/javascript/src/styles/common/diffs.scss
app/logical/set_diff.rb
app/models/artist_version.rb
app/views/application/_diff_list.html.erb

Fixes #3946. This does two things:
* Unifies the code for diffing artist urls and artist other names.
* Groups together minor changes on the same line.
Example:
Here we have several active-to-inactive and http-to-https edits that are detected and grouped together.
It can also detect larger changes:
Here the stacc url is correctly detected as an edit of the old i2.pixiv.net url, and the Twitter handle uppercase-to-lowercase change is also detected.
This works by trying to pair each removed url with the added url that is closest in similarity, where similarity is measured by Levenshtein edit distance. The threshold is that two strings are considered similar if they're at least 25% the same (or in other words, at most 75% dissimilar).

Artist versions: improve diffing of urls and other names (#3946)

---

app/logical/upload_service/preprocessor.rb

in case both an upload from disk and a source were specified, this caused
an md5 mismatch error to be thrown
this seems to be necessary because, as I understand it, a upload record with the correct file (and md5) is already created before the form is submitted, but later not found because `predecessor` incorrectly returns  in the `if Utils.is_downloadable?(source)` branch (just checks whether source is http/https) which is taken if basically any source is present.
I have been testing this on my own instance for a few months now and haven't experienced any issues, but I would still appreciate someone looking over this.

#3767: Prioritize md5 check over source download

---

app/javascript/src/javascripts/autocomplete.js.erb
app/logical/post_query_builder.rb
app/models/artist_commentary.rb
app/models/comment.rb
app/models/note.rb
app/models/post.rb
app/models/post_appeal.rb
app/models/post_approval.rb
app/models/post_flag.rb
app/models/post_replacement.rb
app/models/tag.rb
app/models/upload.rb
test/unit/post_test.rb

Fixes #4004. This adds numerous metatags for searching by various kinds of counts:
* `comments`, `active_comments`, `deleted_comments`
* `notes`, `active_notes`, `deleted_notes`
* `flags`, `resolved_flags`, `unresolved_flags`
* `children`, `active_children`, `deleted_children`
* `pools`, `active_pools`, `deleted_pools`, `series_pools`, `collection_pools`
* `appeals`
* `approvals`
* `replacements`
All metatags can be used both for ordering (e.g. `order:notes`) and for searching (`notes:>5`). Ordering supports both ascending and descending directions (`order:notes_asc`, `order:notes_desc`). Negated searches aren't supported (`-notes:5` doesn't work).
`*_count` can be used as a synonym for any of these tags. For example: `order:note_count`, `child_count:>5`.
Most of these searches will be …

Fix #4004: Add additional order by metatags for posts

---

app/logical/moderator/ip_addr_search.rb
app/models/application_record.rb
app/models/ip_ban.rb
app/views/comments/partials/show/_comment.html.erb
db/migrate/20190109210822_rename_ip_addr_on_comments.rb
db/structure.sql
test/unit/ip_ban_test.rb

Fixes #4038:
* Rename comments.ip_addr to comments.creator_ip_addr.
* Fix belongs_to_creator to not clobber ip_addr field.

Fix #4038: Attempting to create an IP-ban bans the creator.

---

app/helpers/delayed_jobs_helper.rb
app/javascript/src/javascripts/blacklists.js

Fixes #4057. The **keeper_data** field was left as is in case it's still being kept around for other reasons, such as backwards compatibility. If it can be gotten rid of though, I can add a migration which will remove that value.

Remove references to Keeper/TopTagger

---

app/logical/pixiv_ugoira_converter.rb

since file is `nil` and has no `#close!` when `Danbooru.config.enable_image_cropping` is false
the more proper method might be to use a `begin; ...; ensure; file.close!; end` part around the parts related to `file`
I should really stop using the web editor... (in #4140 I changed the wrong `file.close!`)

Fix Ugoiras when image cropping is disabled

---

app/javascript/src/javascripts/post_mode_menu.js

Addresses the script storage from #3955. Additionally, there was an issue where the numeric keypad was setting the script ID as "a-z`", which was fixed by rebasing the value off of 0.

Change tag script storage

---

app/controllers/pool_versions_controller.rb
app/helpers/pool_versions_helper.rb
app/helpers/wiki_page_versions_helper.rb
app/javascript/src/styles/specific/pool_versions.scss
app/javascript/src/styles/specific/wiki_page_versions.scss
app/logical/diff_builder.rb
app/models/pool_archive.rb
app/views/pool_versions/_listing.html.erb
app/views/pool_versions/_secondary_links.html.erb
app/views/pool_versions/diff.html.erb
app/views/pool_versions/index.html.erb
app/views/pool_versions/search.html.erb
app/views/wiki_page_versions/diff.html.erb
config/routes.rb

Fixes #4224. Instead of adding another column, the pool versions index was made to be more like with wiki page versions index.  This also allows for multiple other status changes. Also, the logic for doing the diff for wiki page versions was moved out into a logic module so that it could be available for pool versions.

Add pool version enhancements

---

app/javascript/src/javascripts/notes.js

Fixes #3702. I went with the simpler option of just moving the dialog title to the dialog body.

Move note number to the body so that it can be copied

---

app/models/post.rb

I noticed the other day that the post model only had `uploader_id` and `approver_id`. That's because the post model was missed when all of the other models were converted over. I did a directory search and didn't find any other ones that didn't get done.

Fix missing post HTML attributes

---

app/models/comment.rb

Fixes #2728. Undeletion is now possible through the HTML interface by using the **is_deleted** search parameter. This fixes the other issue mentioned in #2728, namely that comments edited/deleted by moderators should not be editable/undeletable by users.

Lock comments edited/deleted by moderators

---

app/logical/table_builder.rb
app/views/artist_commentaries/index.html.erb
app/views/artist_commentary_versions/_listing.html.erb
app/views/artist_versions/_listing.html.erb
app/views/artists/index.html.erb
app/views/bans/index.html.erb
app/views/bulk_update_requests/_listing.html.erb
app/views/comment_votes/index.html.erb
app/views/delayed_jobs/index.html.erb
app/views/forum_post_votes/index.html.erb
app/views/ip_addresses/_index.html.erb
app/views/ip_addresses/_index_by_ip_addr.html.erb
app/views/ip_bans/index.html.erb
app/views/news_updates/index.html.erb
app/views/note_versions/_listing.html.erb
app/views/pool_versions/_listing.html.erb
app/views/pools/index.html.erb
app/views/post_appeals/index.html.erb
app/views/post_approvals/index.html.erb
app/views/post_flags/index.html.erb
app/views/post_replacements/index.html.erb
app/views/post_versions/_listing.html.erb
app/views/post_votes/index.html.erb
app/views/tag_aliases/_listing.html.erb
app/views/tag_implications/_listing.html.erb
app/views/tags/index.html.erb
app/views/user_feedbacks/index.html.erb
app/views/user_name_change_requests/index.html.erb
app/views/users/index.html.erb
app/views/wiki_page_versions/_listing.html.erb

This primarily adds a column parameter for use on columns which have no header name. With this, the **th** and **td** parameters don't have to be used to set the column class. This also prevents extremely long class names from being created, e.g. on the post versions view: (`label-input-type-checkbox-id-post-version-select-all-checkbox-class-post-version-select-checkbox-label-column`). It then adds missing column classes for all applicable tables.
Next , it standardizes the use of the width parameter for the column parameters to not use surrounding curly braces.
Finally, it fixes up the note versions index to remove the unneeded empty column and fix the search by post ID and note ID links so that they appear whenever not searching by that parameter, which includes the vanilla index …

Update HTML table column attributes

---

app/controllers/uploads_controller.rb
app/javascript/src/javascripts/uploads.js.erb
app/javascript/src/styles/specific/uploads.scss
app/logical/upload_service.rb
app/views/uploads/new.html.erb
db/migrate/20200114204550_add_more_commentary_to_uploads.rb
db/structure.sql

Fixes #2794. In addition to the request from that issue, several other enhancements were made to the upload interface for artist commentaries.
1. Can now translate commentary from the upload page
Sometimes the translator is the one uploading. This facilitates adding the translation in one step instead of having the multiple step process of submitting the upload, waiting for the post to be created with a page reload, then adding the commentary with another page reload.
The translated section starts out hidden by default, and the control to show the translated section is only shown if the commentary section itself is shown.
2. Can now add commentary tags with a checkbox
The checkbox names are the same as those on the add commentary dialogue. The tags involved with just the original section …

Add upload commentary enhancements

---

app/models/application_record.rb
app/models/artist.rb
app/models/tag.rb
app/models/tag_relationship.rb
app/models/wiki_page.rb

Fixes #4227. It basically adds in support for URL array parameters for both text and array fields. Besides that it also adds in different string splitters for text fields, since that may be shorter and work better under many conditions.
This is a slightly breaking change since a parameters had to be renamed, or are now covered under one of the new parameter name formats. However, this now makes the base name parameter more standardized across models.

Add ability to search for multiple name values on the same field

---

app/controllers/application_controller.rb
app/controllers/artists_controller.rb
app/controllers/pools_controller.rb
app/controllers/users_controller.rb
app/controllers/wiki_pages_controller.rb
app/helpers/application_helper.rb
app/views/artists/_secondary_links.html.erb
app/views/pools/_secondary_links.html.erb
app/views/users/_secondary_links.html.erb
app/views/wiki_pages/_secondary_links.html.erb

Fixes #4204. This is a more comprehensive version of 6e5e070. 
- It allows users to redirect to the show page on all controllers that have index and show actions.
- It also fixes the quick search forms so that the redirect parameter is accurate to the intended purpose of the search
- I.e. whether it will redirect or not if only one match is found.
- Only the search parameters for the quick search forms are being handled specially in the controller.
- The use of any other search parameters will redirect as long as only one result is returned when the redirect parameter is true.
- This should be fine as long as users are aware of that.
- All of the controllers with index actions had their render functions replaced even if they didn't have a show action
- This is just in case a show action …

Add universal index redirect

---

app/controllers/wiki_pages_controller.rb

It was fixed on the quick search form with 217f5e6 but wasn't fixed on the parameter checking in the controller.

Fix title parameter checking

---

app/models/application_record.rb

It does the by performing a lowercase on the text, so the user of these params must also do a lowercase on their end before sending the query.
This has the immediate use case of searching batches of wiki page other names, as is a need with [Translate Pixiv Tags](https://github.com/evazion/translate-pixiv-tags).

Add parameters for searching attributes by array with case insensitivity

---

app/javascript/src/javascripts/autocomplete.js.erb

It was removing line returns, even when line returns are important, such as in the blacklist and frequent tags input fields.
Besides those, it was also causing confusion when editing tags on a post, as those are divided into categories, but adding an additional tag for a category at the end of a group causes groups of tags to be combined.

Fix autocomplete insert completion

---

app/views/users/index.html.erb

I noticed this the other day when working on the only parameter but didn't remember to include it in (plus it was unrelated to that PR).
I thought about how to get rid of the SQL queries for the deleted count, but there's really no good way to do it without adding another integer column on the **User** model, and it wouldn't be worth it because it's not really used anywhere else.

User: Use model counts instead of SQL queries

---

app/views/posts/partials/index/_excerpt.html.erb

fixup ef3188a7fe33b300f322de91e635990d04b1ba7b
as it is now it complains about an "undefined method `notes' for #<Artist:0x0559f488>" when searching for an artist for me (on my instance of course)
similar change in original commit: https://github.com/danbooru/danbooru/commit/ef3188a7fe33b300f322de91e635990d04b1ba7b#diff-9f43d1c0ee59f857f7a54b37a798d7a4L8-R10
not sure if this is the correct way to fix this but at least it doesn't throw an error anymore
~~I can't guarantee I haven't somehow made a mistake again when copying into the web editor (easier this way)~~

fix leftover reference to Artist.notes

---

app/logical/related_tag_query.rb

This queries the base tag when any `*_(cosplay) ` tag gets queried. Beforehand, if a user wanted to get the tags of the base tag (such as the costume), the user had to type out the base tag in addition to the `*_(cosplay)` tag. This is extra work for the user, plus it also wastes the current auto-implication capability where it automatically adds the base tag when the cosplay tag gets added.
Besides the above, it also fixes an existing issue when selecting other wikis, since if the `list_of_*` wiki does not actually exist, then the queried tag will generate an exception and not deliver any results.

Add cosplay related tags for other wikis

---

app/javascript/src/javascripts/notes.js

As mentioned by **Arcana55** on Danbooru ([forum #1234](https://danbooru.donmai.us/forum_posts/163316)), the note resizing is also affecting non-embedded-notes. This is because there was a missing embedded check in the scale all function.

Restrict note container resizing to embedded notes

---

app/helpers/note_versions_helper.rb

The size transition should only be shown on size changes, and the position transition should only be shown on position changes.

Only show dimension transitions on relevant changes

---

app/javascript/src/javascripts/notes.js
app/javascript/src/javascripts/posts.js.erb
app/javascript/src/styles/base/040_colors.css
app/javascript/src/styles/specific/notes.scss

Fixes #4235. In addition to the items there, it also adds the much needed key functions for nudge and resize. It also adds a few settable styles beyond background color on the note box itself, which facilitates having different shapes and orientations of the box. It does this by copying certain styles of the first element with the class of **note-box-attributes** that it finds in the note text if it exists.
Several style manipulations were converted to using classes instead of setting styles on the elements themselves, which allows for easier maintenance and setting of multiple styles at once. For the note preview function, the font-size of the parent inner box is set to the base font size (set at page load) so that the size calculations can be done correctly, and afterwards it clears …

Add embedded notes improvements

---

app/javascript/src/javascripts/notes.js

Beforehand it was always using the left corner, which was causing the note body to be to the right of the note box whenever the bottom angle of the note box was descending.
Now it selects the left or the right corner depending on the angle, which keeps the note body in a better position right beneath the note box.

Fix embedded note body position 

---

app/javascript/src/javascripts/blacklists.js
app/javascript/src/javascripts/posts.js.erb
app/javascript/src/javascripts/related_tag.js
app/javascript/src/javascripts/utility.js
app/javascript/src/styles/common/blacklists.scss
app/views/posts/update.js.erb

Fixes #4323. Besides that, it also adds several other improvements.
1. Fixed several issues with the post update JS render
2. Fixed multiple performance issues with the blacklist apply function being applied multiple times
3. Refactored regexp split used in several places into its own utility function
4. Adjust how classes get added and renamed the classes on the links to be more accurate
5. Used alternate iterators as `$.each` is a subpar performer
<hr>
One thing I realized doing this is that module functions/variables are referred to in a lot of places with **this** which is dangerous with the current standard format. Since most of the anonymous functions use the full function format instead of arrow functions, the **this** inside those refer to the anonymous function instead of the …

Update blacklist controls

---

app/controllers/related_tags_controller.rb
app/logical/related_tag_calculator.rb
app/logical/related_tag_query.rb
app/logical/tag_category.rb
app/models/tag.rb
test/unit/related_tag_calculator_test.rb

Fixes #4321. It also adds some other enhancements.
1. Included tag overlap
This is a separate hash so that the values can be quickly looked up. There is no extra processing involved since the SQL queries already adds that information to the tag instances. There's no reason and no easy way to add those for pattern matching, so those types only return a blank hash.
2. Variable limit
The default is still 25.
3. Settable type
The user can now specify which type they want to use, regardless of the format of the query or whether a category is specified or not. It also fixes it where the category type wasn't settable for pattern matching.
4.  Included sample count
This is the amount of samples that were actually used in the calculations. Since the sample size is not always the maximum, the query …

Related tag enhancements

---

app/controllers/forum_topics_controller.rb
app/helpers/forum_topics_helper.rb
app/models/forum_topic.rb
app/views/forum_topics/_listing.html.erb

Fixes #2751.
A class for each BUR status type is supplied so that the user can style the counters themselves if they want to. The widths percentages were fine-tuned using up to 3 digits for all 3 values, so there should be plenty of room for growth.
On a side note, with this BUR counter scheme, the **[Approved]** and other markers that currently get prepended onto topics could be done away with. If that's something that is desired, then more commits can be added onto this PR, or it can be done as a separate PR/commits.
If such is the case, should all of the old topics titles be cleaned up to strip out those markers if they exist as well with a fixup script? It's true that there's no indication for failure with the BUR counters, however a forum post indicating such is already being added. …

Add BUR counters to forum topics index

---

app/javascript/src/javascripts/notes.js
app/javascript/src/javascripts/posts.js.erb
app/javascript/src/styles/base/040_colors.css
app/javascript/src/styles/specific/notes.scss
app/javascript/src/styles/specific/posts.scss
app/javascript/src/styles/specific/z_responsive.scss
app/views/posts/partials/show/_options.html.erb
app/views/users/edit.html.erb

Created this PR based on prior discussions on Discord with @evazion about the reversion of a commit with 4b9a297. Basically, the note boxes were converted from using exact coordinates into using percentages instead. This facilitates a much easier resizing of the note boxes, and allows for much of the Javascript resizing code to be removed. The only resizing required now is on the note container itself, needing its size updated to match the underlying image, as well as updating the font size based on the size ratio.
To accomplish this, several style elements had to be changed or removed. All style elements were removed from the inner box, both to unify all style elements on the note box itself, but also because any height or width styles set on the inner box heavily conflicted with getting …

Convert notes to use percentages instead of exact coordinates

---

app/controllers/application_controller.rb
app/controllers/post_versions_controller.rb
app/helpers/post_versions_helper.rb
app/javascript/src/styles/base/040_colors.css
app/javascript/src/styles/specific/post_versions.scss
app/models/post_version.rb
app/views/post_versions/_listing.html.erb
app/views/post_versions/index.html.erb
app/views/post_versions/search.html.erb

Fixes #4364, fixes #4365, fixes #4366. 
1. Alternate post versions HTML format
Converts the column **Tags** and places all of the current state of the post at that time (to included unchanged tags) into it. It also supports tag categories and was partially based off of the display for comments.
Adds an additional column **Edits** and lists only the actual items that were added and removed for that particular post version. It also does away with the "+" and "-" to facilitate ease in copying. Finally, it brings back the "obsolete" category for the "subsequent" and "previous" views.
The "previous" mode does not have any additional comparisons to make against since those are the comparison values, so it has no "obsolete" category. No tag changes are shown on the "New" versions even though the …

Various post version fixes

---

app/views/favorite_groups/_secondary_links.html.erb
app/views/favorite_groups/show.html.erb

also link to the proper post search with `status:any`
fixes #4347
I don't particularly care for this change but someone requested it, so why not
---
Alternative:
* make `favgroup:` return everything even without `status:any`
* more complicated

Show deleted posts for favorite groups

---

app/views/favorites/_update.js.erb

Not sure if this is at all the proper way to do this, but it seems to work(?)
When favoriting/unfavoriting a post, it would also be upvoted/"un"voted internally but the upvote/downvote/undo vote buttons would stay shown/hidden as they were before unlike when pressing those buttons.
For example when you want change from favorite to merely upvoted you would have to reload the page in between.
Condition taken from here: https://github.com/danbooru/danbooru/blob/6d615001e4fcfdeb123f0f64cc47f3f30a044fed/app/views/posts/partials/show/_information.html.erb#L29
JS taken from: https://github.com/danbooru/danbooru/blob/6d615001e4fcfdeb123f0f64cc47f3f30a044fed/app/views/post_votes/create.js.erb#L4-L5
and https://github.com/danbooru/danbooru/blob/6d615001e4fcfdeb123f0f64cc47f3f30a044fed/app/views/post …

Show or hide post vote buttons when (un)favoriting

---

app/models/post.rb

This normalizes the following urls:
* https://twitter.com/ichizon7/status/1244475516180021248/photo/1 (caused by clicking on a picture) ([15k posts](https://danbooru.donmai.us/posts?tags=source%3A*twitter*%2Fphoto%2F*&ms=1 ))
* https://twitter.com/ichizon7/status/1244475516180021248?s=20 (the number is variable, typically between 18-20 but I've seen other numbers too. Used to track the type of device it was shared from)  ([600 posts](https://danbooru.donmai.us/posts?tags=source%3A*twitter*%3Fs%3D*&ms=1)) 
* https://mobile.twitter.com/ichizon7/status/1244475516180021248 (regularly fixed by multiple users, should be done server-side) 
It also normalizes urls with an ending slash (https://mobile.twitter.com/ichizon7/status/1244475516180021248/).

Post#normalized_source: Normalize more twitter urls

---

app/logical/sources/strategies/tumblr.rb

`photo[:alt_sizes]` may contain a bigger image than
`photo[:original_size]`
fixes #4324

tumblr: pick biggest image based on resolution

---

app/logical/sources/strategies/art_station.rb

Fixes an issue with urls like https://hosi_na.artstation.com/projects/3oEk3B where the site gives up when getting the api response (so we miss the commentary, tags etc).
See: https://danbooru.donmai.us/source.json?url=https://hosi_na.artstation.com/projects/3oEk3B

Artstation: artists can have underscore in their name

---

app/logical/sources/strategies.rb
app/logical/sources/strategies/hentai_foundry.rb
test/unit/sources/hentai_foundry_test.rb

Also fixes #3437.
My first real contribution. Hopefully I didn't make too many mistakes.
I wasn't sure how much testing was required so I tried to cover all user cases I could think of. 
For the agent, it's basically useless to try and cache the cookie that allows browsing, because it expires extremely fast even on normal browsers.

Add hentai-foundry support

---

app/logical/deviant_art_api_client.rb
app/logical/sources/strategies.rb
app/logical/sources/strategies/deviant_art.rb
app/logical/sources/strategies/stash.rb
config/danbooru_default_config.rb
test/unit/artist_test.rb
test/unit/sources/deviant_art_test.rb
test/unit/sources/stash_test.rb

Since I never got any replies to any of my comments anywhere I just implemented it how I would find it acceptable since it's been broken for about half a year now (#4219).
I chose to get rid of the JS backend API client (`extended_fetch`) entirely as not to have two clients (for one). This meant I might as well go back to before it was introduced as a known good state. See https://github.com/danbooru/danbooru/issues/4431#issuecomment-621518209 for details.
This first reverts `app/logical/sources/strategies/{deviant_art,stash}.rb` to how they were in 7f482dc35bc7b77bce580ec06b4b708d49d3a29a with some very minor changes. I couldn't figure out how to to this other than `git checkout $commit -- $files`
Counting redirects this makes 3-5 non-image requests for what was 1-2 with `extended_fetch` …

Fix Deviantart

---

app/logical/sources/strategies/nijie.rb
test/unit/sources/nijie_test.rb

Reported by Zurreak on discord.
Examples: 
http://nijie.info/view.php?id=370424 ([Link to source.json](https://danbooru.donmai.us/source.json?url=http://nijie.info/view.php?id=370424))
http://nijie.info/view.php?id=266532 ([Link to source.json](https://danbooru.donmai.us/source.json?url=http://nijie.info/view.php?id=266532))
The og:description property is truncated with "..." after a certain length.
We have a few of these truncated commentaries on site:  `https://danbooru.donmai.us/artist_commentaries?commit=Search&search%5Bpost_tags_match%5D=source:*nijie.info*+&search%5Boriginal_description_regex%5D=\.\.\.$&limit=1000`. They'll have to be fixed manually afterwards.
Since the title field is limited to 100 characters, it's never truncated, so that can be left as it is.

Nijie: fetch full commentary rather than truncated preview

---

app/controllers/iqdb_queries_controller.rb
app/logical/iqdb_proxy.rb

Mentioned as an item that needed fixing in issue #4328.
Basically, there was no support for the **image_url** parameter. In addition to fixing that, it adds in support for a **file_url** parameter, which always selects the largest available size.
So all told, the parameters will be:
- `url` - The preview URL size
- `file_url` - The download/largest URL size
- `image_url` - The size as specified by the input URL

Adds suport for using the image_url parameter with IQDB

---

app/javascript/src/styles/common/fonts.css
package.json
yarn.lock

Part of #4212.  Discussed on [topic #16435](https://danbooru.donmai.us/forum_topics/16435) and Discord's [#translations](https://discordapp.com/channels/310432830138089472/390639683119480863/713152504283529756).
I went with the IBM Plex Mono as suggested by Shinjidude as it looked about the right amount of robotic, plus the italic version looks pretty interesting.

Add monospace font

---

app/logical/media_file/flash.rb

When uploading a flash file you get a ``error: NoMethodError - undefined method `unpack' for nil:NilClass``.
This is because `#dimensions` is called twice - in `#width` and in `#height` which is a problem because the first time it gets called file  is consumed by `#read` and thus the second time it gets called `#read` just returns the empty string.
This would be solved by memoizing `#dimensions` but that's not what I did since it still consumes the file and while (I think) it doesn't get used (without rewinding) right now who knows what you might want to do with it in the future.
You could `#rewind` it of course but I chose to open it again with `File.read` and not mess with `file` at all (though I doubt you have to worry about thread-safety) (like the other subclasses).
(I would prefer …

Fix flash dimensions

---

app/logical/artist_finder.rb
app/logical/sources/strategies.rb
app/logical/sources/strategies/weibo.rb
test/unit/sources/weibo_test.rb

Fixes #4476.
It uses the mobile internal api, because the real Weibo api is overly complicated and apparently it's impossible to set up authentication without full OAuth2 redirection, which is well beyond our use case.
There are some weibo posts that are unsupported. There's two different types of unsupported:
* those that require log in, e.g. [this one](http://photo.weibo.com/5457245914/wbphotos/large/mid/4227012979213138/pid/005Xk2Xogy1fq6quaycpbj30t61jkkjm)
* those for which the api can only be accessed through base62, e.g. [album link](http://photo.weibo.com/6192798570/talbum/detail/photo_id/4287009158189036) -> [base62 link](https://www.weibo.com/6192798570/GAvvlnSyP) (the [mobile ID link](https://m.weibo.cn/detail/4287009158189036) redirects to a 404).
For the second category, it's …

Add Weibo support

---

app/javascript/src/javascripts/notes.js

Fixes #4408. Explanation is in the commit message.

Fix notes having absolute coordinates upon creation

---

app/logical/sources/strategies/deviant_art.rb
test/unit/sources/deviant_art_test.rb

Reported on discord.
Fixes posts like [post #3632694](https://danbooru.donmai.us/posts/3632694) or https://www.deviantart.com/akizero1510/art/Ten-miles-of-cherry-blossoms-792268029 not working with the batch bookmarklet (not getting the correct source, commentary, tag etc), because they didn't match the right wixmp host.

Deviantart: fix api downloads

---

app/logical/pixiv_api_client.rb
test/unit/sources/pixiv_test.rb

This is not needed anymore. It used to be that those tags bled into the tags for when the software interface appears in the picture, but as we have translated tags for digital mediums now it should be fine.

Pixiv: don't blacklist digital tools anymore

---

config/danbooru_default_config.rb

Added resolution_mismatch + children and the missing_image/sample/thumbnail tags, since replacements for old posts were fixed and now those posts can be replaced again.
Fixes #4509.

Add more tags to post replacements filtering and modqueue highlighting.

---

app/logical/sources/strategies/null.rb

For some reason we were only normalizing jpgs.
Example: https://danbooru.donmai.us/posts/3959654

Zerochan: Normalize png links

---

app/logical/pixiv_api_client.rb
test/unit/sources/pixiv_test.rb

It was worth a try, but unfortunately it seems that once someone sets tools in a Pixiv upload, they become defaults and are applied to all of their subsequent uploads, so we get some posts with two or three different digital tags.
It's pretty easy to fix by simply comparing the metadata, but it's not worth it to have it autotranslated since some users just blindly click all related tags.

Revert "Pixiv: don't blacklist digital tools"

---

app/views/artists/_show.html.erb
app/views/wiki_pages/show.html.erb

Fixes #4526. It also fixes the reverse situation, i.e. a wiki's artist is deleted.

Don't display artist wiki when it is deleted

---

app/models/post_version.rb
test/functional/post_versions_controller_test.rb

Fixes #4533. The issue was the split function was mistakenly used instead of the match function.

Fix the tag matches option

---

app/models/wiki_page.rb
app/views/wiki_pages/search.html.erb

I encountered the need for this usecase the other day when searching for meta-wikis that don't currently link to the [list of meta-wikis](https://danbooru.donmai.us/wiki_pages/list_of_meta-wikis) wiki page. Beyond that specific usecase, it can also be used for other umbrella wikis to find wikis that don't currently have links so that they can be added.
In regards to those type of scenarios, both the linked to and not linked to search parameters were added to the wiki search page to aid the normal user.

Add option to search for wikis that don't link to a specific wiki

---

app/javascript/src/javascripts/autocomplete.js.erb
app/logical/post_query_builder.rb
test/unit/post_query_builder_test.rb

Fixes #4474. 
Besides searching for the status of parent, it also adds the ability to search by status of child.

Add ability to search on status of parent/child

---

app/models/artist_url.rb
test/unit/artist_url_test.rb

Fixes #4192. The problem was that the Addressable parser does not catch all invalid URL cases.
I used the following page in part of my search for a regex URL validator.
https://mathiasbynens.be/demo/url-regex
The one provided by **diegoperini** seemed to be the best.
https://gist.github.com/dperini/729294
One of the responders there mentioned creating a Ruby gem, which seems like the easiest to incorporate and maintain.
https://github.com/amogil/url_regex

Fix invalid artist URLs being allowed

---

app/logical/sources/strategies/deviant_art.rb
app/logical/sources/strategies/nico_seiga.rb
app/logical/sources/strategies/nijie.rb
app/logical/sources/strategies/pawoo.rb
app/logical/sources/strategies/pixiv.rb
app/logical/upload_service/preprocessor.rb
app/logical/upload_service/utils.rb

Avoid returning bare API traceback from pixiv et al when login details are not configured, and instead raise a generic error with the site's name.
There already was a skeleton implementation for this so I just added the missing functions for all relevant strategies.
Fixes #4545.

Uploads: Check if strategy is enabled before use

---

app/javascript/src/javascripts/post_tooltips.js
app/javascript/src/javascripts/user_tooltips.js
app/views/layouts/default.html.erb

When Tippy is delegated to the same element more than once, that prevents the destroy method from working, which makes it so that users cannot change the settings and then reinitialize the tooltips.
To this end, each `delegate()` call is now given a different selector. Additionally, the tooltips are given their own separate `<div>`'s so that something like the second `delegate() `call in the UserTooltips module can be given its own unique selector.

Fix tooltips to allow for reinitialization

---

app/models/post_version.rb
app/views/post_versions/index.html.erb
app/views/post_versions/search.html.erb

This will facilitate users being able to monitor tag changes from a list of tags they are interested in. Currently, the only way to do this is 2 separate queries on the added_tags and removed_tags.
For the record, I would be able to use this with my [EventListener userscript](https://github.com/BrokenEagle/JavaScripts/blob/master/eventlistener.user.js). Currently, the user can only search for a list of added tags, a list of removed tags, but not both at the same time unless a tag from both lists appears on the post version, which limits its use.

Add search for a list of any changed tags

---

app/logical/sources/strategies/nijie.rb
test/unit/sources/nijie_test.rb

Fixes a regression in 6e6ce6e62f79f0c97251d4e1012009f8c138e021 that broke logging in.
Fixes #4543.
Also raises nijie timeout to 60 seconds because the site is often hella slow.

Nijie: fix login

---

app/logical/upload_limit.rb
app/views/users/_upload_limit.html.erb

Upload limit: don't display progress in tooltip when maxed out

---

app/models/post.rb

Right now we're only copying the *_translation tags when copying notes, but we also have the various *_annotation tags.

Copy annotation tags when copying notes

---

app/views/users/_statistics.html.erb

It's pretty useful as an approver to have a quick link to an user's appeals, and there's no reason to hide the count since appeals are public.

Users: show appeal link and count to everyone

---

app/logical/sources/strategies/tumblr.rb
test/unit/sources/tumblr_test.rb

Tumblr: support highest res for new image urls

---

app/logical/concerns/searchable.rb

Parameter arrays are causing errors because they also respond to `each`.
https://danbooru.donmai.us/artist_urls.json?search%5Bnormalized_url_lower_array%5D%5B%5D=http%3A%2F%2Ftwitter.com%2Fkozomeeeee%2F&only=normalized_url%2Cartist%5Bid%2Cname%2Cis_deleted%2Cis_banned%2Cother_names%2Curls%5Bnormalized_url%2Cis_active%5D%5D&limit=1000
```json
{
"success": false,
"message": "undefined method `values' for [\"http://twitter.com/kozomeeeee/\"]:Array\nDid you mean?  values_at",
"backtrace": ["app/logical/concerns/searchable.rb:9:in `parameter_depth'","app/logical/concerns/searchable.rb:10:in `block in parameter_depth'","app/logical/concerns/searchable.rb:10:in `map'","app/logical/concerns/searchable.rb:10:in `parameter_depth'","app/logical/concerns/searchable.rb:151:in …
```

Fix parameter hash detection

---

app/logical/sources/strategies.rb
app/logical/sources/strategies/fanbox.rb
app/logical/sources/strategies/pixiv.rb
test/unit/sources/fanbox.rb
test/unit/sources/pixiv_test.rb

Fixes  #3912. Fixes #4316.
Unfortunately age-restricted posts are not possible to support, because they require login and that's hidden behind ReCaptcha v3 nowadays, which is impossible for us to work around.
Other projects like PixivUtil ask the user to submit their cookie, but that's not a viable strategy for us, so if we figure out how to work around the login to fetch the metadata it can always be updated.
I've opted to raise an error for R18 posts so that the user understands what's going on if the upload fails.
There's no `match?` for the Fanbox strategy despite the fact that it gets pixiv.net and piximg.net pictures, because those domains are already captured by the Pixiv strategy, and the only thing that filters down is urls with the "/fanbox/" url in it.
Cover and profile images …

Add (partial) fanbox support

---

app/logical/artist_finder.rb
app/models/artist_url.rb

Fixes #4551. 
This allows us to get rid of the tons of horrible fc2 urls structured like "https://blog.fc2.com/a/a/a/aaaaaaaaaako/" (just look at the [/a/ entries](https://danbooru.donmai.us/artist_urls?commit=Search&search%5Border%5D=id&search%5Burl_matches%5D=%2Afc2.com%2Fa%2F%2A)) that have plagued the artist urls for years, and merge them all into a standard "https://artist_name.blog.fc2.com".

Fix blog.fc2 urls matching wrong artists

---

app/logical/artist_finder.rb
test/unit/artist_test.rb

Fixes #4621. 
Also adds blacklist for https://baraag.net and updated tests for /en/ pixiv links.

Update artist finder blacklist

---

app/logical/sources/strategies/weibo.rb

Fixes weibo previews not being shown in the batch upload page.
Example: http://danbooru.donmai.us/uploads/batch?batch%5Burl%5D=https%3A%2F%2Fwww.weibo.com%2F5362351387%2FJvzzbhnrc&commit=Fetch

Weibo: use proxy for upload previews

---

INSTALL.debian

gcc, g ++ is required to building
Add [^ -] to exclude duplicate.
Example:
PostgreSQL 11.9 (Debian 11.9-0+deb10u1)

Update: INSTALL.debian

---

app/logical/sources/strategies/null.rb
test/unit/sources/null_test.rb

At some point, not sure when, Gelbooru changed the way md5 searches work. I just noticed this while going through the queue.

Fix gelbooru source normalization

---

app/logical/upload_service/preprocessor.rb

Fixes #4409. 
I really tried to understand why these lines are in the code but for the life of me I couldn't figure it out. The github blame function only goes back to 3 years ago when the preprocessor.rb file was created.
These lines are not needed to stop duplicate uploads, because the md5 check does the same. At first I thought they stopped duplicate preprocessing, but after some tests I realized those were being created regardless of the lines being there. 
The only thing they do from what I could tell is stop replacements if the same source already exists, which basically breaks replacements in many cases unless you empty the source field before replacing and fix it afterwards (which is slowly making me insane with all the e-hentai replacements being cockblocked by this). And this …

Uploads preprocessing: get rid of same-source existence check

---

app/logical/concerns/searchable.rb

Fixes #4638.
Adds support of multiple excludes for integer, enum, and inclusion types.

Add Support For Multiple excludes

---

config/docker/Dockerfile.danbooru
config/docker/docker-compose.test.yaml

with these fixes, the suggested docker-compose command actually succeeds and runs tests to completion; tested on a fresh ubuntu 20.10 installation.

fix docker config

---

app/views/posts/partials/index/_related.html.erb

Fixes #4692. 
Makes the logic for displaying the tag history behave similarly to the one for showing the wiki in https://github.com/danbooru/danbooru/blob/054ac51d471b192cdc5136b82bb1a5c939bd7332/app/logical/post_sets/post.rb#L27-L28
Basically we still want to display the link if someone searches for the negated tag or with additional metatags like status.

Post sidebar: ignore metatags for the tag history link

---

app/logical/sources/strategies/twitter.rb

The artist name is supposed to be the display name according to the base file, however the artist name was treated like the tag name instead. This commit renames all instances of "artist_name" to "tag_name" and then adds an `artist_name` function that uses the Twitter display name if available.

Add the Twitter name to the list of other names for new artists

---

app/controllers/application_controller.rb
app/controllers/emails_controller.rb
app/models/email_address.rb
app/models/forum_topic_visit.rb
app/models/saved_search.rb
app/models/tag_implication.rb
app/models/user_event.rb

I noticed that I had missed the `parent_implications` and `child_implications` associations because I didn't thank that the `tag_implication` had additional relationships beyond those in the `tag_relationship` model. I didn't add those to a **search_attributes** call in the **search** function because it already has `implied_to` and `implied_from` which should cover most of that.
Beyond that, I also added in a few other related items.
- Searched for other missing usable associations and added those.
- Removed unncessary associations. 
- Converts non-converted ID fields to the association names instead.

Add missing associated attributes

---

app/models/user.rb

Fixes Member appearing before Restricted in the user search. This thing:

Fix ordering of user levels in user search

---

app/components/tag_list_component.rb

There's 4629 of these tags with a single post as of the opening of this pull request. Doesn't make much sense for us to mark them as low post count since they're legitimate even when there's a single post, just like their corresponding character tags.

Don't mark cosplay/style tags as low post count

---

app/views/ip_bans/index.html.erb

Fixes #4705 by formatting the reason in the same way as the Bans page.

IP Bans: format reason via dtext

---

app/views/users/_statistics.html.erb

Something that's bugged me for a while. The current sample links use limit:300, but the max limit is 200.

Use correct post limit in the sample links for mods in user profiles

---

app/logical/sources/strategies/fanbox.rb
test/unit/sources/fanbox_test.rb

R18 posts are now supported, without us needing to change anything, because fanbox now exposes all the necessary data in the api. No idea when they started working properly.
* fix the test for R18 posts, which are now supported
* replace the dead post for the imageMap test with an active one
* fix the ordering of images: it was possible to get the wrong image in some cases when not using the batch bookmarklet, because fanbox orders imageMap alphabetically based on ID, not based on position. We need to get the proper order from another section of the api and use it as an ordering key.
* fix a bug where the sample wasn't properly replaced with the full size
* rename test file to match the rest of the other test files

Fanbox: fix tests and a bug with image ordering in the bookmarklet

---

app/helpers/bulk_update_requests_helper.rb
app/views/bulk_update_requests/_form.html.erb

The BUR form was never updated to show rename or nuke. 
Also since I was editing the file anyway I fixed the rubocop warning for meaningful heredoc delimiters.

Updates the BUR form to reference the new commands

---

app/logical/sources/strategies/mastodon.rb
test/unit/sources/mastodon_test.rb

Fixes a bug for Baraag.net that caused the batch bookmarklet to always pick the first picture in multi-image posts.

Baraag: fix image regex

---

app/logical/sources/strategies/mastodon.rb
test/unit/sources/mastodon_test.rb

Accidental regression in 5366b0781ee4989d3d4fadb90445feaa89fea62e. Since we were not checking the referer, it's saving all sources as /web/statuses rather than the normal form. A minor issue, but still.

Sources: get correct mastodon page url

---

app/logical/sources/strategies.rb

Right now, whenever a source is evaluated, it goes through all the match functions in each strategy, even if the first strategy matches the url. 
Using [lazy.map](https://ruby-doc.org/core-2.7.0/Enumerator/Lazy.html) the function instead aborts the moment it finds a match.
Lazy enumerators are slightly slower if the match is at the end of the array, as the following tests report, so performance worsens for last two or three strategies and unmatched posts, but on danbooru Pixiv alone makes up [2.82M posts](https://danbooru.donmai.us/counts/posts?tags=pixiv%3Aany+status%3Aany), with another 550k from Twitter, so the performance gain is ultimately positive because the vast majority of posts is matched by the first few strategies (I reordered them so they match usage).
For the last year, for …

Optimize Sources::Strategies.find()

---

app/presenters/user_presenter.rb
app/views/users/_statistics.html.erb

It's a real pain when you're looking at a user and are trying to see if they're doing something bad or want to view their edits in detail for certain tags, but you have to navigate back to the expanded search form or add the user name manually again because the URL you get from their profile uses the ID, but the field in the search form uses the name, so it's not automatically populated.
This makes it so that when you click on an user's edits from their profile, you get the name properly autofilled.

User profiles: use name instead of id in links to post edits

---

app/logical/mastodon_api_client.rb
app/logical/sources/strategies/mastodon.rb
test/unit/sources/mastodon_test.rb

This bug has been present for a long time, but it was only reported recently. It would only become visible to end users if you tried to make an artist page directly after uploading a post with only the direct link, otherwise it would fail silently.
Also updates the tests and catches an exception for certain 404 urls.

Mastodon: fix strategy raising an exception for direct links

---

app/models/tag_implication.rb

The default category for empty tags is general, so implications are otherwise always going to be rejected when the tag is created via BUR beforehand.
Ref: https://danbooru.donmai.us/forum_topics/18013?page=2#forum_post_182107

BURs: don't check for category when implicating empty tags

---

app/logical/sources/strategies/pixiv.rb
test/unit/sources/pixiv_test.rb

Pixiv: don't add auto-generated usernames to the other names field

---

app/javascript/src/javascripts/notes.js
app/javascript/src/styles/specific/notes.scss.erb

Partial fix of #4741.
This will allow for the stack order of embedded notes to be determined via the user. Currently, the order is determined by the order they get rendered, which makes it hard to precisely work with embedded notes, especially since overlap is sometimes impossible to avoid.

Add ability to determine stack order of embedded notes

---

app/views/posts/partials/show/_delete_dialog.html.erb

I've noticed that several approvers (mods included) don't realize that deleting a pending posts takes 5 uploads slots, and what's worse some don't realize that they should not delete posts just because they're status:banned.
Just like the flag and appeal notice, having an embed wiki in this dialog could help preventing these mistakes.

Add embed wiki to delete dialog

---

app/models/tag_alias.rb
test/unit/tag_alias_test.rb

Ref: https://danbooru.donmai.us/forum_topics/18277, https://danbooru.donmai.us/forum_topics/18278
When aliasing a to b, remove an eventual implication from a to b as well.
Not sure if there's a simple way to get both implication directions in a single line, I couldn't find any way without having to use raw SQL.

Tag Aliases: automatically remove redundant implications

---

app/logical/sources/strategies/skeb.rb
test/unit/sources/skeb_test.rb

Skeb added support for multi-image posts. Fixing the strategy was fairly simple. Also fixes a test because the image we were using changed.

Skeb: add support for multi-image posts and fix tests

---

app/logical/sources/strategies/nijie.rb
test/unit/sources/nijie_test.rb

Reported on discord. We weren't correctly falling back to the generic image domain for unsupported pictures.

Nijie: get correct image when using batch bookmarklet

---

app/logical/sources/strategies/weibo.rb

Reported on discord (https://discord.com/channels/310432830138089472/710192137878241372/848383207904378880)
Also compacted some code while I was there.

Weibo: fix new lengthier image urls breaking the batch bookmarklet

---

app/views/bulk_update_requests/show.html.erb

Example: https://danbooru.donmai.us/bulk_update_requests/5643
Becomes like this:
Also adds missing colons.
This was already done for the index but for some reason the individual pages were forgotten.

BUR individual page: show link to forum, not topic, if it exists

---

app/views/user_feedbacks/index.html.erb

This is a minor cherrypick, but it always annoys me.
On the [feedback creation page](https://danbooru.donmai.us/user_feedbacks/new) they're already ordered correctly.

Reorder feedback type dropdown search

---

app/javascript/src/javascripts/uploads.js.erb

Reported on discord. Right now you can still add flash files to the upload form (though their upload will fail at the processing stage, obviously).

Upload page: disallow swf uploads in javascript too

---

app/views/post_disapprovals/_counts.html.erb

Fixes #3786. 
I suppose a "nicer" way would be to color the individual messages a lighter or darker shade compared to the system message so that it's clear what the approvers said, but I felt that was adding too much noise to the interface. And I don't think anyone is spamming double quotes in the messages, so this should be good enough.
Example:

Quote different disapproval reasons to separate them

---

app/views/posts/partials/index/_related.html.erb

Just like it's done in wikis. I often find myself in need of this link when browsing posts.

Posts sidebar: add link to tag discussions in forums

---

app/views/uploads/batch.html.erb

Modern browsers open links in tabs, not windows

Fix text in batch bookmarklet

---

app/logical/post_query_builder.rb

Fixes #4435 by using the wildcard itself in queries where it would not have matched anything.
I am not familiar with Ruby, so this may need some refactoring. If so, please lend me a helping hand.
If wildcards did not match anything, they were completely ignored. If a search was a wildcard search and it did not match anything, it was like having an empty search box which then returned everything...
| User input | Real query | Result |
| :--- | :--- | :--- |
| \*non-existent\* |  | **Posts of the index page** |
| soranamae \*non-existent\* | soranamae | **Posts of soranamae** |
| serval_\* | ~serval_girl ~serval_print ~serval_tail | *Posts of serval_\** |
| takom serval_\* | takom ~serval_girl ~serval_print ~serval_tail | *Posts of serval_\* by takom* |
Wildcards add their wildcard form to …

Search: fix unmatched wildcards

---

app/views/static/site_map.html.erb

* Added a link to the related tags page, I personally always struggle to find this whenever I need it
* Moved the mod dashboard to the reports section, and removed the check, because the page is already accessible to everyone including anonymous users
* Added a link to user events for mods

Update site map

---

app/components/source_data_component/source_data_component.html.erb

Right now, even if an artist for weibo is matched, it won't show the box under "fetch source data", this one: 
This is because the faulty logic aborts early if the artist_name field in the source is blank, even if an artist tag exists.

Upload page: show artist tag if it exists even if artist_name is empty in source

---

app/logical/sources/strategies/skeb.rb
test/unit/sources/skeb_test.rb

Fixed for real this time!
Basically sometimes skeb offers a smaller, clean version (696x instead of 800x) of a picture along with the normal 800x version.
We want to only get that when the bigger version is watermarked, so the logic is:
- is the full size clean? if yes, filter out the smaller version if it exists and only get the clean 800x
- if the full size is not clean, is there a smaller version? if yes, get that, otherwise just get the full size watermarked one

Fix skeb strategy

---

app/views/pools/new.html.erb

Better to just put the usual embed wiki so that it can be fixed without changing the site code every time.

Fix broken link to howto:pools in /pools/new

---

app/logical/iqdb_client.rb

This makes the url lookup perform in the same way as file regeneration.
Fixes #4859.

IQDB direct url lookup: send the thumbnail instead of the full size

---

package.json
yarn.lock

[app/javascript/packs/flash.js](https://github.com/danbooru/danbooru/blob/master/app/javascript/packs/flash.js) imports `node_modules/ruffle-mirror/ea72e7bd92c6a211ab42071518cef232.wasm` whose filename varies across versions.

fix ruffle-mirror version

---

app/logical/sources/strategies/lofter.rb
test/unit/sources/lofter_test.rb

Lofter changed their image url schema so we should just check for the domain instead of the whole image url, otherwise it becomes a cat and mouse game.
Also removes a test that had become broken due to a link going 404.

Fix lofter strategy due to changes in their image urls

---

app/logical/bulk_update_request_processor.rb

Adds {{}} syntax to the destination of mass updates too.

Mass updates: make the destination search clickable

---

app/javascript/src/styles/common/simple_form.scss

Reported on discord. There's a few pages on the site where this missing CSS makes the form look weird. Among them:
[/iqdb_queries](https://danbooru.donmai.us/iqdb_queries):
[/artist_urls](https://danbooru.donmai.us/artist_urls):

Fix url fields in forms not having the same length as other text inputs

---

app/models/post.rb

Currently ugoira with broken samples can't be regenerated, since the PixivUgoiraFrameData object is passed rather than the actual data itself (.data). This causes an error:
```
undefined method `each' for #<PixivUgoiraFrameData:0x0000555740d784c0>
/var/www/danbooru/releases/20210815100842/app/logical/media_file/ugoira.rb:64:in `block (2 levels) in convert'
/var/www/danbooru/releases/20210815100842/app/logical/media_file/ugoira.rb:62:in `open'
/var/www/danbooru/releases/20210815100842/app/logical/media_file/ugoira.rb:62:in `block in convert'
/var/www/danbooru/releases/20210815100842/app/logical/media_file/ugoira.rb:40:in `convert'
/var/www/danbooru/releases/20210815100842/app/logical/upload_service/utils.rb:25:in `generate_resizes' …
```

Fix ugoira regenerations

---

app/logical/sources/strategies/base.rb
app/logical/sources/strategies/lofter.rb

There's infrequent reports of uploads failing with a timeout error for large images with Lofter. Currently one such case is https://kllia.lofter.com/post/2d278a_1c78bbaef. In my personal deployment it downloads the file in less than 5 seconds, but on Danbooru and Testbooru it fails with a timeout error, so it seems to be a regional issue. Raising the timeout might help.
We probably don't want to raise the timeout too much across the bar, so imo it makes sense to have a customizable option that can be raised by the individual strategies where necessary.

Lofter: raise timeout for file download

---

app/logical/sources/strategies/skeb.rb
app/logical/sources/strategies/weibo.rb

Both skeb and weibo weren't displaying the artist box in the upload page because of this property.

Sources: fix artist_name not being caught in skeb and weibo

---

app/helpers/application_helper.rb

There's now [11 tags](https://danbooru.donmai.us/tags?commit=Search&search%5Bhide_empty%5D=yes&search%5Border%5D=count) above 1M posts, and several users with edits in the millions, which currently look like this:
It makes sense to print these high numbers in a nicer way:
Worth noting that the [official notation](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes) dictates that kilo is lowercase while Mega is uppercase.

Add million scale to humanized number helper

---

app/logical/sources/strategies/foundation.rb
test/unit/sources/foundation_test.rb

While indexing foundation.app I found some weird account names. Turns out \w+ is not enough to catch all the possible cases.

Foundation: add support for unconventional account names

---

app/helpers/application_helper.rb

* only show the [+] and [-] feedback buttons to gold users
* only show the [promote] button to moderators, and only when targetting users
builder or below
* don't show either button if the target is the current user
* closes #4924

mod dashboard: minor cleanup

---

app/logical/spam_detector.rb

This is to match the max duration usable by mods in the site.
The previous value of 999999 seconds only amounted to 11 days: see [this user]( https://danbooru.donmai.us/users/851640) for example.

SpamDetector: raise autoban duration to 100 years.

---

app/models/upload.rb

Some twitter videos near the max duration had some stray milliseconds that made the check fail.
For example https://twitter.com/kivo_some_18/status/1152167154059321344?s=20 (nsfw) has 140.053333 duration.
I'm not sure if the fault is on twitter. Testing several videos with exactly 140 seconds of duration, the duration for us always ended up being 140.053333 seconds. In any case, rounding down solves this issue.

Fix duration check for uploads from twitter

---

app/logical/upload_limit.rb

My last PR has an issue: when setting configuration from a .env file, the ints are loaded as strings, causing fatal errors if you tried to set you own upload limits in this way.
`TypeError (String can't be coerced into Integer)`
A simple `.to_i` should fix this, since it's essentially a no-op when called on something that's already an integer. My apologies for missing it the first time.
Issue #4963

Fix bug with configurable upload limits

---

app/views/layouts/blank.html.erb
app/views/layouts/default.html.erb
app/views/robots/index.text.erb
public/favicon.svg
public/maintenance.html

Was using it for a while in my browser extension. Hand-crafted approximation of `favicon.ico` with brute-forced gradient angles and stops to get a lowest dssim score (0.00510548).
Dropped `shortcut` in `rel` since it is deprecated by html5 ([spec](https://html.spec.whatwg.org/multipage/links.html#rel-icon), [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types)).

Add svg favicon

---

app/views/posts/index.html.erb

When unset the width is inconsistent across browsers. 
In Firefox I measured 203px while in Chrome it is only 162px.

Tag script field: use full available width

---

app/models/user.rb

Yep, wow, me again. #4963. I'm ashamed to be on my third PR for this. Missed a hardcoded int last time, so new users were still given the default starting upload points. This time I built my own images and let it run for a week on my selfhosted instance because I would have probably died if another issue came up after this.

Fix initial upload points bug

---

app/javascript/src/styles/common/page_header.scss
app/views/layouts/_main_links.html.erb

It turns italic and is styleable when there's pending reports just like the forum link.
This is so that we can actually check at a glance if there's new reports without having to have a bookmark to the report page or using distill.

Moderation Reports: add link for moderators to navbar

---

app/logical/source/url/nijie.rb

Turns recent image URLs such as <https://pic.nijie.net/06/nijie/17/14/236014/illust/218856_1_7646cf57f6f1c695_f2ed81.png> into  post URLs (<https://nijie.info/view.php?id=218856>) on post pages. It seems like the post ID is included only if the image is from a multi-image post and is not the first item in the gallery.

nijie: extract post ID from new image URL

---

app/models/favorite_group.rb

The UI offers an option to sort by modification date but it doesn't do anything, might've been left out after a rewrite. This PR implements it.

favorite_groups: make search[order]=updated_at work

---

docker-compose.yaml

This is needed to create DanbooruBot and enable uploads, among other things.
Fixes #5011.

docker-compose: do db:seed before server start

---

app/logical/source/url/foundation.rb

Urls like https://foundation.app/@yohan1754/fso/3 would get normalized like https://foundation.app/@foundation/foundation/3, which was wrong because it would point to a completely different collection.
FIxes #5028.

Foundation: fix normalization error

---

app/logical/source/url.rb
app/logical/source/url/weibo.rb
app/logical/sources/strategies/weibo.rb
test/unit/sources/weibo_test.rb

Additionally, fixed some broken tests and changed normalization for urls of album type to point to the mobile version instead, because they're only visible to logged-in users.
As you can see I extracted url normalization too, since it's a method purely based on parsing, so it should not be in an extractor strategy now that we're separating them.
I thought about tackling normalize_for_source globally to move it from Sources::Strategies to Source::URL as I was doing that, but from a brief look I think that the rest of the strategies need to be factored out to their own Source::URL subclasses first, otherwise it's just too much of a mess to do all at once, so I opted to just do it for Weibo since I was rewriting it anyway. 
I also removed the wall of comments from the start, rather than …

sources: factor out Source::URL::Weibo

---

app/logical/sandbox.rb
config/danbooru_default_config.rb

Noticed inconsistent indentation when editing the config. `sandbox.rb` was the only other file I found wrongly using tabs.

Replace hard tabs with spaces in .rb files

---

app/logical/source/url/lofter.rb
app/logical/sources/strategies/lofter.rb

Now that we have a separate parsing class we can just use it to properly parse tag urls as well.

Lofter: simplify tag extraction logic

---

app/logical/source/url.rb
app/logical/source/url/tumblr.rb
app/logical/sources/strategies/tumblr.rb
test/unit/sources/tumblr_test.rb

Also adds support for fetching source data from direct image urls when possible.
Example: https://64.media.tumblr.com/7c4d2c6843466f92c3dd0516e749ec35/tumblr_orwwptNBCE1wsfqepo2_540.jpg

sources: factor out Source::URL::Tumblr

---

app/logical/source/url/art_station.rb
app/logical/source/url/fanbox.rb
app/logical/source/url/foundation.rb
app/logical/source/url/hentai_foundry.rb
app/logical/source/url/lofter.rb
app/logical/source/url/mastodon.rb
app/logical/source/url/moebooru.rb
app/logical/source/url/newgrounds.rb
app/logical/source/url/nijie.rb
app/logical/source/url/plurk.rb
app/logical/source/url/skeb.rb
app/logical/source/url/twit_pic.rb
app/logical/source/url/twitter.rb
app/logical/sources/strategies/plurk.rb

These comments are already present under the parse blocks, so the huge walls of text before the code are not needed anymore.
I left the twitpic ones since they're useful and moved around some info for plurk and skeb to more adequate places. The rest of the information was already present in one way or another elsewhere.

sources: remove redundant comments

---

app/controllers/modqueue_controller.rb
app/views/modqueue/_post.html.erb
app/views/modqueue/index.html.erb

Fixes #5029. I used PostPreviewComponent::DEFAULT_SIZE since PostGalleryComponent::PostGalleryComponent says it's to be used for a gallery, and modqueue entries are not arranged in a gallery, though I'm not 100% sure if that's correct.

Modqueue: support variable size thumbnails

---

app/javascript/src/styles/common/simple_form.scss

Hints are displayed below their fields on small screens.
Hints for `.text` and `.dtext` inputs weren't hidden even before this change.

simple_form: Don't hide hints on mobile. Fix #4997

---

app/models/media_asset.rb
config/danbooru_default_config.rb

This PR allows to easily configure max length of video by config or env variable.  
Previously 140 seconds (2:20 min) was hardcoded

Configurable max video duration during upload

---

config/danbooru_default_config.rb

adds screenshot and anime_screencap to the modqueue highlighted tags and removes screencap

Fix modqueue highlighting after topic #20445 (screenshots)

---

app/javascript/src/styles/common/main_layout.scss

I think the intent of c0610cb809f40d00bc0df02678986f9bf0103805 was to reduce the sidebar width on screens smaller than 1920px? Not sure why the 1080px query was added but it causes the sidebar to have no min-width on screens smaller than 1080px.

posts: fix sidebar min-width on small screens (fix #5052)

---

app/components/tag_list_component/tag_list_component.html.scss

Fixes rare cases of tags containing a long word overflowing outside the sidebar e.g.
https://danbooru.donmai.us/posts?tags=iwakiyamayukisatoshironanogojuurokushi_akira

tag_list_component: fix overflow of some long tags

---

app/logical/post_query_builder.rb

Fixes #4918 by guessing that the user wanted to search for the non "ord" version of the negated tags.
`-ordfav:USER` → `-fav:USER`
`-ordfavgroup:ID` → `-favgroup:ID`
`-ordpool:ID` → `-pool:ID`
**Note:** It doesn't fix `-order:rank` and other negated `order` searches.

Search: "Fix" negated ordered metatags

---

app/javascript/src/styles/common/dtext.scss

A small delay on the pointer-events property prevents accidentally
opening a link inside a spoiler when tapping to reveal the spoiler on
mobile.

css: prevent acidentally opening spoilered links

---

.gitignore

This folder is created by running `bundle install`. It can quickly overwhelm IDEs like vscode since there's potentially thousands of files in there.

Add /vendor to .gitignore

---

app/logical/bulk_update_request_processor.rb
app/policies/tag_policy.rb
test/functional/tags_controller_test.rb
test/unit/bulk_update_request_test.rb

This was raised as a concern in the discord, and I agree that a requirement for deprecating tags would be to offer alternatives in their wiki.
Also fixed and moved the tests for the BUR because I realized I had put them in the wrong place.

Tags: don't allow deprecation of tags without wiki

---

app/controllers/post_disapprovals_controller.rb
app/controllers/posts_controller.rb
app/models/post.rb
app/policies/post_disapproval_policy.rb
app/views/modqueue/_quick_mod.html.erb
app/views/post_disapprovals/_detailed_rejection_dialog.html.erb
app/views/post_disapprovals/update.js.erb
app/views/posts/partials/show/_notices.html.erb
app/views/posts/partials/show/_options.html.erb
config/routes.rb
test/functional/post_disapprovals_controller_test.rb

Fixes #3470.
Makes these controls always be visible.
Message can be edited (and is prepopulated) by clicking on "detailed rejection".
Minor change: "No interest" in the controls now is "disinterest", just like the metasearch and the actual reason in the code. 
I thought about just changing everything from disinterest to no_interest but wasn't sure if that was desired, since it would be a breaking change, and adding additional code just to display "no interest" felt like a hack to preserve a legacy aspect.
@evazion lemme know what you prefer and I'll add a follow-up commit.
This also removes the two "approve" and "hide from queue" buttons in the sidebar, which are useless if these controls are always visible.

Allow post disapprovals to be edited

---

app/models/post.rb
test/unit/post_query_builder_test.rb

Only matches on the current user's favgroups.

favgroups: allow favgroup:any/none searches

---

app/models/post_appeal.rb
app/models/post_flag.rb
test/unit/post_disapproval_test.rb

Fixes #4876.
Evazion mentioned that an alternative was to stop deleting disapprovals and mark them as soft deleted, however I'm not sure that's useful for us. I count more than 100k existing disapprovals right now, and that's even considering that they're purged monthly. The table risks ballooning out of proportion for no real benefit and the same behavior.

Posts: prune disapprovals on new appeal or flag

---

app/logical/source/extractor.rb
app/logical/source/extractor/booth.rb
app/logical/source/url/booth.rb
app/models/artist_url.rb
test/test_helper.rb
test/test_helpers/source_test_helper.rb
test/unit/sources/booth_test.rb

Fixes #5079.
Also adds a test helper to automatically handle all of the soul-sucking parts of writing source tests.
For getting the full image from the sample, it tries looping through the possible image extensions (png, jpg and jpeg) in order to find the existing one, like the artstation strategy does.

Add Booth support

---

app/views/posts/show.html.erb

I'm a dumbass and I didn't realize this button had a shortcut attached.
The quick mod buttons are also used in the modqueue so it's not possible to bind the shift-o shortcut to them, hence the need for this.

Readd approval button to the sidebar

---

app/logical/source/url/null.rb
test/unit/sources/null_test.rb

Fixes #5072. One of the examples in that issue is still not normalized correctly but that's because the fandom name can't be extracted from the url. Nothing we can do in that case.

Fix normalization for fandom sources

---

app/logical/source/extractor/foundation.rb
app/logical/source/url/foundation.rb
test/test_helpers/source_test_helper.rb
test/unit/sources/anifty_test.rb
test/unit/sources/booth_test.rb
test/unit/sources/foundation_test.rb

Fixes #5121.
Also refactors foundation tests and adjusts SourceTestHelper to not autogenerate contexts, so that tests can be launched individually.

Foundation: fix some video posts not being extracted

---

app/javascript/src/javascripts/related_tag.js
app/views/related_tags/_current_tags.html.erb

Fix #5154
Only add `toggle_tag` listener to links with the `search-tag` class,
add `target="_blank"` to wiki links to prevent accidentally leaving the
edit form.

related tags: fix wiki link adding "undefined" tag

---

app/views/posts/show.html+tooltip.erb

Show "non-web source" in the tooltip instead of "no source", link to the
`non-web_source` tag and show the source on mouseover.

post tooltips: add support for non-web sources

---

app/logical/source/extractor/furaffinity.rb
test/unit/sources/furaffinity_test.rb

Use Addressable::URI, which supports non-ascii urls.

Furaffinity: fix uploads for non-ascii image urls

---

app/components/categorized_tag_list_component/categorized_tag_list_component.html.erb
app/components/inline_tag_list_component/inline_tag_list_component.html.erb
app/components/search_tag_list_component/search_tag_list_component.html.erb
app/views/explore/posts/missed_searches.html.erb
app/views/explore/posts/searches.html.erb

Allows using custom CSS to highlight deprecated tags, fixes #5110
```css
[data-is-deprecated='true'] a, a[data-is-deprecated='true'] {
color: var(--low-post-count-color) !important;
}
```

Add data-is-deprecated attribute to tags

---

app/views/layouts/default.html.erb

The commit hash is shown when hovering over the app name in the footer.

Add back current commit hash to site footer.

---

app/logical/note_sanitizer.rb

These properties are widely supported: https://caniuse.com/text-stroke
Currently some notes use multiple text-shadows as a workaround:
https://danbooru.donmai.us/notes?search[body_matches]=text-shadow

Notes: allow using -webkit-text-stroke and related

---

app/policies/bulk_update_request_policy.rb
app/views/bulk_update_requests/_bur_edit_links.html.erb

Also fix bad formatting for non-admins in BUR index.
Right now they look like:
I suppose approved BURs could be edited because they often failed so you had to fix them manually, but now they just go into a failed status instead.

BURs: don't allow edits to approved scripts

---

app/logical/note_sanitizer.rb

[It's supported by roughly the same browsers ](https://caniuse.com/?search=-webkit-background-clip) as the [previous added properties](https://github.com/danbooru/danbooru/commit/c909555da85c17dac065507e971468248b908b1e) and if everything works fine, it'll allow the translator to make gradient texts and such without resorting to [multiple `<span>` or `<div>` blocks](https://danbooru.donmai.us/posts/4954692?q=noteupdater%3AHyozen+order%3Anote+unconnected_marketeers+) when used along with `-webkit-text-fill-color: transparent`: https://www.w3schools.com/code/tryit.asp?filename=GT23TR6IBESV

Allow background-clip and -webkit-background-clip properties in notes

---

config/danbooru_default_config.rb

Posts should be judged by the quality of the art, there's nothing inherently worse about a self upload than any other post.

Modqueue: remove self_upload from highlighted tags

---

app/models/wiki_page.rb

As of right now, api wiki pages are categorized as "general" when they should be categorized as "meta". Please see issue #5206

Added `api:` to the list of META_WIKIS

---

app/javascript/src/styles/common/main_layout.scss
app/javascript/src/styles/specific/post_tooltips.scss

Follow-up to 136e2777cb514763fb994565882ad737e201cc81, which didn't account for the wiki_pages sidebar.
Additionally fix tags containing long words causing the post tooltip to overflow (realistically this only happens for tooltips containing a preview image), for example post #1489167:
The post tooltip fix needs the `overflow-wrap: break-word`, so I didn't revert 136e2777cb514763fb994565882ad737e201cc81.

Fix some long tags / wiki links overflowing their container

---

app/views/favorite_groups/_secondary_links.html.erb
app/views/static/keyboard_shortcuts.html.erb

Add edit (<kbd>e</kbd>) and delete (<kbd>shift</kbd> + <kbd>d</kbd>) keyboard shortcuts for favorite groups, in the same fashion as artists, forum, pools, and wiki.
I plan to add a few more as mentioned in #5175, please let me know if there's anything :)

Add keyboard shortcuts for favorite groups

---

app/models/wiki_page_version.rb

It is a bit inconvenient to see when pages were locked since it doesn't show on the history page at the moment.

show locked/unlocked changes on wiki page histories

---

app/javascript/src/styles/common/user_styles.scss
app/models/user.rb
app/policies/user_policy.rb
app/views/users/edit.html.erb

The previous behavior can be replicated by putting the following in the custom css:
.user { color: var(--link-color) !important }
This is an alternative to pull #5296. It doesn't make sense for us to keep this as a setting anymore given that those who don't want it can just use custom css.

Users: display colored usernames by default

---

app/models/post.rb

I first raised this in issue #3261 when I was a member, because it REALLY sucked to not be able to fix your own uploads. Five years and several user levels later I still think this is a very annoying restriction that has no reason to exist and is really frustrating to new users. Nobody is going to buy an account just to see their own uploads.

Posts: show levelblocked posts to their uploader

---

db/structure.sql

This commit aligns the repo's structure.sql to the one that is altered by db:migrate, so that just having your own instance is not enough to fuck up tracking. 
It's mostly reordering of columns, however there's two changes: it alters `created_at` and `updated_at` for `public.ar_internal_metadata` from `timestamp` to `timestamp(6)` (which seems to be the default for postgres), but it also removes the index `index_user_upgrades_on_created_at`. I'm not sure if that's intended, or if there's a missing index that was never added as a migration and this is a bug on freshly created instances. If that's the case, it should be fixed.

Update structure.sql to the one generated by db:migrate

---

app/views/uploads/_single_asset_upload.html.erb

Similar to how there's a link on the post page. For convenience of checking metadata.

uploads: link to the media asset from the upload page

---

app/controllers/admin/users_controller.rb
app/helpers/application_helper.rb
app/javascript/src/styles/common/user_styles.scss
app/logical/approver_pruner.rb
app/logical/post_query_builder.rb
app/logical/upload_limit.rb
app/logical/user_promotion.rb
app/models/post.rb
app/models/user.rb
app/policies/user_policy.rb
app/presenters/user_presenter.rb
app/views/admin/users/edit.html.erb
app/views/post_disapprovals/_compact_counts.html.erb
app/views/post_disapprovals/_counts.html.erb
app/views/uploads/_single_asset_upload.html.erb
app/views/users/_statistics.html.erb
app/views/users/_upload_limit.html.erb
app/views/users/index.html.erb
app/views/users/show.html+tooltip.erb
db/populate.rb
script/fixes/122_populate_approvers_and_contributors.rb
test/factories/user.rb
test/functional/admin/users_controller_test.rb
test/functional/posts_controller_test.rb
test/functional/users_controller_test.rb
test/unit/approver_pruner_test.rb
test/unit/post_appeal_test.rb
test/unit/post_approval_test.rb
test/unit/post_flag_test.rb

As discussed before. 
`script/fixes/122_populate_approvers_and_contributors.rb` needs to be run to transform unrestricted/approvers to the new level. 
I left the automatic demotion for approvers to how it was, because I imagine it would make people butthurt to get "You have been demoted" as a feedback for being inactive, but let me know if it doesn't matter and it should just leave a normal demotion feedback instead.
I couldn't run the functional tests because of this error:
```
Minitest::UnexpectedError:         RuntimeError: failed to execute:
psql --set ON_ERROR_STOP=1 --quiet --no-psqlrc --output /dev/null --file /danbooru/db/structure.sql danbooru-1
Please check the output above for any errors and make sure that `psql` is installed in your PATH and has proper permissions.
```
but I …

Users: add Contributor and Approver user levels

---

app/logical/source/extractor.rb
app/logical/source/extractor/bilibili.rb
app/logical/source/url.rb
app/logical/source/url/anifty.rb
app/logical/source/url/bilibili.rb
app/logical/source/url/nico_seiga.rb
app/models/artist_url.rb
test/unit/sources/bilibili_test.rb

Fixes #5321. Adds support for t.bilibili.com, h.bilibili.com and bilibili.com/read. Videos are not supported because it looked like too much of a pain to extract them.
Also updates the artist url order. We should generate that list automatically eventually.

Add bilibili support

---

app/components/categorized_tag_list_component/categorized_tag_list_component.html.erb

The call to `#capitalize` doesn't inflect properly and the call to `#pluralize` doesn't work right as it is receiving an array instead of a number.

fix category text formatting in CategorizedTagList template

---

.rubocop.yml

rubocop: fix typo

---

app/views/wiki_pages/_secondary_links.html.erb

Right now, if you click Edit or hit the "e" shortcut key while editing a wiki page, the page will essentially reload, and you could lose all your changes without warning. A user on Discord had this issue because they forgot they were in Preview mode and clicked Edit again.
This makes it so Edit doesn't show when you're editing. Edit is only visible when Delete isn't.

views: Don't show 'Edit' link when editing a wiki

---

README.md

Removed deprecated `docker-compose` command and replaced with `docker compose`. Also added a reminder that `docker compose` may need to be run with elevated privileges.

Removed deprecated docker command

---

app/logical/source/url/fantia.rb
test/unit/sources/fantia_test.rb

Considering that the most efficient way to upload free-tier fantia rewards that I'm aware of is to open the full-size image and upload it using the browser extension, this will save uploaders a few clicks each post due to not having to manually copy-and-paste fantia post url into the upload form.

fantia: extract free tier reward post page url from full size image page url passed as referer

---

app/logical/source/extractor/bilibili.rb

I noticed that bilibili checks User-Agent header, forcing browsers other than the newest Firefox or Chrome to pass captcha, but for some reason empty User-Agent also works.
Additionally, use more realistic url - of a work page - as a Referer.

Fix bilibili uploads

---

app/logical/source/extractor/pixiv.rb

There is an issue with `Source::Extractor::Pixiv.to_dtext` that causes `test/unit/sources/pixiv_test.rb:154` and `test/unit/sources/pixiv_test.rb:165` to fail if the Pixiv account that is used for extractor is set to language other than English.
It is worth to notice is that at the moment the bug reproduces on the actual Danbooru (e.g. post #5111725) - which can be kinda fixed by changing the language of the account used over there.

pixiv: fix dtext conversion for non-english pixiv accounts

---

app/components/tag_change_notice_component.rb
app/components/tag_change_notice_component/tag_change_notice_component.html.erb
app/helpers/components_helper.rb
app/logical/post_sets/post.rb
app/views/posts/index.html.erb
app/views/wiki_pages/new.html.erb
app/views/wiki_pages/show.html.erb

Fixes #5563, and adds the tag change notice to wiki pages.
Case of one topic, one BUR:
Case of one topic, multiple BURs:
Case of multiple topics, mixed BUR count:
Adding a link to the topic in case of multiple BURs in the same topic seemed too noisy to me, but lemme know and I'll change it if it's desiderable.

Turn tag change notice into component, handle multiple burs in same topic

---

app/controllers/post_disapprovals_controller.rb
app/views/post_disapprovals/create.js.erb

This is similar to how approval errors are currently handled ([app/views/post_approvals/create.js.erb][]).
Fixes #5666. Also fixes an issue where disapproval errors would get silently ignored until next page load if the disapproval was created from the modqueue.
[app/views/post_approvals/create.js.erb]: https://github.com/danbooru/danbooru/blob/d67bd670916644017a83a3de8fc5d0bdb3404585/app/views/post_approvals/create.js.erb

disapprovals: handle disapproval errors in the view

---

lib/dtext_rb/ext/dtext/dtext.cpp.rl

Fixes incorrect parsing of the `</blockquote>`. There was a simple typo/copy-paste error in the parsing rule which meant the parser was attempting to match on a closing square bracket (`]`) instead of the closing angle bracket (`>`). This has been corrected to allow this tag to be parsed correctly.

[DText] Fix: Correct parsing of blockquote closing tags

---

app/logical/concerns/searchable.rb
test/unit/post_query_builder_test.rb

Fixes #5552
Fix a bug when post user_tag_match would use ordering which contained a left_outer_joins relation, it would not include relation when constructing a select query.
For example
```ruby
Post.user_tag_match("order:disapproved", User.first).to_a
Post.user_tag_match("order:modqueue", User.first).to_a
```

 Fix a bug with Post.user_tag_match sql generation

---

app/logical/related_tag_calculator.rb

At `RelatedTagCalculator::RelatedTag#overlap`, using integer `tag.post_count` leads to integer division in `jaccard_similarity` and `overlap_coefficient` methods.
Fixes #5803

related tags: fix integer division in similarity values calculator

---

app/models/user_feedback.rb
app/views/user_feedbacks/index.html.erb

This has been bugging me for a while. In times of heavy spam or sockpuppeting, the feedback page becomes pretty much unreadable, and there's no easy way to filter bans out of it.
This pull adds a simple dropdown that allows us to remove standard ban messages from the results, with default being no filtering (same as status quo).
https://danbooru.donmai.us/user_feedbacks?commit=Search&page=8&search%5Bbody_regex%5D=%5EBanned shows that the only false positives were joke bans made for april fools', so more accurate filtering doesn't seem necessary.

User Feedbacks: add option to hide ban messages from search results

---

app/components/media_asset_component/media_asset_component.scss
app/models/media_asset.rb
app/models/moderation_report.rb
app/policies/media_asset_policy.rb
app/policies/moderation_report_policy.rb
app/views/media_assets/show.html.erb
app/views/moderation_reports/_new.html.erb
app/views/moderation_reports/index.html.erb
test/functional/moderation_reports_controller_test.rb

Fixes #5825.
Still a WIP, need to add tests and think of edge cases.
Media assets can only be reported if they're not associated to posts, otherwise flags must be used. Because of that, I added a different wiki for media asset report notices so that this can be explained separately.
The main change is that it changes reported_user to reported_users, because media assets can be associated with multiple uploads.

Make media assets reportable

---

app/components/media_asset_component/media_asset_component.scss
app/models/media_asset.rb
app/models/moderation_report.rb
app/policies/media_asset_policy.rb
app/policies/moderation_report_policy.rb
app/views/media_assets/show.html.erb
app/views/moderation_reports/_new.html.erb
app/views/moderation_reports/index.html.erb
test/functional/moderation_reports_controller_test.rb

Reverts danbooru/danbooru#5830, it's clear there's no interest in the feature anyway, should've never have merged it and left it to die with the rest of the pulls.

Revert "Make media assets reportable"

---

app/logical/source/extractor/nico_seiga.rb
test/unit/sources/nico_seiga_test.rb

1. The site now requires special user-agent header for non-japanese IPs
2. Age-restricted images have been removed from the site, and therefore are removed from tests

sources: fix nico seiga extractor

---

app/logical/source/extractor/xiaohongshu.rb
app/logical/source/url/xiaohongshu.rb
test/unit/sources/xiaohongshu_test.rb

1. xsec_token query parameter is now required for posts
2. include artist id in post url whenever available
3. extract formatted artist commentary from page html, as opposed to unformatted commentary from json
4. some tests (A video post, A post with /spectrum/ image URLs) still fail, as i didn't bother to find new appropriate posts to test them.

sources: Xiaohongshu extractor fixes/tweaks

---

app/logical/source/extractor/arca_live.rb
app/logical/source/url/arca_live.rb
test/unit/sources/arca_live_test.rb

1. Use the canonical post url when extracting from `/b/breaking` page (#5890)
2. Replace redirect links with actual urls in artist commentary
3. Use the original file extension for videos to support .gif, .webp, or actual .mp4 files (#5875)

arca.live extractor tweaks

---

app/logical/source/extractor/bilibili.rb
app/logical/source/url/bilibili.rb
test/unit/sources/bilibili_test.rb

Fixes #5868
- `api.bilibili.com` is not used anymore, only json from the web page is used.
- `/read/cv` urls seem to be not used anymore, and instead redirect to `/opus/`
- "canonical" post url format changed from `https://t.bilibili.com/` to `https://www.bilibili.com/opus/`, as the latter seems to be more "full" (compare https://www.bilibili.com/opus/428178320677065986 and https://t.bilibili.com/428178320677065986)
- `dtext_artist_commentary_desc` works on existing tests, but might be actually a bit broken. I can't create an account there to test out all the possible bullshit formatting supported by myself. Will gladly accept help if offered though. Just to note, parsing the html from the page is not an option either, as it is also seems to be incomplete.
- For now, reposts support is …

bilibili: refactor the extractor

---

config/nginx.conf

On provided `nginx.conf`, the `break` statement (from `ngx_http_rewrite_module`) executed too early, so that the following `if ($arg_download) { ... } ` block executed never. This commit fixes it by putting the `break;` on it's own line at the end of the location block.
The reasons it looked like it worked are:
1. Locally, it was most probably, if at all, tested by left-clicking the "Download" button on post (huh!), which initiated download because the `<a>` element had `download` attribute.
This wouldn't have worked if the user clicked the button with the middle mouse button (resulting it to just opening in a new tab), or reached that url through other means, or, while not directly applicable here, if the anchor location was cross-origin (as both Firefox and Chromium ignore it in that …

docker: Fix Download link on posts

---

app/views/static/bookmarklet.html.erb

https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Schemes/javascript
> If this completion value is a string, that string is treated as an HTML document and the browser navigates to a new document with that content, using the same URL as the current page. 
https://datatracker.ietf.org/doc/html/draft-hoehrmann-javascript-scheme
> In typical implementations, when the user activates the hyperlink, the web browser will pass control to the doSomething() function, and render its result, if any, in place of the current document.

/static/bookmarklet: fix the bookmarklet to comply with `javascript:` URI standard

---

app/logical/bulk_update_request_processor.rb
test/unit/bulk_update_request_test.rb

Fix an issue that prevented admins from approving
unimply a -> b
imply a -> c
when "b -> c" already existed.
Fixes #5938

Bulk Update Requests: fix some ValidationErrors

---

Gemfile

Using a brand new Master branch pull/run, we see the following:
> /home/danbooru/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30: warning: /usr/local/lib/ruby/3.3.0/abbrev.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add abbrev to your Gemfile or gemspec.
It suggests that while we load from the standardlib (which is fine as long as we version lock to ruby < 3.4.0), it's still recommended to add abbrev to either Gemfile or gemspec.
I added it to Gemfile.  This should behave/work and remove the deprecation warning.

Update Gemfile: abbrev no longer in Ruby 3.4.0+

---

app/javascript/src/javascripts/notes.js
app/javascript/src/javascripts/posts.js
app/javascript/src/javascripts/ugoira.js
app/javascript/src/styles/specific/notes.scss
app/javascript/src/styles/specific/posts.scss
app/views/posts/show.html.erb

There are three things incorrect as of now:
First, `Note.Box.scale_all`, which is supposed to adjust font size for embedded notes, applied it to the whole image/notes container, which also contained ugoira controls, making them incorrectly sized, and the image itself, giving it a large top padding.
The fix is to change `font-size` only for `.note-box` elements.
Second, `Post.resize_ugoira_controls` couldn't calculate the right slider width - it was trying to use the image's width, but the image itself adjusted own width to match slider.
The fix is to get rid of that function and just use CSS.

posts: fix "Resize to window" for ugoira

---

app/javascript/src/javascripts/autocomplete.js

Sometimes people make typos when writing tags. If you're trying to write `brown_eyes` you may write `brow_e` and only then notice your mistake:
So you move your caret back and fix the typo:
But now autocomplete doesn't see the `_e` part that comes after your cursor, so it's putting `brown_hair` above `brown_eyes` in the suggestions.
So you press down a couple times and manually select the second result instead, and then press tab so it completes `brown_eyes`:
Now there's some junk at the end that will mess up your search, since `_e` is not a real tag. So you have to manually delete that before hitting enter.
This pull request makes a simple change to autocomplete so that it pretends the cursor is at the end of the current term rather than being in the middle. This way, it sees `brown|_e` …

Autocomplete: Improve behavior when caret is in the middle of a term

---

app/javascript/src/javascripts/autocomplete.js

Currently, if you're modifying a term that is not the last one in the text field:
And you press tab to insert a completion:
It will insert one space after the term, then your caret, then the next term immediately after your caret.
The issue with this is that, with the change from #5954, autocomplete now can't see a difference between a new term you start typing and the next term that comes immediately after that, as they are only separated by your caret and no space:
This pull request makes a change so that in addition to the space after the previous completed term, another space will be added after your caret (but only if there's another term after it):
This allows autocomplete to work in this scenario without having to manually add a second space or move your caret to the end:

Autocomplete: Insert extra space after caret when completing between two terms

---

app/helpers/application_helper.rb
app/logical/bulk_update_request_processor.rb
app/models/bulk_update_request.rb
app/models/tag_implication.rb
app/views/bulk_update_requests/_form.html.erb
test/unit/bulk_update_request_test.rb

This basically just adds `[[]]` and `{{}}` around each tag name in BUR/implication errors, so that they are automatically styled by the site. 
The errors then become like this:
Which makes it infinitely easier to parse the error message, especially in the case of large BURs.
Compare with the status quo:
This partially mitigates the problems in issue #5492.

Bulk Update Requests: display better errors

---

app/logical/source/extractor/reddit.rb
app/logical/source/extractor/reddit_comment.rb
app/logical/source/url/reddit.rb
test/unit/sources/reddit_test.rb

Fixes #5900 for the most part, using a different JSON endpoint instead of scraping HTML. Also slightly improved commentary parsing while fixing the tests.
One slight deviation is that posts with external images (see test `A reddit post with an external image` now return the linked URLs in `image_urls`. The old extractor returned `external-preview` Reddit URLs, but I could not get these to reliably return an actual image, while this one at least works for sites like Twitter.
Another option would be to return no URLs, which would be trivial since the API response contains a boolean for it.

Fix #5900: Fix Reddit extractor

---

app/logical/source/extractor/xiaohongshu.rb
app/models/site_credential.rb
config/danbooru_default_config.rb

Credit to @hdk5 for figuring out that for some reason passing a dummy `webId` and `web_session` is enough.

Xiohongshu: add cookies to extractor

---

db/migrate/20250601164355_align_pool_versions_to_prod.rb
db/migrate/20250601164357_align_post_versions_to_prod.rb
db/migrate/20250601164359_add_missing_post_versions_index.rb
db/structure.sql
docker-compose.dev.yaml
docker-compose.yaml

This pull adds a local SQS mock that makes post versions available locally and to codespaces for development and testing.
Still a WIP, I need to add it to the non-dev docker compose file as well and figure out the various options.
This pull also contains migrations that align the schema to the one used by danbooru in production.
Fixes #5255.

Add sqs mock for local development

---

app/javascript/src/javascripts/autocomplete.js
app/javascript/src/javascripts/related_tag.js
app/javascript/src/javascripts/tag_counter.js

Commit 2aaa99ef882872d24be079a35f63dd5d601033c3 fixes the issue with related tags reported here: https://github.com/danbooru/danbooru/issues/5958#issuecomment-2901883495
That issue occurs because clicking on a related tag to toggle it triggers a programmatic "input" event in order to update the tag counter, which causes an autocomplete search to be performed. It only occurs on Chrome and not Firefox for some reason. Removing the artificial input and using a custom trigger to update the tag counter fixes this.
Commit 1b7d6d08d5f6a7d89fc3a3e15fd1d04fe296bab1 fixes the issue with reopening a closed tab reported here: https://github.com/danbooru/danbooru/issues/5958#issuecomment-2910718251
That issue occurs because an "input" event is triggered when a closed tab is reopened. It only occurs on …

Fix two bugs that could cause an autocomplete search to be triggered without user input

---

app/logical/source/url.rb
app/logical/source/url/ci_en.rb
app/logical/source/url/fantia.rb
app/logical/source/url/misskey.rb
app/logical/source/url/null.rb
app/logical/source/url/pixiv.rb
app/logical/source/url/twitter.rb
app/models/post.rb
app/models/upload_media_asset.rb
app/views/uploads/_single_asset_upload.html.erb
test/unit/source/url/ci_en_url_test.rb
test/unit/source/url/fantia_url_test.rb
test/unit/source/url/misskey_url_test.rb
test/unit/source/url/null_url_test.rb
test/unit/source/url/pixiv_url_test.rb
test/unit/source/url/twitter_url_test.rb

* Recognize image sample URLs from Pixiv, Twitter, E-Hentai, Misskey
* Autotag posts with `image_sample` on save if source field contains such URL
* On upload, if URL can't be converted into something better, show a warning
Closes #5508

Add image sample URL recognition

---

app/models/artist.rb
test/unit/artist_test.rb

- Override `other_names=` to automatically remove elements that exactly match the artist name
- Add comprehensive test cases covering various scenarios including case sensitivity
- Ensure other_names array stays clean without main artist name duplicates

feat(artist): add `other_names=` method to prevent duplicate artist names

---

app/javascript/src/javascripts/autocomplete.js
app/javascript/src/javascripts/dtext_editor.js
app/javascript/src/javascripts/undo_stack.js
app/javascript/src/javascripts/utility.js

The first five commits are several bugfixes and quality-of-life improvements for autocomplete. Details are included in each commit. Between these five commits, I believe the following issues should now all be resolved (as well as some other issues I haven't seen reported anywhere):
* Fixes #5251
* Fixes #5958: When deleting a tag, the caret remains before the next tag, interfering with autocomplete for the next term you type
* Fixes the issue reported in the second half of [this comment](https://github.com/danbooru/danbooru/pull/5954#issuecomment-2954619440): Autocomplete results not updated when moving caret to a different term
The sixth commit is slightly different from the others, as it completely replaces the native undo/redo implementation with a custom one for tag input fields. My …

Various fixes and improvements for autocomplete

---

app/javascript/src/javascripts/autocomplete.js

There was a bug in the regex for these shortcut overrides which meant that if your caret was in this position, with only separators at the edge of the string:
`looking_at|_`
Pressing Ctrl+Right wouldn't move the caret to the end, it would be stuck before the underscore. And pressing Ctrl+Delete wouldn't delete the underscore either.

Fix Ctrl shortcuts ignoring separators at edges of string

---

app/javascript/src/javascripts/autocomplete.js

Related to commit 35494be3c60e6540b2da847348dbf777857acb2f
> Now Ctrl+Right moves past spaces at the end of tags, which matches normal browser behavior.
I was confused by this statement as when I tested it on both Firefox and Chrome Ctrl+Right did not move past the final space. After some more testing, it would seem this behavior actually varies not on your browser but your operating system. On Windows it skips the final space in both browsers, but on Linux it doesn't. (Unsure about Mac.)
Furthermore, desktop GUI frameworks like Qt seem to have the Windows behavior even on Linux. So not skipping the space is something that specifically only browsers do, and only on Linux.
If we wanted to emulate native behavior as closely as possible we would need to detect the user's operating system and …

Another minor tweak to Ctrl+Right

---

app/javascript/src/javascripts/autocomplete.js

https://github.com/danbooru/danbooru/pull/6074#issuecomment-3030057174
> I think this will require some further tuning to get things working just right. One issue is that it's currently hard to delete words in the middle of a tag. For example, if you have `hand_on_own_hip`, you should be to easily delete `own` and replace it with `another's` to get `hand_on_another's_hip`. Or if you have `artoria_pendragon_(lancer)_(fate)`, you should be able to easily delete `lancer` and replace it with `swimsuit_ruler`.
> 
> Currently it's hard because it inserts spaces after deleting words, which breaks deleting words inside tags. But even if you get rid of that, there are still issues with it not working how you would like in some cases. For example, if you're at the start of `lancer` in …

Tag autocomplete: Treat the caret as a wildcard in the middle of a term
